### ISSUE TITLE
behavior of Step button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#100]
From the design doc:

<img width="610" alt="screenshot_383" src="https://user-images.githubusercontent.com/3046552/84084643-124bae80-a9a1-11ea-9484-db3aa3cb00a1.png">

In 6/8/2020 Zoom discussion with @amanda-phet, she said that the step button behaves differently in the Java version.  It's more like a fast-forward control, and she uses it frequently.  And it's enabled while the sim is playing, not just while paused.

The HTML5 version is currently using the standard `TimeControlNode` that is used by all HTML5 sims.   There's also nothing in the HTML5 version that supports fast-forward.  And if the dt associated with the Step button is too large, we will risk stepping over important operations in the model.  For example, you could skip right over the part of the model that deals with food or wolves.  Adding fast-forward support would be a major change as this point in development.

There are currently 2 query parameters that control time, see documentation below.  Maybe a larger `secondsPerStep` will give @amanda-phet what she's looking for.  But again, a value too large may skip over operations in the model.

Assigning to @amanda-phet to decide how to proceed.

```js
  // Seconds of real time per cycle of the generation clock.
  // For internal use only.
  secondsPerGeneration: {
    type: 'number',
    defaultValue: 10,
    isValidValue: value => ( value > 0 )
  },

  // Seconds of real time per each press of the Step button.
  // For internal use only.
  secondsPerStep: {
    type: 'number',
    defaultValue: 0.1,
    isValidValue: value => ( value > 0 )
  },
```

**Comment by amanda-phet** [comment]
6/18/20 questions
- Can we hide the step button?
- Can we add a radio button group that has "Fast" and "Normal"? 
- **Can we add a "fast forward" button that speeds ahead? Instead of the step button. The user would hold the button to run the sim at a faster speed.** 

@pixelzoom will try the third bullet!

**Comment by pixelzoom** [comment]
In the above commit, I replace TimeControlNode with a custom time control (NaturalSelectionTimeControl).  The fast-forward button is not hooked up yet.

**Comment by pixelzoom** [comment]
@amanda-phet ready for review in master or in 1.0.0-dev.56:

phet: https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.56/phet/natural-selection_en_phet.html

phet-io: 
https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.56/phet-io/

Notes:
* Use query parameter `fastForwardScale` to set the scale factor for time while the fast-forward button is pressed.  For example `?fastForwardScale=4` (the default) scales time by 4x. Let me know if you'd like to change the default.
* The fast-forward button can be pressed while the sim is playing or paused. 
* While the fast-forward button is pressed, the play/pause button cannot be used, so it is disabled.
* If the fast-forward is pressed while the sim is paused, you'll see the (disabled) play/pause button change to play, and the sim will be restored to paused when  the fast-forward button is released.
* As in the Java version, pressing the fast-forward button does not make bunnies or wolves move any faster.  Let me know if you'd like that changed and I will investigate the implications.


Since we're no longer using the common-code TimeControlNode, you'll need to review and approve the PhET-iO instrumentation and Studio tree (shown below). `playPauseButton` is the same common-code button used in TimeControlNode. `fastForwardButton` is specific to natural-selection.

<img width="237" alt="screenshot_410" src="https://user-images.githubusercontent.com/3046552/85167727-80f0fd80-b226-11ea-8bd0-5019be561986.png">

**Comment by pixelzoom** [comment]
After making a couple more PhET-iO tweaks, I update the previous comment to refer to 1.0.0-dev.57.

**Comment by amanda-phet** [comment]
I am LOVING the fast-forward button. It is behaving exactly as I want it to. The 4x speed seems perfect. I intuitively click it to jump ahead a little, or click and hold to really fast-forward, and no longer feel stifled without my `secondsPerGeneration` query parameter. 

The PhET-iO instrumentation/studio tree looks fine to me.

**Comment by amanda-phet** [comment]
Looks great!
