### ISSUE TITLE
how to write the genotype abbreviation?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#104]
I noticed that sometimes a bunny's heterozygous genotype could be displayed as "Ff" or "fF", depending on if the recessive allele is inherited from the mother or father. Can you be sure that in this case we always display the genotype as "Ff", so capital first then lowercase, regardless of the inheritance? I typically see capital first, and while I can't confirm that this is an established convention, it looks very strange to display lowercase first.

**Comment by pixelzoom** [comment]
The convention is "father mother", not "capital lowercase".

**Comment by pixelzoom** [comment]
The convention is "father mother", not "capital lowercase".   "Ff" and "fF" are different genotypes, with different meaning.  "Ff" mean "F" from father, "f' from mother.  "fF" means "f" from father, "F" from mother.

**Comment by pixelzoom** [comment]
And the Pedigree graph displays father on the left, mother on the right, the same order as the genotype abbreviation.

**Comment by amanda-phet** [comment]
I found a wikipedia entry that confirms my suspicion. https://en.wikipedia.org/wiki/Zygosity

>Heterozygous
A diploid organism is heterozygous at a gene locus when its cells contain two different alleles (one wild-type allele and one mutant allele) of a gene.[3] The cell or organism is called a heterozygote specifically for the allele in question, and therefore, heterozygosity refers to a specific genotype. Heterozygous genotypes are represented by a capital letter (representing the dominant/wild-type allele) and a lowercase letter (representing the recessive/mutant allele), such as "Rr" or "Ss". Alternatively, a heterozygote for gene "R" is assumed to be "Rr". **The capital letter is usually written first.**

**Comment by pixelzoom** [comment]
I've seen both conventions used. What you've cited is typically used in Punnett's Square representation.  I chose what I thought was most useful for a Pedigree graph.  If you don't think there's any benefit to showing which allele was inherited from which parent, then I'll change it.

**Comment by pixelzoom** [comment]
So I'm going to put the dominant abbreviation first.  Keep in mind that these abbreviations are translatable, and "capital letter" may have no meaning in some locales.

**Comment by pixelzoom** [comment]
I also want to point out that `labPopulation=3Ff` is going to be different than `labPopulation=3fF`.     It denotes which allele was inherited from farther vs mother.  I don't see any reason to always put the capital letter first in this case.

**Comment by pixelzoom** [comment]
I also want to point out that `?labPopulation=3Ff` is going to be different than `?labPopulation=3fF`.  The allele order determines which allele is inherited from farther vs mother.  So if someone specifies `?labPopulation=3Ff,3fF`, then this change is going to result in 6 bunnies that appear at 'Ff' in the Pedigree graph, not 3 'Ff' and 3 'fF'.

**Comment by pixelzoom** [comment]
From the Wikipedia article that @amanda-phet cited above:

<img width="314" alt="screenshot_390" src="https://user-images.githubusercontent.com/3046552/84442513-022f0b80-abfb-11ea-91ed-7bda21f6371b.png">

This way of writing the genotype shows the correlation to the parent that the allele was inherited from.  This is the convention I was using for the Pedigree graph -- the left allele was inherited from the parent on the left (father), the right allele was inherited from the parent on the right (mother).

**Comment by pixelzoom** [comment]
Below is the patch needed to make the requested change.  I'm going to hold off on this until @amanda-phet confirms that we really want to do this.  https://github.com/phetsims/natural-selection/issues/104#issuecomment-642941929 and https://github.com/phetsims/natural-selection/issues/104#issuecomment-642945208 summarize why I'm not in agreement about this change.

<details>
<summary>Patch</summary>

```diff
Index: js/common/model/GenePair.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/model/GenePair.js	(revision 7d728f49608e945200e3d11327076be7bba398e1)
+++ js/common/model/GenePair.js	(date 1591911625279)
@@ -170,8 +170,14 @@
     let s = '';
     const dominantAllele = this.gene.dominantAlleleProperty.value;
     if ( dominantAllele ) {
-      s = ( this.fatherAllele === dominantAllele ) ? dominantAbbreviation : recessiveAbbreviation;
-      s += ( this.motherAllele === dominantAllele ) ? dominantAbbreviation : recessiveAbbreviation;
+      if ( this.fatherAllele === dominantAllele ) {
+        s = ( this.fatherAllele === dominantAllele ) ? dominantAbbreviation : recessiveAbbreviation;
+        s += ( this.motherAllele === dominantAllele ) ? dominantAbbreviation : recessiveAbbreviation;
+      }
+      else {
+        s = ( this.motherAllele === dominantAllele ) ? dominantAbbreviation : recessiveAbbreviation;
+        s += ( this.fatherAllele === dominantAllele ) ? dominantAbbreviation : recessiveAbbreviation;
+      }
     }
     return s;
   }
```

</details>

**Comment by amanda-phet** [comment]
Happy to discuss this with Megan. I completely understand why the order matters if you want to keep track of from whom the bunny inherits their alleles.

**Comment by amanda-phet** [comment]
6/15/20: not a problem to keep these as they are.
