### ISSUE TITLE
"father" and "mother" terminology in PhET-iO API

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#105]
Bunnies in this sim are sexless, and any bunny can mate with any other bunny. But as in the Java version, the code currently refers to the parents as "father" and "mother".   That terminology wasn't a problem in the Java version because it was not publicly visible. But in the HTML5 version, "father" and "mother" are appearing in the PhET-iO API, in 2 places:

* Each `Bunny` element has a `father` and `mother`
* Each `GenePair` element has a `fatherAllele` and `motherAllele`

Questions:
* Is this a problem, or is it OK to show "father" and "mother" in the PhET-iO API?
* If it's a problem, what new terms should we use? "parent1" and "parent2"?

**Comment by pixelzoom** [comment]
As couple of other considerations....

* If we don't think this is a problem, it's going to be much easier to just leave it "as is".  There's a ton of code that I'll need to touch. And "father" and "mother" is much clearer in the code than "parent1" and "parent2".

* If clients need to create activities that refer to parents, will they want to use "father" and "mother", or something else?  Do we want them use those terms, or do we care?

**Comment by amanda-phet** [comment]
I don't really care about the terminology here. Father and Mother is fine, IMO, even if the bunnies don't have a sex. (And nothing wrong with two fathers, haha). It is clear enough to me as it is. Happy to discuss with the team, especially @kathy-phet since she understand client needs more than I do.

**Comment by pixelzoom** [comment]
@kathy-phet thoughts?

**Comment by pixelzoom** [comment]
#97 and #98 resulted in a lot more use of "father" and "mother" in the code. So I'm really hoping that we don't need to change this.   There are now 100+ occurrences in code that would need to be changed, and the code will become much less clear and more prone to error (it's easier to accidentally swap parent1/parent2 than father/mother).

I recommend that we leave the code and PhET-iO API alone, and address this via documentation. Note in the PhET-iO Client Guide that bunnies are sexless, and  that "father" and "mother" are just a way of differentiating between 2 parents.

**Comment by amanda-phet** [comment]
We will leave this as-is. It does not seem problematic.
