### ISSUE TITLE
PhET-iO Client Guide

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#106]
@pixelzoom brought up an item we will likely want to include in the client guide in https://github.com/phetsims/natural-selection/issues/95#issuecomment-645519387. Let's use this issue for additional topics we want to include in the client guide.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/natural-selection/issues/95#issuecomment-645519387:
> We decided that "Start Over" means to go back to the point where we have the initial population, and that "Start Over" should not restore to a state that was saved after the generation clock started running. When a state like that has been saved, it will be odd that "Start Over" and "Reset All" take you to different states, and clients should consider hiding the "Start Over" button. But there's not a lot of value in saving a state after the generation clock has been started, and it's preferable to set up an experiment using the query parameters that configure the initial population. This should be documented in the PhET-iO Client Guide.

**Comment by amanda-phet** [comment]
From #56 we will want to provide information about getting a data stream from the graph.

>The data is stored in ObservableArrays, and Studio provides no ability to inspect the contents of an ObservableArray. So if you want to see data, you'll need to inspect the data stream in the State Wrapper. For example, here are the data points for "short teeth" after the bunnies have mated twice. For each point, x=generation, y=population.

**Comment by pixelzoom** [comment]
The bit above about ObservableArrays (previous comment) is true of all uses of ObservableArray.  Rather than duplicate it in every sim-specific client guide, should it be included in some general guide?  And does such a general guide exist?

**Comment by pixelzoom** [comment]
The client guide should include a description of the public query parameters, currently:

allelesVisible
introMutations
introPopulation
labMutations
labPopulation

Feel free to steal from [NaturalSelectionQueryParameters.js](https://github.com/phetsims/natural-selection/blob/master/js/common/NaturalSelectionQueryParameters.js).

**Comment by pixelzoom** [comment]
8/27/2020 design meeting:

Ideally there should be a client guide to do with the dev version to be delivered 10/1/2020.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/natural-selection/issues/208, the Client Guide was identified as "ideally to be included" for 10/1 client deliverable.  So labeling this issue as "blocks-sim-publication".

**Comment by amanda-phet** [comment]
note: the final PhET-iO client guide will need to include zoom query parameter for turning off zoom, since it will likely be included after the RC version (and thus in the final version).

**Comment by amanda-phet** [comment]
The primary client guide is finished: https://github.com/phetsims/phet-io-client-guides/blob/master/natural-selection/phet-io-guide.md 

I still need to create client-requests.md, and also figure out where to include the information about the start over button.

**Comment by pixelzoom** [comment]
9/10/2020 design meeting: @amanda-phet will remove the `supportsZoom` row from the NS Client Guide.

**Comment by amanda-phet** [comment]
Regarding @pixelzoom 's [comment](https://github.com/phetsims/natural-selection/issues/106#issuecomment-646807665) above, I've added the following to client-requests.md. 

However, we made this ID read-only, so the client can't actually hide the startOverButton. @pixelzoom any advice? 

## Reset the sim to initial preset sim conditions

The "Start Over" buttons means the user will go back to the point where we have the initial population (e.g. no customizations). "Start Over" will not restore to a state that was saved after the generation clock started running. 

The "Reset All" button will return the user to the initial preset sim conditions. 

If you do not want users to click the "Start Over" button, consuder hiding it using: 

* `naturalSelection.introScreen.view.playButtonGroup.startOverButton.visibleProperty`
* `naturalSelection.labScreen.view.playButtonGroup.startOverButton.visibleProperty`

**Comment by pixelzoom** [comment]
Re:
> If you do not want users to click the "Start Over" button, consuder hiding it using: ...

I think we should omit that part. We don't want them touch this button, it's not something they asked for, and you've already clarified the difference between "Reset All" and "Start Over".

**Comment by pixelzoom** [comment]
Re this section:

> Select which mutations are visible in the "Add Mutations" panel

It depends on what this goal is. 

If they want to add/remove a gene from this screen, they should use the Properties that show/hide all UI components related to a gene:

```
naturalSelection.introScreen.view.genes.earsVisibleProperty
naturalSelection.introScreen.view.genes.furVisibleProperty
naturalSelection.introScreen.view.genes.teethVisibleProperty
```

If they want to temporarily show and hide certain things in the UI after configuring the screen using the above elements, then they could use the elements that you have listed in the Client Guide.  But I wonder if we really want them doing this. If not, then those `visibleProperty` elements should be read-only.  @amanda-phet let's discuss.

**Comment by amanda-phet** [comment]
@pixelzoom and I discussed some tweaks over zoom, so these documents are now complete! Closing.
