### ISSUE TITLE
migrate color utilities to scenery.Color

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#107]
[NaturalSelectionUtils.js](https://github.com/phetsims/natural-selection/blob/master/js/common/NaturalSelectionUtils.js) contains 4 utility functions that are candidates for migration to scenery.Color:

* `getLuminance`
* `toGrayscale`
* `isDarkColor`
* `isLightColor`

@jonathanolson to you have any objection to me moving these to static methods of scenery.Color?

**Comment by pixelzoom** [comment]
By the way... In Natural Selection, these functions are used to decide what color text (black or white) to use on a specific background color.

**Comment by jonathanolson** [comment]
No objection, looks good.

**Comment by pixelzoom** [comment]
Migration completed. Closing.
