### ISSUE TITLE
Population graph not resetting

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#109]
Found while reviewing https://github.com/phetsims/natural-selection/issues/101

Reset-all doesn't reset the population graph properly. The sim is reset but the graph still shows the total population from the previous iteration (and others if you check them). 

Then when the sim starts running, you don't see the graph moving along with time, you only see jumps at the generations.

**Comment by amanda-phet** [comment]
Seen on https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.58/phet/natural-selection_en_phet.html, running Chrome on Mac OS 10.14.

**Comment by pixelzoom** [comment]
Fixed in master, please verify. If everything looks OK, please close this issue.

**Comment by amanda-phet** [comment]
Looks good.

**Comment by pixelzoom** [comment]
Reopening.  This aspect of the bug is not fixed:

> Then when the sim starts running, you don't see the graph moving along with time, you only see jumps at the generations.

**Comment by pixelzoom** [comment]
This was a very subtle bug, fixed in the above commit.  Thanks for finding this!  @amanda-phet please verify in master.

**Comment by amanda-phet** [comment]
Looks good now!
