### ISSUE TITLE
delete unused icons from icon-artwork.ai

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#11]
Re icon-artwork.ai, @amanda-phet and I had this Slack conversation:

Chris Malley 2:00 PM
where would I be using these?

<img width="447" alt="screenshot_1682" src="https://user-images.githubusercontent.com/3046552/68514021-cc2b4280-0239-11ea-9a6a-0fb146b79c7d.png">

Amanda McGarry 2:01 PM
I don’t think we’ll be using the brown version of those

Chris Malley 2:01 PM
ok, those were the ones that confused me.

Amanda McGarry 2:01 PM
ah, yes that is confusing. I shouldn’t have included those in the file

Chris Malley 2:02 PM
should I delete them from icon-artwork.ai?

Amanda McGarry 2:02 PM
yes, please

**Comment by pixelzoom** [comment]
My knowledge of Illustrator is limited. I tried to delete these and could't figure out how to delete both the artwork and their artboards.   @amanda-phet would you mind doing this?  And please mention this issue in the commit message.

**Comment by amanda-phet** [comment]
No problem. I also organized them a bit better in the new version.

**Comment by pixelzoom** [comment]
Thanks!
