### ISSUE TITLE
Change when deaths occur

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#110]
During the 6/25/20 design meeting we discussed how deaths would occur, and we found many reasons for keeping the deaths at a single point (rather than continuously happening). However we'd like to change it to happen in the middle of the "death cycle." So, for food, if the cycle is from 2:00-6:00, we'd want deaths to occur at 4:00. If the wolf cycle is from 6:00-10:00, we'd like deaths to occur at 8:00.

**Comment by pixelzoom** [comment]
I discussed this issue with @amanda-phet on Zoom.  We are also going to leave behavior related to how wolves and bunnies move "as is".  That is, wolves will not try to move towards specific bunnies.  And bunnies will not try to cluster around food.  That behavior is (at best) subtle in the Java version, and not worth the expense/complexity.

**Comment by pixelzoom** [comment]
Ready for review in master and [1.0.0-dev.59](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.59/phet/natural-selection_en_phet.html).

**Comment by amanda-phet** [comment]
This is looking good to me, and the graph looks great because of it. Thanks!
