### ISSUE TITLE
dash appears to move along plots for mutant alleles

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#111]
Related to #101.

When the Population graph starts to scroll, there's a distracting visual effect for the mutant (dashed) plots.  The line dash appears to move along the line.  This is because the line dash remains stationary, while the line moves to the left, as it scrolls with the graph.

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson on Slack.  Option `lineDashOffset` should be the means of resolving this. As the graph scrolls, adjust `lineDashOffset` to shift the dash pattern, making it look like it's scrolling with the plot.

**Comment by pixelzoom** [comment]
`lineDashOffset` worked great, and this is now behaving as desired.  @amanda-phet please review in master.  If it looks OK, close this issue.

**Comment by amanda-phet** [comment]
It is working as desired. Thanks for finding a solution!
