### ISSUE TITLE
handle enable/disable of environmental factors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#115]
Handle food and wolves correctly when they are enabled/disabled during their slice of the generation clock.

**Comment by pixelzoom** [comment]
Environmental factors are shown as slices of the generation clock, but are applied at single points in time.

Food slice is 2:00-6:00, applied at 4:00.
Wolves slice is 6:00-10:00, applied at 8:00.

What should happen when an environmental factor is enabled during its slice, but after the time that it's applied?  For example, what happens if wolves are enabled at 9:00?  Do they not appear? Do they appear, but not eat any bunnies? Do they appear and eat bunnies immediately?  And does food behave the same as wolves?

**Comment by pixelzoom** [comment]
7/7/2020 discussed with @amanda-phet via Zoom.

Food: If one of the food checkboxes is checked after 4:00, those factors won't be applied until the next clock cycle.

Wolves: If the checkbox is checked after 8:00, no wolves are created until the next clock cycle.  Otherwise, wolves are created when the checkbox is checked, disposed when the checkbox is unchecked.

**Comment by pixelzoom** [comment]
Ready for review in master or [1.0.0-dev.64](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.64/phet/natural-selection_en_phet.html).

One change to what we discussed in https://github.com/phetsims/natural-selection/issues/115#issuecomment-654990423:
> If the checkbox is checked after 8:00, no wolves are created until the next clock cycle. ...

Clicking a checkbox and sometimes seeing wolves appear, sometimes not, felt very odd/wrong. It was also difficult/messy to implement.  So the sim currently creates wolves if the checkbox is checked anytime during the clock slice.  If it's after 8:00, the wolves will just run around and won't eat any bunnies until the next clock cycle.

@amanda-phet please review.

**Comment by amanda-phet** [comment]
That looks fine to me. The easier thing to implement is usually better for code and often means a more intuitive user experience! I didn't find it odd for the wolves to come out and eat bunnies right away (if I added them right at 8:00), nor did it seem odd to see them come out and not eat bunnies (at 9:00) because it all happened so fast.
