### ISSUE TITLE
procedure to put the population in a stable state

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#119]
Pulling this issue out of https://github.com/phetsims/natural-selection/issues/46#issuecomment-654993065 and https://github.com/phetsims/natural-selection/issues/112#issuecomment-655200080, where it's needed to test memory consumption.

@amanda-phet will describe a procedure to put the population in a stable state. 

#86 (tune the environmental factors model) needs to be done first.

**Comment by amanda-phet** [comment]
1. Add a mate
2. At the start of generation 3, check "Limited Food" 

This is stabilizing for me until generation 17 (when the sim crashes). Hopefully this helps you test memory consumption once #127 is fixed. (If that is indeed addressing #120 )

**Comment by pixelzoom** [comment]
Thanks for the stabilization procedure.  And I believe the crash is fixed, see #127.

Closing.
