### ISSUE TITLE
keys for allele abbreviations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#12]
From the design doc:

> Alleles will be translatable, but many locales will choose to leave them as-is.

This refers to the allele abbreviations, which are as follows in English:

* F = fur dominant
* f = fur recessive
* E = ears dominant
* e = ears recessive
* T = teeth dominant
* t = teeth recessive

As I was deciding on good keys for these strings in natural-selection-strings_en.json, I ran into some interested questions. 

First, I considered using keys that might be end up grouped together in Rosetta, and communicate some info to the translators, e.g.:

```
  "allele.fur.dominant": {
    "value": "F"
  },
  "allele.fur.recessive": {
    "value": "f"
  },
  "allele.ears.dominant": {
    "value": "E"
  },
  "allele.ears.recessive": {
    "value": "e"
  },
  "allele.teeth.dominant": {
    "value": "T"
  },
  "allele.teeth.recessive": {
    "value": "t"
  }
```

This was based on the assumption that Rosetta groups keys alphabetically, to which @jbphet replied on Slack:
> Nope.  I can't recall exactly how it determines the order, I think it might be by order of appearance in the HTML file, but I'd have to investigate if you need to know.

Then I decided that perhaps it's better to keep it simple. Don't try to communicate to translators through keys, don't try to group them, and use the chars as the keys.  If a translator wants to change 'F', they can find 'F'.  I.e.:

```
  "F": {
    "value": "F"
  },
  "f": {
    "value": "f"
  },
  "E": {
    "value": "E"
  },
  "e": {
    "value": "e"
  },
  "T": {
    "value": "T"
  },
  "t": {
    "value": "t"
  }
```

I asked @jbphet if Rosetta is case sensitive, and he replied on Slack:

> As for case sensitivity, the strings are in JSON files, and JSON is defined to be case sensitive, so my answer is, "I think so, but it's never been tested".
>
> I'd suggest that you log an issue to have us test this on Rosetta when you're getting close to publication, and I can figure out a test on ox-dev that could use a dev version of the sim and we could make sure that case sensitivity isn't a problem.

(EDIT: That issue is https://github.com/phetsims/rosetta/issues/216.)

Finally, @jbphet noted on Slack that the a11y team is working on something that might be useful here:
> The a11y folks have been designing a scheme to group together keys, and are adding some structure to the string files, but it's not there yet.  You might want to check in with them and see if you can leverage what they're planning if the time frame works out.

**Comment by pixelzoom** [comment]
For now, I'll going with single-char case-sensitive keys. 

https://github.com/phetsims/rosetta/issues/216 (does Rosetta handle case-sensitive string keys?) is a pre-requisite for this issue.

**Comment by zepumph** [comment]
>The a11y folks have been designing a scheme to group together keys, and are adding some structure to the string files, but it's not there yet. You might want to check in with them and see if you can leverage what they're planning if the time frame works out.

Yes currently supported in a branch called `a11ystring-plugin` is the ability to have nested string keys in the english JSON file. These then get "flattened out" on build to be just as they look in build sims currently, so nothing needs to change with how rosetta handles them. 

This is currently working on the same named branch in friction. See 
https://github.com/phetsims/friction/blob/a11ystring-plugin/friction-strings_en.json#L26

This work was implemented to support a11y strings inside string json files. The timeline for merging this with master is based on @jbphet's availability to add code to rosetta that ignores a11y strings. Technically we could merge it to master today, and just not move a11y strings over until @jbphet is ready. 

To apply this more towards you case, would you want to do something like this?

```json
  "genes": {
    "F": {
      "value": "F"
    },
    "f": {
      "value": "f"
    }
  },
```

**Comment by pixelzoom** [comment]
> These then get "flattened out" on build to be just as they look in build sims currently, so nothing needs to change with how rosetta handles them.

I can see how this is useful for grouping related things within the JSON.  But if the structure is flattened, how does this help with keeping related things together in the Rosetta UI? 
JSON is (by definition) an _unordered_ set of key/value pairs, https://www.oracle.com/technical-resources/articles/java/json.html.

**Comment by pixelzoom** [comment]
> ... But if the structure is flattened, how does this help with keeping related things together in the Rosetta UI? ...

Discussed with @zepumph on Slack.  It sounds like Rosetta is currently relying on order of keys in the JSON, and that just happens to work.  @jbphet can you verify?   

If some guaranteed order is important, it would be preferable to get all keys from the JSON, sort them alphabetically, then present them alphabetically in Rosetta.  That would guarantee that (e.g.) all keys of the form "alleles.*" or "a11y.*" would be grouped together.

**Comment by pixelzoom** [comment]
This turned out to be problematic:

```
  "F": {
    "value": "F"
  },
  "f": {
    "value": "f"
  },
```

The `require` statements would be:

```js
const FString = require( 'string!NATURAL_SELECTION/F' );
const fString = require( 'string!NATURAL_SELECTION/F' );
```

... and `FString` violates naming conventions.

So the new plan is:

```
  "furDominantAbbreviation": {
    "value": "F"
  },
  "furRecessiveAbbreviation": {
    "value": "f"
  },
  "earsDominantAbbreviation": {
    "value": "E"
  },
  "earsRecessiveAbbreviation": {
    "value": "e"
  },
  "teethDominantAbbreviation": {
    "value": "T"
  },
  "teethRecessiveAbbreviation": {
    "value": "t"
  },
```

So this is no longer dependent on phetsims/rosetta#216.
