### ISSUE TITLE
Error once we hit generation 17, likely related to pruning

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#120]
I was holding down fast-forward for many generations and then all of a sudden at the start of the generation the bunnies didn't mate, causing the population to die. 

Clicking reset-all made the sim further bug out, as the sim was only partially reset, the button still looks depressed and other things look strange. 

I can try to find steps to reproduce, but wanted to document this as soon as I could.

![image](https://user-images.githubusercontent.com/7852916/87081935-64bdfc00-c1e7-11ea-8118-f7032c69cd5b.png)

**Comment by pixelzoom** [comment]
@amanda-phet What version were you running, on what browser? Anything in the browser console?

**Comment by pixelzoom** [comment]
>  What version were you running, on what browser?

1.0.0-dev.66, Chrome + macOS 10.15

**Comment by amanda-phet** [comment]
I held down the fast-forward button for maybe 6 generations in a row, then at generation 17 you can see the bunnies didn't mate. 
![image](https://user-images.githubusercontent.com/7852916/87100465-bbd4c880-c209-11ea-9bfa-f40bd92df92f.png)

I'm not sure if you can read the console, but hopefully something here is helpful. If you want me to do this on zoom with you I'm happy to do that.

**Comment by pixelzoom** [comment]
Could you describe how you got the sim to run for 17 generations, and give this a try with master?  Built versions get mangled, so the console output isn't difficult to interpret.  But I'm guessing that this bug is related to pruning of bunnies after 15 generations.

**Comment by amanda-phet** [comment]
You're right, I'm sure this has to do with pruning. It keeps happening right at generation 17. I'm trying to test #98 and #86, which requires me getting the bunnies in a steady state, so I keep bumping into this bug.

Running https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.66/phet/natural-selection_en_phet.html?wolvesPercentToKill=.35,.4&wolvesEnvironmentMultiplier=2.3&limitedFoodPercentToKill=.6,.7&toughFoodPercentToKill=.4,.68&shortTeethMultiplier=1.4&limitedFoodMultiplier=1.02&ae (sorry, haven't gone to master yet), add the teeth mutation, run for a few generations, then add tough food, and the population should stabilize. I'm sure if you tweak it to make sure the bunnies don't all take over or die you'll get to generation 17 some how.

**Comment by amanda-phet** [comment]
So I'm running http://phettest.colorado.edu/natural-selection/natural-selection_en.html?ea&brand=phet&wolvesPercentToKill=.35,.4&wolvesEnvironmentMultiplier=2.3&limitedFoodPercentToKill=.6,.7&toughFoodPercentToKill=.4,.7&shortTeethMultiplier=1.4&limitedFoodMultiplier=1.02&ae&minBunniesForFood=4 and right at the start of generation 17 I get a lot of console information. I think it will work best if you run this and check out the console output because there is a lot of stuff that I can't really copy and paste here. 

To reproduce, run using the parameters above, run a few generations and then use limited food to maintain a stable population. You can check and uncheck as needed to be sure you keep them alive for 17 generations. 

There are lots of assertions failed that look just like this: 

Assertion failed: reentry detected, value=172.7019999999991, oldValue=172.6859999999991

assert.js:22 Uncaught Error: Assertion failed: reentry detected, value=172.7019999999991, oldValue=172.6859999999991
    at window.assertions.assertFunction (assert.js:22)
    at NumberProperty._notifyListeners (Property.js:270)
    at NumberProperty.set (Property.js:171)
    at NumberProperty.set value [as value] (Property.js:343)
    at GenerationClock.stepTime (GenerationClock.js:129)
    at GenerationClock.step (GenerationClock.js:109)
    at LabModel.stepOnce (NaturalSelectionModel.js:272)
    at LabModel.step (NaturalSelectionModel.js:258)
    at Sim.js:292
    at Action.execute (Action.js:225)

![image](https://user-images.githubusercontent.com/7852916/87106608-1296ce00-c21b-11ea-9d4a-53e4369371d5.png)

**Comment by pixelzoom** [comment]
Moving this to https://github.com/phetsims/natural-selection/issues/127.
