### ISSUE TITLE
method of handling Reset All

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#121]
As noted at 7/9/2020 dev meeting... Reminder that https://github.com/phetsims/phet-io/issues/1678#issuecomment-655766250 is affecting Reset All and Start Over.

**Comment by samreid** [comment]
I reverted the behavior in https://github.com/phetsims/phet-io/issues/1678 so axon Property reset() doesn't try to load customized state any more.  This issue can likely be closed after Natural Selection tests to have the correct behavior.  @pixelzoom let me know if you test this before I do.

**Comment by samreid** [comment]
I'll defer to @pixelzoom for the testing since he is more familiar with how "start over" can be triggered and how it is expected to behave.  Another test to run for this issue is creating a customized sim in Studio and make sure it has the correct behavior for "reset" and "start over".

**Comment by pixelzoom** [comment]
Start Over and Reset All are behaving as expected. Closing.
