### ISSUE TITLE
animation slows down with large numbers of bunnies & wolves

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#122]
Reported to me verbally by @amanda-phet, she noticed this on her MacBook Pro.

This will be addressed by the scenery work that @jonathanolson is doing for sprites (#128) and conversion to time-based animation (#123).

**Comment by pixelzoom** [comment]
I started to tune Bunny.REST_STEPS_RANGE, and realized that I can't really come up with a value that I think looks good on all platforms.  Animation is currently based on clock steps, not time, so I'm going to investigate changing that in #123.

**Comment by pixelzoom** [comment]
Deferred for #128 (high-performance sprites).

**Comment by pixelzoom** [comment]
The time that bunnies rest is going to be tuned in #129, not in this issue.

**Comment by pixelzoom** [comment]
With the new sprites implementation (#128) and the conversion to time-based animation (#123), performance should be consistent across platforms and should not slow down with the max number of bunnies.

@amanda-phet please verify with your machine.  Use [1.0.0-dev.72](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.72/phet/natural-selection_en_phet.html), so that you're testing with a built version.  If it looks OK, please close.

**Comment by amanda-phet** [comment]
It's all looking great!
