### ISSUE TITLE
base animation on time instead of "steps"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#123]
As in the Java version, animation of bunnies and wolves is currently based on number of clock steps, not on time.  Since the time between clock steps will vary widely across platforms, this makes it impossible to "tune" animation.   

For example, in #122 we decided to increase the amount of time that bunnies spend resting.  But because that's based on number of clock steps and not a time value, it's impossible for me to pick a value that I'm confident will look good on all platforms.

So after discussing with @amanda-phet, I'm going to investigate changing animation of bunnies and wolves to be time-based. And ideally, we do not want them to move faster when the fast-forward button is pressed -- which I believe can be accomplished by only scaling the dt value that is provide to the generation clock.

**Comment by pixelzoom** [comment]
Animation is now time-based, and computed based on each dt (time step) passed to the model.   This is consistent with other sims, will provide more consistent animation across platforms, and allow us to tune the animation based on how long we want something to take (e.g. how long bunnies rest, how long it takes to complete a hop).

This was a relative major change. So @amanda-phet, in addition to tuning the animation in #129, please verify that everything looks OK with the motion of bunnies and wolves.

**Comment by amanda-phet** [comment]
As far as this changes goes I think everything looks good. I stabilized the population at a pretty large size (~480 bunnies at the start of each generation) and the animation speeds all looks really consistent.
