### ISSUE TITLE
reimplement environment view as high-performance sprites

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#128]
In #60 and #122, we identified performance problems with trying to use scenery Nodes to create and animate large numbers of bunnies and wolves. 

In 7/8/2020 design meeting (see https://github.com/phetsims/natural-selection/issues/60#issuecomment-656320887) we asked @jonathanolson about this recommendation that he made:
> Rather than implement something sim-specific based on Canvas or WebGL, @jonathanolson recommends investing in a general solution for rendering high-performance sprites in scenery.

@jonathanolson has some of this implemented already. @kathy-phet asked him to proceed, and assign hours to Natural Selection.

Using this approach means that:

* The view for bunny, wolves, and shrubs cannot be instrumented. (I removed instrumentation in #124.)
* I'll need to reimplement the part of the view that draws bunnies, wolves, and shrubs. They will become sprites.
* I'll need to reimplement how bunnies are selected, and how the selection rectangle is handled. It will become another sprite.

Team was OK all of the above.

The corresponding scenery issue is https://github.com/phetsims/scenery/issues/990 (Add high-performance sprite option).

**Comment by pixelzoom** [comment]
@jonathanolson and I reviewed progress and API questions on Zoom today.  This is looking very promising.

**Comment by pixelzoom** [comment]
The corresponding scenery issue is https://github.com/phetsims/scenery/issues/990 (Add high-performance sprite option).

**Comment by pixelzoom** [comment]
I made good progress on this today.  But there are many issues to resolve, noted by "TODO #128" comments in the code.

**Comment by pixelzoom** [comment]
The sim is now fully converted to using scenery high-performance sprites.  

Performance: I'll be doing more thorough performance tests over in #60 and #122.  But with `?showTimeToMate` on my 2019 MacBook Pro + macOS 10.15.5 + Chrome 83,  the time to create 952 bunnies at generation 6 has dropped from 326ms, and animation performance is smooth/consistent for all population sizes.  This is a very exciting improvement.

PhET-iO: The view now has a single PhET-iO element named `sprites` that renders all sprites. And it has `bunnyPressListener`, which handles selection of bunnies. In Studio, see for example `naturalSelection.labScreen.view.environmentNode.sprites`:

<img width="263" alt="screenshot_430" src="https://user-images.githubusercontent.com/3046552/87627087-3199d200-c6eb-11ea-8be2-a6c058efdc0f.png">
 
@amanda-phet please test drive in [1.0.0-dev.70](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.70/phet/natural-selection_en_phet.html).  Take a very close look, because all of the rendering and interaction in the "environment" is an entirely new implementation.

**Comment by kathy-phet** [comment]
Great, Chris! Can you clarify what the new number is? dropped from 326ms ... to what? Thanks.

**Comment by pixelzoom** [comment]
Sorry, that somehow got dropped from https://github.com/phetsims/natural-selection/issues/128#issuecomment-659155464.  I've edited to include the information:

> the time to create 952 bunnies at generation 6 has dropped from 326ms to 130ms

**Comment by kathy-phet** [comment]
My only comment is that "sprites" is a very technical term. Is it possible to have different names sim to sim for a particular bundle of sprites?

**Comment by pixelzoom** [comment]
We can call it anything that we want.  But the PhET-iO convention is to name things to correspond to their JavaScript class names. The scenery base class is `Sprites`, the natural-selection subclass is `NaturalSelectionSprites`.  Hence the current name "sprites".    Here's the code:

```js
    // High-performance sprites, for rendering bunnies, wolves, and food.
    const sprites = new NaturalSelectionSprites( model.bunnyCollection, model.wolfCollection, model.food,
      model.isPlayingProperty, bounds, {
        tandem: options.tandem.createTandem( 'sprites' )
      } );
``

And the phetioDocumentation is "bunnies, wolves, and shrubs that appear in the environment".

**Comment by pixelzoom** [comment]
We can call it anything that we want.  But the PhET-iO convention is to name things to correspond to their JavaScript class names. The scenery base class is `Sprites`, the natural-selection subclass is `NaturalSelectionSprites`.  Hence the current name "sprites".    Here's the code:

```js
    // High-performance sprites, for rendering bunnies, wolves, and food.
    const sprites = new NaturalSelectionSprites( model.bunnyCollection, model.wolfCollection, model.food,
      model.isPlayingProperty, bounds, {
        tandem: options.tandem.createTandem( 'sprites' )
      } );
```

And the phetioDocumentation is "bunnies, wolves, and shrubs that appear in the environment".

<img width="529" alt="screenshot_431" src="https://user-images.githubusercontent.com/3046552/87629080-7f183e00-c6ef-11ea-8147-2962a3cf46bf.png">

Unless there's a reason to violate PhET-iO naming conventions, my recommendation is to leave it named "sprites", and don't feature it.

**Comment by pixelzoom** [comment]
And yes, the name can (and will) vary from sim to sim.  There is nothing in common code that is naming it "sprites".

**Comment by amanda-phet** [comment]
I don't have a problem with them being called sprites, myself. I am still wrapping my head around PhET-iO in general, so excuse me if this is obvious. `naturalSelection.labScreen.view.environmentNode.sprites.pickableProperty` is read-only, as are the other elements under `sprites`. Doesn't that mean an instructional designer can't really do anything with these properties? If I try to put myself in the shoes of an instructional designer, I don't think I will need to bother with any of this stuff. If I care about bunny information I would look in the model and `bunnyGroup`. 

So, my thinking is that all of this is fine because I just accept Studio as it is. I don't see any concerns with how the tree looks and I think when we brainstormed how an instructional designer might want to customize this sim, this still achieves those potential goals.

**Comment by amanda-phet** [comment]
@kathy-phet since you are really the PhET-iO designer, can you confirm that this all looks ok? If you want to change the name from "sprites" then maybe this needs to be discussed at PhET-iO or dev meeting.

**Comment by kathy-phet** [comment]
I reviewed this and it all looks good to me. Let's leave the name as "sprites". I like the definition. And yes, no reason to feature any of it, so it won't get distracting for the instructional designer. Thanks, Chris! 

Without ?ea and running in brand=phet, I got 202ms and 123ms in two trials! Nice. With ?ea it increases a lot.

**Comment by kathy-phet** [comment]
Feel free to close.

**Comment by pixelzoom** [comment]
👍 Closing.
