### ISSUE TITLE
tune animation query parameters

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#129]
Over in https://github.com/phetsims/natural-selection/issues/123, animation was changed to be time-based.  This will provide more consistent behavior on all platforms, and lets us specify motion in terms of time.

There are 3 new query parameters that can be tuned:

* `bunnyRestTime` is a range that determines how long a bunny rests between hops, in seconds. The default is `2,4`, and a new value is randomly chosen each time a bunny rests.

* `bunnyHopTime` is a range that determines how long it takes for a bunny to complete 1 hop. The default is `0.25,0.5`, and a new value is randomly chosen each time a bunny hops.

* `wolfSpeed` is a range that determines how fast the wolves move, in pixels/second. The default is `125,200`, and a new value is chosen for each wolf at the start of the "wolves" slice of the generation clock.

@amanda-phet please review and let me know if you'd like to change any of the default values.

**Comment by amanda-phet** [comment]
@ariel-phet can you also review, since it was your suggestion to change the animation speed for the bunnies?

**Comment by amanda-phet** [comment]
I like all of the speeds as they are right now, but would also be ok with `bunnyRestTime=3,5` if @ariel-phet wants those rest times to be longer. 

I thought I wanted the wolves to be slower but after playing for a bit they seemed too slow even at `120,180` so I'd like to leave those as-is.

**Comment by pixelzoom** [comment]
@ariel-phet you can review in master or [1.0.0-dev.69](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.69/phet/natural-selection_en_phet.html).

**Comment by ariel-phet** [comment]
I would probably opt for the slightly longer `bunnyRestTime=3,5` but the defaults look good.

Perhaps @oliver-phet could cast a deciding vote, I am probably pretty happy either way.

**Comment by oliver-phet** [comment]
I just tried `2,4`, `3,5`, and `3,7` and preferred longer, wider ranges especially around generation 4/5 on Intro. The smaller ranges (`2,4`, `3,5`) lead to many of the newest generation bunnies jumping at the same time and it just looks chaotic and unnecessary with a lot of bunnies.

I wonder if it would make sense to just scale the `bunnyRestTime` as the number of bunnies increases. Something like:

- < 10 bunnies `bunnyRestTime=2,4`
- 10 - 250 bunnies `bunnyRestTime=3,7`
- 250+ bunnies `bunnyRestTime=5,9`

**Comment by pixelzoom** [comment]
I've had the same thought as @oliver-phet - that I want to see less hopping as the population increases.  But varying the rest range is going to increase complexity.  Bunny rest time is set by each individual bunny, and bunnies don't know about the population size.  So we'll need a model-global `restRangeProperty` that's derived from the population size, and `restRangeProperty` will need to be passed to every Bunny.  The single `bunnyRestTime` query parameter may need to become 3 query parameters, to tune the 3 ranges that @oliver-phet noted above.   I'll be happy to do this, but it's going to take 2-3 hours.  

@amanda-phet let me know how you want me to proceed.

**Comment by amanda-phet** [comment]
>I wonder if it would make sense to just scale the bunnyRestTime as the number of bunnies increases.

That is exactly what @ariel-phet had suggested in the design meeting, but it seemed like it wasn't worth the added complexity. 

If we stick with the current design, I would prefer keeping the longest rest time smaller, so `bunnyRestTime=2,6` is looking ok to me. If the initial bunny (or 2 bunnies) has a long rest time, it looks really strange to me. I want that first bunny hopping around! But I agree that having a wider range helps when there are more bunnies. 

I also think nudging the speed down a little to `bunnyHopTime=0.2,0.45` helps to balance the long rest time. 

I'm not sure if it's worth it to make major changes to this or not.

**Comment by pixelzoom** [comment]
We all seem to agree that something like what @oliver-phet proposed in https://github.com/phetsims/natural-selection/issues/129#issuecomment-658820527 would be nice.  @amanda-phet and I will discuss to decide whether to proceed with this, or whether to leave as is.

**Comment by pixelzoom** [comment]
Because there's a performance benefit to having large numbers of bunnies rest longer, we decided to proceed with @oliver-phet 's proposal.

**Comment by pixelzoom** [comment]
This took me 1 hour to implement in the above commit.   The `bunnyRestTime` query parameter has been removed, and the ranges and population sizes are as @oliver-phet specified in https://github.com/phetsims/natural-selection/issues/129#issuecomment-658820527:

* < 10 = [2,4]
* 10-250 = [3,7]
* 250+ = [5,9]

@amanda-phet please review in master or [1.0.0-dev.71](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.71/phet/natural-selection_en_phet.html).

**Comment by amanda-phet** [comment]
I think it looks great! Maybe next week we could tweak it over zoom... I'm tempted to make the ranges something like this so that those first bunnies do more hopping: 

< 10 = [1,3]
10-250 = [2,7]
250+ = [5,9]

**Comment by pixelzoom** [comment]
@amanda-phet and I tweaked the rest times via Zoom. We ended up with:

< 10 = [1,3]
10-250 = [2,7]
250+ = [6,10]

Closing.
