### ISSUE TITLE
requirements for Proportion "Values" checkbox

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#13]
Proportion view, from the design doc:

<img width="662" alt="screenshot_1695" src="https://user-images.githubusercontent.com/3046552/68791318-49720100-0606-11ea-81f3-c123264898c0.png">

The behavior of the "Values" checkbox is not specified, and there are no mockups showing the "Values" checkbox unchecked.

On Slack, AM said that it hides the bunny counts, but still displays percentage values, so someone could hide the counts and focus only on the percentages. But if you don’t know how the population has changed (increased vs decreased), how do you interpret the significance of proportions? I'm questioning the usefulness of this feature

**Comment by pixelzoom** [comment]
11/21/19 design meeting:

"Values" checkbox will show/hide percentage values. Unchecked by default.

**Comment by pixelzoom** [comment]
I've implemented what was decided at this afternoon's design meeting - "Values" checkbox is unselected by default, and hides the percentage values.  You can test drive in [1.0.0-dev.10](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.10/phet/natural-selection_en_phet.html).  Screenshots of unchecked and checked below.

I'm not wild about having this unchecked by default, because the vertical spacing doesn't look great.  But I guess I could live with it. 

@amanda-phet your opinion?

<img width="822" alt="screenshot_1701" src="https://user-images.githubusercontent.com/3046552/69385972-5c2bac00-0c7e-11ea-8ab0-b3a80d8b2145.png">
<img width="818" alt="screenshot_1702" src="https://user-images.githubusercontent.com/3046552/69385975-5d5cd900-0c7e-11ea-83e6-908e9aedf9fc.png">

**Comment by amanda-phet** [comment]
Let's leave it for now and wait until there is live data before we make a final decision.

**Comment by pixelzoom** [comment]
OK., I'll unassign for now, and we can revisit when the implementation is more fleshed out.

**Comment by pixelzoom** [comment]
As noted in #18, for small percentage values, the bars alone are problematic.  A small sliver of a bar is difficult to see. Here are examples for 99% + 1% and 1% + 99%:

<img width="136" alt="screenshot_1709" src="https://user-images.githubusercontent.com/3046552/69586849-16822280-0fa1-11ea-8756-f08b6136070d.png">
<img width="136" alt="screenshot_1718" src="https://user-images.githubusercontent.com/3046552/69586854-17b34f80-0fa1-11ea-8de2-0718e986eb2a.png">

Depending on how #18 its addressed, this may be a good reason to drop this feature and _not_ hide the percentage values.

**Comment by pixelzoom** [comment]
Two more thoughts about this feature:

(1) Rather than hiding the percentage values, perhaps it would be more useful to switch between percentages and numbers of bunnies.  

(2) It might be better to put this control in the panel with the bar graphs, so that the panel to the left is purely a legend.

**Comment by pixelzoom** [comment]
Make "Values" on by default, move to the bottom of the panel.

**Comment by pixelzoom** [comment]
Done, closing.
