### ISSUE TITLE
tune maxGenerations query parameter

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#130]
Over in https://github.com/phetsims/natural-selection/issues/46, we set a limit on how long the simulation will run.  It's controlled by query parameter `maxGenerations`, which currently has an arbitrary default of `1000`.    We need to determine, based on memory consumption, what a reasonable value is.

From https://github.com/phetsims/natural-selection/issues/119#issuecomment-657915594, to put the sim in a stable state:

> 1. Add a mate
> 2. At the start of generation 3, check "Limited Food"

Then I'll probably need to take Chrome heap snapshots as the generation number increases.

**Comment by pixelzoom** [comment]
Testing over in #112 (prune dead bunnies), memory consumption seems to be stable, no sign of memory leaks.  Memory footprint is largest when bunnies take over the world, and that's ~70 MB, very reasonable for a PhET sim.    Memory consumption is similar for both `brand=phet` and `brand=phet-io`.

The Population graph has a maximum of 3 points (Vector2) per generation.  So for maxGenerations=1000, that's 3000 Vector2 instances. That's very reasonable.

1,000 generations * 10 seconds/generation = 10,000 seconds = ~167 minutes before the user will encounter the generations limit.  So while we might be able to raise the generation limit, I don't see any reason to, and recommend leaving it at 10,000.  @amanda-phet your opinion?

**Comment by amanda-phet** [comment]
I don't see any reason to increase it beyond 1,000 generations. It can certainly happen faster if the user is holding down the fast-forward button, but even still, I don't think it is unreasonable for the sim to reach the limit we've set if they hold down that button for 40 minutes.

**Comment by pixelzoom** [comment]
Great, then we're done here. Closing!
