### ISSUE TITLE
CT:  Impossible set state from iterate

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#134]
Related to reimplementation using sprites in #128.

```
natural-selection : phet-io-state-fuzz : unbuilt
https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io-wrappers/state/?sim=natural-selection&phetioDebug&fuzz&wrapperContinuousTest=%7B%22test%22%3A%5B%22natural-selection%22%2C%22phet-io-state-fuzz%22%2C%22unbuilt%22%5D%2C%22snapshotName%22%3A%22snapshot-1594887375814%22%2C%22timestamp%22%3A1594896874619%7D
Uncaught Error: Assertion failed: Impossible set state from iterate:
naturalSelection.introScreen.model.bunnyCollection.selectedBunnyProperty
Error: Assertion failed: Impossible set state from iterate:
naturalSelection.introScreen.model.bunnyCollection.selectedBunnyProperty
at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/assert/js/assert.js:22:13)
at PhetioStateEngine.iterate (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io/js/PhetioStateEngine.js:340:19)
at PhetioStateEngine.setState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io/js/PhetioStateEngine.js:247:31)
at PhetioStateEngine.setFullState (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io/js/PhetioStateEngine.js:267:10)
at PhetioEngineIO.implementation (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io/js/PhetioEngineIO.js:221:43)
at PhetioCommandProcessor.processCommand (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io/js/phetioCommandProcessor.js:270:51)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io/js/phetioCommandProcessor.js:162:36
at Array.map (<anonymous>)
at PhetioCommandProcessor.processCommands (https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io/js/phetioCommandProcessor.js:160:30)
at https://bayes.colorado.edu/continuous-testing/ct-snapshots/1594887375814/phet-io/js/phetioCommandProcessor.js:99:16
id: Bayes Chrome
Snapshot from 7/16/2020, 2:16:15 AM
```

**Comment by zepumph** [comment]
@pixelzoom asked:

>Can someone from the PhET-iO team interpret what "Impossible set state from iterate" means in the context of the State Wrapper?  The context is https://github.com/phetsims/natural-selection/issues/134

`selectedBunnyProperty` is using `ReferenceIO` to (de)serialize its instance. This means that when trying to set its state, the state object holds a phetioID of a Bunny (most likely, just a guess). When trying to reserialize it, ReferenceIO will try to look up that phetioID in the phetioEngine and return the actual, downstream Bunny and return that instance. If it can't find that, it throws and error in the state engine, telling the state engine to try again on next pass (perhaps after that bunny is created). 

An impossible set state occurs after a couple thousand of loops in which nothing changes, and then it lists the phetioIDs that couldn't be set. 

Likely this is an issue with that exact bunny not being in the state, so it never gets restored. 

It also could potentially be two problems with PhetioGroup, one about indexing (though I don't think this is it), and the second about when newly created elements get notified. 

I won't be able to look into this until at least Wednesday, but let me know if you'd like me to!

**Comment by pixelzoom** [comment]
Slack:

Chris Malley  1:22 PM
thanks. does the state engine know the phetioID of the element that it can't find? if so, should it be included in the error message?

Michael Kauzmann  1:24 PM
Yes I understand and agree. I will commit a patch in which the list of phetioIDs is supplemeneted with printing all of the states of those elements, as the phetioID you are talking about should be in the selectedBunnyProperty's state. Is there an easy way to reproduce the case?

Chris Malley  1:27 PM
thanks. that would help identify which element's reference is missing.  i have not reproduced locally yet, and this may be a manifestation of other problems related to reimplementing the view using scenery Sprites.

**Comment by zepumph** [comment]
I haven't added that yet, assigning myself.

**Comment by pixelzoom** [comment]
After resolving a bunch of other issues with the new sprites implementation, this problem disappeared and hasn't reocurred since shortly after it was first reported.  So I'm going to close this issue.
