### ISSUE TITLE
publish a preview dev version for PhET-iO client

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#135]
Requested by @kathy-phet in 7/16/2020 phet-io meeting.

Sometime in the next week or two, provide the PhET-iO client with a preview dev version.  This version is for the instructional designers to see where things are at, so they can evaluate for scheduling. This will include brand=phet, and may or may not include brand=phet-io.  Wrap up issues #86 and #128 first.  This doesn't have to be bug-free, and PhET-iO API changes are still anticipated.

**Comment by pixelzoom** [comment]
@amanda-phet and I feel like the sim is now in a good place for publishing a preview. So...  

Here are links to the preview version:

* phet: https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.73/phet/natural-selection_en_phet.html
* phet-io: https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.73/phet-io/

Caveats:
* There are still open issues that may crash the sim.
* Performance of the PhET-iO version is not great on slower devices.
* Memory management hasn't been fully addressed, so the browser may run out of memory.
* The PhET-iO API may still change.

Assigning to @kathy-phet to deliver to the client.  I published both phet and phet-io brands, and you can decide which to deliver.  Please comment in this issue when the preview version has been delivered.

**Comment by kathy-phet** [comment]
I sent the client both versions with the caveats above, and noting that these are earlier and less tested than our normal "dev" versions.

**Comment by pixelzoom** [comment]
Nothing else to do for this issue, closing.
