### ISSUE TITLE
Selected bunny dies but selection rectangle remains

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#137]
Seen in dev.70. 

![image](https://user-images.githubusercontent.com/7852916/87719618-dd393580-c770-11ea-989a-40577f40378e.png)

I clicked on a bunny that died due to limited food, and the selection rectangle remains. It is good to see the pedigree, but I think at this point it doesn't make sense to still show a rectangle. I checked dev.69 to confirm that this is new behavior with dev.70. 

Ideally the rectangle disappears, but if viewing the Pedigree you are still viewing a selected bunny. Here is that behavior from dev.69. 
![image](https://user-images.githubusercontent.com/7852916/87719902-559ff680-c771-11ea-81ba-04ef65695cd0.png)

**Comment by pixelzoom** [comment]
Related to sprites implementation #128.

**Comment by pixelzoom** [comment]
This one should be a relatively easy fix.  I forgot that `selectedBunnyProperty` is not set to null when a bunny dies, the bunny remains selected and displayed in the Pedigree graph.   So I'll need to add a listener to the selected bunny's `diedEmitter`, and manage the listener when the selection changes or the bunny dies.

**Comment by pixelzoom** [comment]
This is a duplicate of #132.  Closing.
