### ISSUE TITLE
requirements for "Values Marker"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#14]
The Population graph has a "Values Marker", which displays the values for each plot at a position on the x (Generation) axis.  This feature is underspecified in the design doc, and we haven't made progress discussing it via comments in the design doc, so I'm creating this issue.

Here's the most recent mockup from the design doc, for context:

<img width="661" alt="screenshot_1696" src="https://user-images.githubusercontent.com/3046552/68796404-087eea00-0610-11ea-83e3-f012c142d2a1.png">

Notes in the design doc that have not been resolved, with my questions:

- [x] 8/7/2019 meeting notes: Keep option to swipe to previous generation- need to figure out how the picture updates (or doesn’t). Need to figure out if we want to also include. 
_@pixelzoom: What does "swipe to previous generation" mean? Are we doing this?_
**This is about the Proportion view, ignore.**

- [x] 8/14/2019 meeting notes: Do we want the values marker to snap to certain points? Maybe we can add little dots where those points are. 
_@pixelzoom: Are we doing this?_
**We are not doing this.**

- [x] 8/21/2019 meeting notes: What happens to the marker when we drag the graph? Does it stick on the generation, or stick on the graph? We like the idea of it sticking to the generation, and if it gets to the edge of the graph, at that point it sticks to the graph (in this case, on generation 7) 
_@pixelzoom: This the first reference I've seen to being able to "drag the graph". What does this mean? And how does it stick to (e.g.) generation 7 when that x-axis value is no longer visible?_
**Ignore this, there is no dragging of the graph. And marker will not stick to a value, it will stick to a screen location.**

- [x] 10/11/19 comment thread attached to "The values marker can go as far as the current line for generation 7".
CM: I'm not clear on this. Are you saying that the Values Marker can only be moved as far right as the rightmost generation shown on the graph? (which happens to be 7 in this mockup). Is this so that the values displayed on the marker stay inside the graph bounds?
AM: yes, we want the values inside the graph bounds. Upon reading your question, I realize this constraint limits the data the user can actually read. Could you have the flags flip to the other side of the marker?
CM:Yes, values ("flags") could move to the left or right side of the marker as space permits.
_@pixelzoom: Are we flipping which side of the marker values are displayed on at the left/right edges of the graph?_
**Marker will stick to a screen location, not an x-axis value.**

- [ ] 10/14/19 comment thread attached to "the side arrow", asking about what happens when the Value Marker's position goes off the graph.
CM: What happens to the Value Marker when pressing one of the arrows would move the marker's location off the graph? Same question for when the sim is playing, and the Value Marker's position would no longer be visible on the graph. Perhaps the Values Marker stays at a generation value until that value is no longer on the graph, and then stay stuck to the left/right of the graph if the generation value goes off-graph?
AM: the values marker sticks to that location (previous sentence in this paragraph). I would like to consider the possibility of having the marker be allowed to be anywhere on the graph, not constrained at the "generation 7" line, so if we can flip the flags then the marker can scan the entire graph.
CM: Let me try to clarify... If the marker is at "7", and pressing one of the arrow buttons causes "7" to go outside the visible bounds of the graph, what happens to the value marker? If it stays stuck to location "7" (as you've said), them it will not be visible and the user won't be able to use it (or drag it) until they make it visible again with the arrow buttons.
_@pixelzoom: What do we do when the graph x-axis scrolls (either as the sim runs, or the user presses one of the arrow buttons), and the x value that the Value Marker is on is no longer visible on the graph?_
**Marker will stick to a screen location, not an x-axis value.**

**Comment by pixelzoom** [comment]
Other questions:

- [ ] Which parts of the Values Marker are draggable? (Consider that all checkboxes may be unchecked.) Should it have a small drag handle on the x axis?

- [ ] The Values Marker shows y (Population) values.  Does it also need to show the x (Generation) value somewhere? If so, what are the values between generations? Generation 2.4? 

- [ ] What happens when the Values Marker overlaps the y-axis zoom buttons? Is the Value Marker on top? Does the user have to move the Values Marker to use the zoom buttons? (This is a moot question if we move the zoom buttons outside the graph, at upper left.)

- [ ] What happens when the Values Marker overlaps the arrow buttons? (This is a moot question if we move them the arrow buttons out of the graph, and put them on left and right of "Generation" x-axis label.)

**Comment by pixelzoom** [comment]
11/21/19 design meeting:

Need a better term than "Values Marker".

**Comment by pixelzoom** [comment]
11/21/19 design meeting (@amanda-phet @kathy-phet @ariel-phet @arouinfar @oliver-phet @pixelzoom)

We discussed and addressed all checklist items as noted above.

@oliver-phet suggested directly manipulating the graph to scroll it. We decided against this for a11y and phet-io reasons, and a consensus that obvious controls were preferred.

@kathy-phet suggested making the marker follow the "leading edge" of the data, and the chart is populated. @amanda-phet said that we want students to be watching the bunnies, and that the marker display would be to noisy to monitor the "now" state of the sim.

Summary of requirements:
* The marker is associated with a screen position, not an x-axis value.
* The marker does not move when the x-axis is scrolled.
* The makers "flags" move to the left or right side of its "stick" at the edges of the graph.  The entire marker is always within the bounds of the graph. 
* All other controls (x-axis scroll, y-axis zoom) will be moved off of the graph.

Open issues:
* We need a better term than "Values Marker".

**Comment by pixelzoom** [comment]
As noted in #18, for small percentage values, the bars alone are problematic.  A small sliver of a bar is difficult to see. Here are examples for 99% + 1% and 1% + 99%:

<img width="136" alt="screenshot_1709" src="https://user-images.githubusercontent.com/3046552/69586849-16822280-0fa1-11ea-8756-f08b6136070d.png">
<img width="136" alt="screenshot_1718" src="https://user-images.githubusercontent.com/3046552/69586854-17b34f80-0fa1-11ea-8de2-0718e986eb2a.png">

Depending on how #18 its addressed, this may be a good reason to drop this feature and _not_ to hide the values.

**Comment by pixelzoom** [comment]
The final issue here is:

> * We need a better term than "Values Marker".

Assigning to @amanda-phet to come up with alternative names.

**Comment by amanda-phet** [comment]
It is called a cursor line in https://www.wunderground.com/forecast/us/co/boulder/80302. That's also the term Mike Dubson has used in Calculus Grapher. It is also similar to a scrubber used in video editing. 

So I don't lose my ideas, I'm listing them here, and we can try to decide on something tomorrow.
- cursor line
- data values
- values reader
- values slider

Lastly, I wonder what we might do with this sort of control if outfitted for keyboard navigation. Might it be a slider under the hood? Maybe we could call it a values slider.

**Comment by pixelzoom** [comment]
I'm not wild about "cursor" because it's so overloaded (has a different meaning in scenery).  And the cursor on a chart is not typically constrained to 1 dimension, as ours is. But here's an example that's somewhat similar to our UI component: https://www.amcharts.com/docs/v4/concepts/chart-cursor/ (click "Run Pen" to see the example). 

Scrubber seems nice.  Angular (popular JavaScript framework) uses "scrubber", see
https://www.azavea.com/blog/2018/06/05/d3-chart-data-scrubber-in-angular/

I don't think we should use "slider", for the same reason that we don't rename `NumberControl` to some "slider" type.   While a11y may effectively instrument something to be slider-like for the purposes of interaction, it's much different than a slider in other aspects (what it displays, etc.). I also suspect that a11y will have a difficult time treating this like a slider, because it's not a single value - there is one x (Generation) value, for which it displays multiple y (Population) values.

**Comment by pixelzoom** [comment]
12/12/19 design meeting

We decided on "Data Probe".

**Comment by pixelzoom** [comment]
All work has been done here. The only thing left to do is add live data. Closing.
