### ISSUE TITLE
sprites are not scaled with ?webgl=false

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#142]
There's a problem with the sprites implementation. None of the sprites are scaled, see screenshot below.

This was noted on my 2009 MacBook Pro + macOS 10.11.6 + Chrome 84.0.4147.105 (latest), with [1.0.0-dev.75](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.75/phet/natural-selection_en_phet.html).  Nothing in the browser console. It does not occur in Safari 11.1.2 or Firefox 78.1.0esr.

The PhET website indicates support for "macOS 10.12+", so this is a not a supported platform. But we should test immediately on older versions of macOS.

![screenshot_973](https://user-images.githubusercontent.com/3046552/88726641-59c20180-d0eb-11ea-81d0-85c393bc1758.png)

**Comment by pixelzoom** [comment]
@KatieWoe please test this with PhET's macOS 10.12 test device (Dirac?) and Chrome 84 latest.

**Comment by pixelzoom** [comment]
@jonathanolson any thoughts on why this might be occurring, and whether it might be a problem on other platforms?

**Comment by jonathanolson** [comment]
Looking into it, reproducible with `?webgl=false` on my Chrome.

**Comment by pixelzoom** [comment]
I also reproduced with ?webgl=false on macOS 10.15.5, with Safari 13, Chrome 84, and Firefox 79.  I'm guessing there's a bug in the canvas renderer.

**Comment by pixelzoom** [comment]
@KatieWoe  no need to do any further testing, thanks.

**Comment by jonathanolson** [comment]
I believe the above commit should fix this. @pixelzoom can you verify?

**Comment by pixelzoom** [comment]
In the above commit, I added logging that tells us whether we're using WebGL.  WebGL is apparently not supported on my 2009 MacBook Pro, and there was a bug in the canvas fallback.  

I verified the fix to SpritesCanvasDrawable in master - thanks for the quick fix!  

Closing,
