### ISSUE TITLE
"Wolves" checkbox has an inconsistent pointer area 

### ISSUE THREAD

**Issue by phet-steele** [phetsims/natural-selection#145]
The "Wolves" checkbox is the only one that cannot be enabled/disabled by clicking over its timer icon (on both screens). In the below screenshot, everything to the left of the red line *can* be clicked, and things to the right cannot.

Pinging @pixelzoom so he is aware, but I don't think this needs to be addressed before prototype release.

![image](https://user-images.githubusercontent.com/5863899/88986663-e22dd700-d290-11ea-8e71-40b5b1d92155.png)

Seen on Win 10 Chrome 84.0.4147.89. For phetsims/QA/issues/522.

<details>
<summary>Troubleshooting Information</summary>

Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.0.0-rc.1/phet/natural-selection_all_phet.html
Version: 1.0.0-rc.1 2020-07-29 19:13:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: en-US
Window: 1456x923
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by pixelzoom** [comment]
Thanks. If it's fairly easy, I'll probably patch this into the release branch.

**Comment by pixelzoom** [comment]
Below is a better picture of what's going on. I explicitly set the pointer areas to `this.localBounds.dilated(0)` so that they are rendered with `?showPointerAreas`.   This is very odd, since all 3 checkboxes are using the identical implementation in EnvironmentalFactorCheckbox.js. 

<img width="260" alt="screenshot_445" src="https://user-images.githubusercontent.com/3046552/88999048-b1f63080-d2b0-11ea-9519-d6dbc7547c53.png">

**Comment by pixelzoom** [comment]
And it gets stranger... If I create the "Tough Food" checkbox before the "Wolves" checkbox, then all of the pointer areas are OK, see below.  I suspect something weird is going on with AlignGroup, which is used to give all of the Text+Icon parts of the checkbox label the same effective width.

<img width="231" alt="screenshot_446" src="https://user-images.githubusercontent.com/3046552/88999334-7c057c00-d2b1-11ea-8ea4-779855690736.png">

**Comment by pixelzoom** [comment]
This is a general issue with Checkbox, to be addressed in https://github.com/phetsims/sun/issues/612.

In the meantime, I've applied a reasonable workaround in master and 1.0.  Ready for the testing in the next RC.

**Comment by pixelzoom** [comment]
Since the next 1.0 RC is going to be a merge from master, and this has been verified in master, I'm closing this issue.
