### ISSUE TITLE
Sim inconsistently claims there is a second bunny if a mate is added while the sim is paused

### ISSUE THREAD

**Issue by phet-steele** [phetsims/natural-selection#147]
1. Enter a screen
2. Pause the sim
3. Press "Add a Mate"

The second bunny will not actually appear, yet some places in the sim claim there are two bunnies (see screenshots). Namely:

- The population chart will show a dot at "2"
- The proportions display will claim two bunnies exist

Up to @amanda-phet to decide if this has a problematic pedagogical impact and if it should be addressed before the prototype release. Keep in mind that it is *very* simple to get the second bunny to appear. A non-exhaustive list includes:

- Resuming/fast forwarding the sim
- Clicking the existing bunny
- Enabling/disabling "Limited food"
- A few other ways....

(Also note how the Data Probe does not read any data yet, but it will once the sim is resumed. Could be its own issue.)

![image](https://user-images.githubusercontent.com/5863899/88983374-12bd4300-d288-11ea-97e6-4d58c08629d3.png)

![image](https://user-images.githubusercontent.com/5863899/88983395-210b5f00-d288-11ea-8517-737c1a980727.png)

Seen on Win 10 Chrome 84.0.4147.89. For phetsims/QA/issues/522.

<details>
<summary>Troubleshooting Information</summary>

Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.0.0-rc.1/phet/natural-selection_all_phet.html
Version: 1.0.0-rc.1 2020-07-29 19:13:57 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.89 Safari/537.36
Language: en-US
Window: 1456x923
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
</details>

**Comment by pixelzoom** [comment]
No need for @amanda-phet to review.  This is a bug in the new sprites implementation.  The bunny sprite is indeed created, but the sprites view isn't updated until the clock ticks.   I'll need to force an update when the sim is paused.  Should be an easy fix.

**Comment by pixelzoom** [comment]
Fixed in master and 1.0 branch, ready for testing in next RC.  @phet-steele feel free to take a peek in master.

**Comment by pixelzoom** [comment]
Since the next 1.0 RC is going to be a merge from master, and this has been verified in master, I'm closing this issue.
