### ISSUE TITLE
model.md

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#150]
Write the model description in https://github.com/phetsims/natural-selection/blob/master/doc/model.md.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/natural-selection/issues/9#issuecomment-550122595 has a "crash course in genetics", maybe use some of that for model.md.

**Comment by pixelzoom** [comment]
model.md is done and ready for review. @amanda-phet let me know if there's anything you'd like to change.  I'm a little cross-eyed after writing this, so If you see any typos, feel free to correct them.

**Comment by amanda-phet** [comment]
I made two minor edits. @pixelzoom want to review them and close if they look ok to you?

**Comment by pixelzoom** [comment]
Edits look great, thanks @amanda-phet. Closing.

**Comment by pixelzoom** [comment]
@amanda-phet FYI, I added a **Bibliography** section to model.md, https://github.com/phetsims/natural-selection/blob/master/doc/model.md#bibliography
