### ISSUE TITLE
number of bunnies killed is sometimes 1 more than expected

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#155]
As noted over in https://github.com/phetsims/natural-selection/issues/153#issuecomment-668701767, sometime the number of bunnies that are starved seems to be 1 more than expected.

In https://github.com/phetsims/natural-selection/issues/153#issuecomment-668739934, I identified the problem in Food.js. I'm using `ceil` instead of `round`, in order to ensure that at least 1 bunny is starved.   That's problematic, and there's a better way.

I also see that there's a similar problem with the use of `ceil` in WolfCollection.js, so I'll address that too.

**Comment by pixelzoom** [comment]
The correct way to round and ensure that a value is at least 1 is:

`Math.max( 1, Utils.roundSymmetric( value ) )`

I'll apply this to Food.js and WolfCollection.js.

**Comment by pixelzoom** [comment]
Fixed in the above commits in master and 1.0 (prototype) branch.  For phetsims/QA#522.

@oliver-phet please test with phet-test, to confirm that you can no longer reproduce the scenario that you reported in https://github.com/phetsims/natural-selection/issues/153#issuecomment-668701767.

**Comment by pixelzoom** [comment]
Fixed in the above commits in master and 1.0 (prototype) branch.  For phetsims/QA#522.

@oliver-phet please test with phet-test, to confirm that you can no longer reproduce the scenario that you reported in https://github.com/phetsims/natural-selection/issues/153#issuecomment-668701767.  Assign back to me when you're done.

**Comment by oliver-phet** [comment]
Looks good!

**Comment by oliver-phet** [comment]
Ack, spoke too soon! I just had it happen again on phettest but I didn't have log enabled. Let me look a bit more.

**Comment by pixelzoom** [comment]
@oliver-phet if you could prioritize this, it would be great. It needs to be completed before I can publish the next RC for the prototype.

**Comment by oliver-phet** [comment]
Sorry, other things came up since yesterday! I've done a few runs now and I'm not seeing the population drop to 1.

**Comment by pixelzoom** [comment]
I have not seen it happen again either.  I'm guessing that phet-test hadn't pulled my fix yet when you experienced this in https://github.com/phetsims/natural-selection/issues/155#issuecomment-668842554.

So I'm going to consider this ready for testing in the next RC for 1.0 prototype.

To verify:
1. Open the browser console.
2 . Run the sim with query parameters ?log&initialScreen=2&labMutations=T&labPopulation=1tt,6TT
3. Check the "Limited Food" checkbox
4. Press the "Play" button
5. As soon as the generation clock completes the "food" slice of the clock, pause the sim, and verify that the console log says:

> attempting to starve bunnies
> 4 bunnies with long teeth died of starvation
> 1 bunnies with short teeth died of starvation

The last line should not be "2 bunnies".

**Comment by amanda-phet** [comment]
This seems to be working fine for me.

**Comment by pixelzoom** [comment]
Since the next 1.0 prototype RC is going to be a merge of master, and this was verified in master, I'm going to close this issue.
