### ISSUE TITLE
State Wrapper: dialogs do not display in downstream sim

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#156]
In the State Wrapper, sim-specific Dialog subclasses do not display in the downstream sim.  Examples:

WorldDialog:
<img width="507" alt="screenshot_451" src="https://user-images.githubusercontent.com/3046552/89341163-1d981f00-d65e-11ea-8e5b-34afc4beb0e3.png">

DiedDialog:
<img width="533" alt="screenshot_450" src="https://user-images.githubusercontent.com/3046552/89341172-212ba600-d65e-11ea-91f5-261f3fbc13e4.png">

For some reason the GenerationLimitDialog (a subclass of OopsDialog) does display:

<img width="502" alt="screenshot_452" src="https://user-images.githubusercontent.com/3046552/89341403-7ff11f80-d65e-11ea-919b-ad5afc75154f.png">

**Comment by pixelzoom** [comment]
iO team, could you explain what's going on here? All 3 of these dialogs are uninstrumented, but one of them is displayed downstream.

**Comment by samreid** [comment]
Often dialogs are treated as transient and therefore not stateful, and not expected to display in the downstream simulation.  In some cases, when the showing of a dialog is triggered by a stateful Property, then it is natural for that dialog to be showed in the downstream simulation.

**Comment by pixelzoom** [comment]
Thanks. That explains why the GenerationLimitDialog is displayed and the others are not.  GenerationLimitDialog is displayed by listener of generationClock.currentGenerationProperty.   The other 2 dialogs are displayed as the result of Emitters firing during model.step.

I see that Dialog has `isShowingProperty`.  So if I instrument the other 2 Dialogs, I'm guessing that they will be shown in the downstream sim.

**Comment by pixelzoom** [comment]
Instrumenting the dialogs did the trick, and they are now appearing in the downstream sim.

Closing.

**Comment by pixelzoom** [comment]
Glad I reopened, some good additional changes here:

* renamed GenerationLimitDialog to MemoryLimitDialog, because the messages tells the user that they've hit a "memory limit", not a "generation limit"
* added phetioDocumentation to all dialogs
* grouped dialogs under `naturalSelection.introScreen.view.dialogs` and `naturalSelection.labScreen.view.dialogs`, to reduce clutter at the view level

Since overall PhET-iO review is pending in https://github.com/phetsims/natural-selection/issues/5, I'm going to close this issue and assume that review related to these dialogs will be handled there.
