### ISSUE TITLE
Population graph looks empty when all data is above yMax

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#157]
Here's an interesting usability issue.  The Population graph has default y-axis range of 0-50.  It can be manually changed using the zoom buttons.   But it's entirely possible for all of the data to be above yMax, resulting in something like the screenshot below. The first time I saw this, I didn't have the Data Probe enabled, the graph was totally blank, and I thought it was broken.

@amanda-phet Do we need to do anything about this? 

<img width="1057" alt="screenshot_449" src="https://user-images.githubusercontent.com/3046552/89341792-16254580-d65f-11ea-976a-7107ab393901.png">

**Comment by amanda-phet** [comment]
This has always been a possibility, and since the user is likely going to see the graph before it gets out of view I'm not too concerned. (An example situation where this would be an issue would be in PhET-iO if the client starts with a population >50 and doesn't change the zoom.)

**Comment by pixelzoom** [comment]
The query parameters for setting initial population are not specific to PhET-iO, so what you described is possible in brand=phet.

**Comment by pixelzoom** [comment]
The query parameters for setting initial population are not specific to PhET-iO, so what you described is possible in brand=phet.  And there's no way to set the initial y-axis range via query parameter.

**Comment by amanda-phet** [comment]
That is true. I don't have any great ideas about how to solve this usability issue, though. 

@ariel-phet ?

**Comment by ariel-phet** [comment]
@pixelzoom @amanda-phet  I have a thought, but perhaps not a great one

@pixelzoom I assume you could interrogate the model at some regular interval and decide whether the data was out of range (I assume there is some function that given the zoom level that view is at least aware of the range). If you were in some situation like this could we just display a message on the graph that says "zoom out to see data" or something like that?

Not sure if it is worth the effort, but maybe that is potentially relatively easy to do?

**Comment by pixelzoom** [comment]
@ariel-phet is something like this what you had in mind? @amanda-phet does that work for you?

![zoom-out](https://user-images.githubusercontent.com/3046552/89429153-6f8e8280-d6fa-11ea-96b9-af3fba12bf87.png)

**Comment by amanda-phet** [comment]
Yes that works for me!

**Comment by ariel-phet** [comment]
Yes, exactly what I had in mind. I think that is worth the time

**Comment by pixelzoom** [comment]
Hmm... I took a quick look and this is more complicated than I anticipated.  Each plot is independent, without knowledge of the other plots, so I don't know whether any of the data points are < yMax.  I could add new code to look through all 7 data sets, but that will most certainly create a performance problem.  I'll need to ruminate on this...

**Comment by pixelzoom** [comment]
I'm assuming that this is NOT blocking for 1.0 prototype publication.  If that's incorrect, please let me know asap.

**Comment by pixelzoom** [comment]
I implemented this in the above commits, but it feels a bit too clever.  It relies on examining the bounds of the parent Node for the plots, and those bounds overlap the grid.   I would prefer an approach that lets me determine the bounds after clipping, to see if anything was actually rendered.

**Comment by pixelzoom** [comment]
Labeling "blocks-sim-publication", since work on this is now in an intermediate and untested state.

**Comment by pixelzoom** [comment]
This looked more promising:

```js
    // If there's data that's not visible, then display 'Zoom out to see data.'
    // This checks to see if plotsNode's bounds intersects its clipArea.
    plotsNode.localBoundsProperty.link( localBounds => {
      const dataIsVisible = localBounds.isFinite() && plotsNode.clipArea.intersectsBounds( localBounds );
      zoomOutToSeeDataText.visible = !dataIsVisible && ( populationModel.generationsProperty.value !== 0 );
    } );
```

But then I discovered that `plotsNode.clipArea.intersectsBounds( localBounds )` is false if the localBounds is fully contained in clipArea.  So when all of the data is visible, I'm seeing the "Zoom..." message.  I'm not sure if that's a bug or expected behavior for `intersectsBounds`.

**Comment by pixelzoom** [comment]
This seems to work nicely, so I've committed it:

```js
    // If there's data that's not visible, then display 'Zoom out to see data.'
    assert && assert( plotsNode.clipArea, 'plotsNode.clipArea is required' );
    const clipAreaBounds = plotsNode.clipArea.getBounds();
    plotsNode.localBoundsProperty.link( localBounds => {
      const dataIsVisible = localBounds.intersectsBounds( clipAreaBounds );
      zoomOutToSeeDataText.visible = !dataIsVisible && ( populationModel.generationsProperty.value !== 0 );
    } );
```

I've asked @jonathanolson on Slack if there's a better way. I'll wait until I hear back before working on this further.

**Comment by pixelzoom** [comment]
Discussed with @jonathanolson on Slack.  What I'm doing now is best, especially since it needs to have good performance.

@amanda-phet please review in master or [1.1.0-dev.5](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.5/phet/natural-selection_en_phet.html).  If you want to start with an initial population that triggers this immediately, run with `?brand=phet&ea&log&initialScreen=2&labPopulation=60`.  When you press the "Play" button, you'll immediately see "Zoom out to see data."  Then you can adjust the zoom level to make the message go away and reappear.

**Comment by amanda-phet** [comment]
Thanks for the query parameter ;) Looks good to me. I also ran it with just 1 bunny to start and got the data to eventually be off the graph, and can confirm that the message showed up in that case too and looked great.
