### ISSUE TITLE
Population graph clips points and line segments at yMax

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#159]
In the Population graph... 

When a point or line segment falls on yMax, the top part of it is being clipped.  You can see this if you start the sim with `?labPopulation=50` and press the "Play" button.  Note how the top half of both the point and line segment are clipped in this screenshot:

<img width="266" alt="screenshot_455" src="https://user-images.githubusercontent.com/3046552/89433102-23920c80-d6ff-11ea-9a99-452158ce6b1b.png">

To make points at yMax fully visible requires adjusting the clipArea for PopulationPlotsNode. That creates a new problem - a tiny bit of vertical line segment is visible that shouldn't be. You can see it at the right end of the line segment in this screenshot:

<img width="262" alt="screenshot_454" src="https://user-images.githubusercontent.com/3046552/89432430-58ea2a80-d6fe-11ea-9bda-d7e330f05952.png">

The points and line segments have different clipping needs, so the problem could be resolved by having different clipAreas for points vs line segments.   But that would mean 2 clipAreas for each plot, which is 7 x 2 = 14 clipAreas.  And (for performance reasons) there's currently 1 clipArea for the entire graph.   So I really don't want to go down that path.

So our options are:

(1) Live with one of the two "visual warts" demonstrated above.  This will take close to zero time. It's just a matter of deciding which is the lesser evil.

(2) Reimplement the Population graph so that clipArea is not needed. The code will be significantly more complicated, so I'm not sure it's worth it. This would take somewhere in the 1-3 hour range. (I wish I'd noticed this when working on https://github.com/phetsims/natural-selection/issues/146.)

I'm inclined to recommend (1), like the first screenshot above, which is what is currently implemented.

@amanda-phet your thoughts?

**Comment by pixelzoom** [comment]
I'm inclined to recommend the behavior in the first screenshot above, which is the what is currently implemented.

**Comment by pixelzoom** [comment]
Since this is a "polish" issue, I'm assuming that it's not required for the 1.0 prototype.  If that's incorrect, let me know asap.

**Comment by pixelzoom** [comment]
Maybe @ariel-phet has an opinion on this one?

**Comment by pixelzoom** [comment]
Here's a compromise that seems OK.  I've adjusted the clipArea so that line segments that fall on yMax are not clipped and therefore rendered at their full with.  The top part of a point that falls above yMax is still clipped, but it's much less noticeable. See screenshot below. 

@amanda-phet @ariel-phet is this acceptable?

<img width="201" alt="screenshot_480" src="https://user-images.githubusercontent.com/3046552/90015465-e16c4c00-dc65-11ea-8fea-7aa872ebb123.png">

**Comment by amanda-phet** [comment]
@pixelzoom the "compromise" looks great to me. Thanks for thinking of that option.

**Comment by pixelzoom** [comment]
Excellent, closing!
