### ISSUE TITLE
Are overlapping plots in the Population graph a significant usability problem?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#163]
In #101, we identified overlapping plots as a potential usability problem:

> * If plots overlap, one or more sets of data will be hidden. For example, if there are equal numbers of bunnies with white fur and brown fur, only one data set will be visible.

In https://github.com/phetsims/natural-selection/issues/101#issuecomment-648349693, @amanda-phet concluded:

> I am not sure there is much we can do about overlapping graphs, and the current graph seems superior to the Java version because of the handy data probe, and the fact that you can choose which graphs to view at any given time.

We should watch for this as a potential problem in interviews.

**Comment by amanda-phet** [comment]
Didn't see problem with this. Some students even unchecked total to see the lines clearly, but I didn't notice any issues with interpreting the graphs with overlapping lines.
