### ISSUE TITLE
Are students able to connect color + line style to allele?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#164]
Traits (fur, ears, teeth) are color coded.  And we use line style to differentiate between alleles for a trait: solid line for normal allele, dashed line for mutant allele.   MH called this out as something that she didn't understand at first.   So we should watch for this in interviews.  Are students able to connect color + line style to allele?

**Comment by amanda-phet** [comment]
Yes, all students interviewed were using the legend to interpret the graphs. I didn't see any issues.
