### ISSUE TITLE
Usability of "Add a Mate", "Play", and "Start Over" button group

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#166]
Related to the "Add a Mate", "Play", and "Start Over" button group...

From https://github.com/phetsims/natural-selection/issues/54#issuecomment-616823639:

> There's still a bit of a usability problem here. When I press "Start Over", the "Add a Mate" or "Play" button appears in it's place. The buttons are all the same color, and they appear in the same place. So it's easy not to notice that the "Start Over" button was replaced, and you have to click another button to continue. This is especially the case with a touch device, where your finger covers the "Start Over" button.

Before making any changes, @amanda-phet said that she'd "like to interview on this first to see if it is in fact a usability concern."

**Comment by amanda-phet** [comment]
There didn't seem to be any concerns with this button group during interviews. Students easily used "Add a Mate" and "Start Over."

**Comment by pixelzoom** [comment]
Reopening.

In https://github.com/phetsims/natural-selection/issues/60#issuecomment-680187532, @KatieWoe encountered this usability issue:
> Note that the bug where clicking "Start Over" twice skips the button to add a friend. This seems like it would be relatively easy to do on even a faster moving device.

This is not the first time she's experienced or reported this. She also reported in https://github.com/phetsims/natural-selection/issues/60#issuecomment-662625708:
> Larger problem was actually the Start Over button. It could take a few seconds on ChromeOS and was slower than expected on all platforms. I thought I had misclicked on ChromeOS and clicked again, and that seemed to register as Add a Mate, which seems problimatic.

Assigning to @amanda-phet to re-evaluate.

**Comment by amanda-phet** [comment]
@KatieWoe So, to be clear, you clicked Start Over, waited, clicked it again, and then it added a mate (without you seeing the "Add a Mate" button), is that right? 

I suppose we should consider a different location for the "Start Over" and "Play" buttons. @pixelzoom didn't we have them more in the center of the play area at one time? Can we put them there, but leave the "Add a Mate" button toward the bottom?

**Comment by amanda-phet** [comment]
Since this is a usability issue, assigning to @ariel-phet  as well.

**Comment by pixelzoom** [comment]
I sort of hate to move the buttons at this point, since the seem to be generally working well.  So something else I'd like to investigate here...  See if the "Add a Mate" button can ignore events like the extra click that @KatieWoe is doing.  And I should see when the "Add a Mate" button is being made visible, whether changing it's pickability might help, etc.

**Comment by KatieWoe** [comment]
@amanda-phet @pixelzoom, yes that is what I am doing. It can either happen if you try to click the button again when the start over is loading, or if you double click instead of single click it will also happen.

**Comment by pixelzoom** [comment]
I consulted with @jonathanolson on this, since it involves scenery input processing. Using timer to make the 'Add a Mate' (or 'Play') button visible _in the next frame_ sounded like a reasonable solution.  It prevents unwanted presses from getting to the button, and the delay in making the button visible is imperceptible.

To verify, compare the behavior of these dev versions.

Before the change, in (1.1.0-dev.16)[https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.16/phet/natural-selection_en_phet.html], I can double-click on the "Start Over" button and cause the "Add a Mate" button to fire, so that I don't even see the "Add a Mate" button, even on my fast MacBook Pro.

After the change, in (1.1.0-dev.17)[https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.17/phet/natural-selection_en_phet.html], a double-click on the "Start Over" button does not reach the "Add a Mate" button.

@amanda-phet please verify in the dev versions above.  

@KatieWoe could you also please verify that this fixes the usability problem that you reported? 

Feel free to use `?secondsPerGeneration=1` to speed up your testing.

**Comment by KatieWoe** [comment]
Things look pretty good, even on ChromeOS. May actually work a bit better on the slower device actually.

**Comment by KatieWoe** [comment]
With a slower device I was able to see the fix better. The double click seemed like it might still be happening on the fast devices, but that was because the new button was up by the time the second click came. Mostly I just mean it worked better for my testing. Sorry for the confusion.

**Comment by pixelzoom** [comment]
Yeah! Very happy that this works.  Thanks for testing @KatieWoe.

@amanda-phet if this looks OK to you, feel free to close.

**Comment by amanda-phet** [comment]
Thanks @KatieWoe that makes sense. Since I don't have a slow device this is tricky for me to reproduce, but it sounds like the original usability issue pertaining to slower devices is fixed! Thanks for testing, and thanks @pixelzoom for coming up with a good solution to this.

**Comment by pixelzoom** [comment]
Reopening. This unfortunately introduced a PhET-iO state problem in https://github.com/phetsims/natural-selection/issues/211.  So I'll need to revert and find another way.

**Comment by pixelzoom** [comment]
I've moved the Start Over button problem to its own issue, https://github.com/phetsims/natural-selection/issues/217, where it will be easier to track, regression test, etc.

So re-closing this issue.
