### ISSUE TITLE
Design Q: 'Tough Food' causes long teeth bunnies to starve regardless of 'Limited Food'

### ISSUE THREAD

**Issue by oliver-phet** [phetsims/natural-selection#168]
@amanda-phet When I was testing for https://github.com/phetsims/QA/issues/522 I noticed that even in a population of all Long Teeth bunnies, many would "die of starvation" with Limited Food **unchecked**. I was under the impression the design of Tough Food was to make it more clear to users that it was selecting for Long Teeth. 

While it makes sense to me for Short Teeth bunnies to "die of starvation" in the Tough Food scenario, if food is **unlimited** and the bunnies have long teeth I would expect the bunnies to quickly take over the world. Currently, the default value is 40-70% of Long Teeth bunnies die with Tough Food (and 56-98% of short teeth bunnies) [from my understanding of the values.](https://github.com/phetsims/natural-selection/blob/master/js/common/NaturalSelectionQueryParameters.js)

**Comment by amanda-phet** [comment]
You have the values correct. I tried to mimic the behavior in the Java sim, which is how I ended up with those values. Most of the time the long-tooth bunnies will in fact take over the world, just not as quickly or predictably as other unlimited food scenarios. I could check with Megan to see if she'd like to see them take over the world more aggressively, if you recommend this change. @kathy-phet is also in touch with another Biology expert and we could ask that person.

**Comment by oliver-phet** [comment]
I do think it would be good to get Megan's/other expert's opinions. I personally think having bunnies "die of starvation" in an unlimited food scenario conflates what 'Tough Food' and 'Limited Food' factors are accomplishing. The current behavior aligns more closely with what I would expect in a Limited+Tough Food scenario.

Just a quick test I did:

1. Add Long Teeth Dominant
2. Add a Mate
3. Immediately after generation 0 breeds, add selection factors to contrast what happens.

I just did 3 tests of both scenarios, in all 6 the bunnies took over the world:
**Tough Food**: take over the world in 33/21/27 generations (avg 27)
**Tough + Limited Food**: take over the world in 29/29/35 generations (avg 31)
vs 
**Soft Food**: bunnies almost always take over the world generation 6

**Comment by oliver-phet** [comment]
I'm just now reading the discussion in https://github.com/phetsims/natural-selection/issues/161, sounds like we should hold off on any changes until work on that is finished.

**Comment by pixelzoom** [comment]
Yes, please pause on Food testing.  It's getting a complete makeover, in order to address #161.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> ... I could check with Megan to see if she'd like to see them take over the world more aggressively, if you recommend this change. @kathy-phet is also in touch with another Biology expert and we could ask that person.

Top priority if we're going to do this.

**Comment by pixelzoom** [comment]
@amanda-phet and I chatted a bit about this on Slack.  Based on last Friday's interviews, she's going to adjust the `toughFoodPercentToKill` and `shortTeethMultiplier` query parameters, so that fewer long-teeth bunnies die.

**Comment by pixelzoom** [comment]
Via Slack, @amanda-phet said that she's like to change these values before her next interviews on Thursday 8/13/2020.

**Comment by amanda-phet** [comment]
Megan confirmed that this is a good idea to allow the long tooth bunnies to take over the world. 

I discussed this with @pixelzoom and we should be able to use the current model, as long as there is a function to put a ceiling on the values so that they never multiply to be >100%. 

`toughFoodPercentToKill=.45,.6`
`shortTeethMultiplier=1.6`
`limitedFoodMultiplier=1.25`

These values seem to meet all of our needs: long tooth bunnies can take over the world, and limited food can stabilize the population. There's no guarantee with both checked, because it can really depend on how much you let the population build up first and when you check limited food, but in a bunch of trials this seems to be working well for both dominant and recessive mutations. 

Hoping @pixelzoom can implement this in a dev version by 11am Thursday, but if not I will just use query parameters in the link I send to my interviewee.

**Comment by pixelzoom** [comment]
Changes completed in master and [1.1.0-dev.7](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.7/phet/natural-selection_en_phet.html).  @amanda-phet please review.

**Comment by amanda-phet** [comment]
I think it looks great! 

@oliver-phet do you want to take a look?

**Comment by oliver-phet** [comment]
Yep, the latest is behaving much more like what I would expect!

**Comment by amanda-phet** [comment]
Thanks for reviewing. I think this issue is wrapped up, and further discussion of the food model can happen in https://github.com/phetsims/natural-selection/issues/169.
