### ISSUE TITLE
positions for food

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#17]
Like the Java version, food will be located at fixed positions.  Positions are the same for equator/arctic and tough/tender food.  And I’ll make it easy to move/add/remove food. 

@amanda-phet provided these mockups to show where she'd like the food positioned. (Food is not scaled based on z-depth in these mockups, but will be scaled in the sim.)

With "Limited Food" unchecked:

![image](https://user-images.githubusercontent.com/3046552/69451542-e1659e00-0d1c-11ea-9bdd-fac515c3a161.png)

With "Limited Food" checked, the amount of food is reduced by 1/2:

![image (1)](https://user-images.githubusercontent.com/3046552/69451621-0f4ae280-0d1d-11ea-97d7-17783ca48edc.png)

**Comment by pixelzoom** [comment]
@amanda-phet this is ready for review in [1.0.0-dev.23](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.23/phet/natural-selection_en_phet.html).  If you run with `?dev`, you'll see the food labeled like your mockups (A1, A2, B1, B2, C1, C2).  The food with a '2' will be removed when "Limited Food" is checked.

If this looks good enough for now, feel free to close this issue.  It's easy to tweak food locations, and we can do that when there's more action happening.

**Comment by amanda-phet** [comment]
Thanks @pixelzoom . Once we see bunnies hopping around I might have a better idea but for now this looks good.

**Comment by pixelzoom** [comment]
For posterity...  As I mentioned in https://github.com/phetsims/natural-selection/issues/17#issuecomment-577467404, running with `?dev` labels the food.   Once I started PhET-iO instrumenting food, it became burdensome to label as shown in the screenshots above.   So food is now labeled using tandem names, as shown in the screenshot below. Odd-numbered food is removed when "Limited Food" is checked.

<img width="808" alt="screenshot_241" src="https://user-images.githubusercontent.com/3046552/78405720-521ba180-75be-11ea-8f0b-4b382defd281.png">

**Comment by pixelzoom** [comment]
More for posterity...  I got rid of the labels on shrubs.  And then the entire view here was reimplemented using scenery Sprites.
