### ISSUE TITLE
Change initial location of data probe

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#173]
Currently, if the user checks "Data Probe", the probe is placed at the left most edge of the graph (the initial offset is 0). I'd like this initial offset to be somewhere else, such as an offset of 1.5 (so the probe ends up between generations 1 and 2). 

Hoping that by having the probe in the middle of the graph, users realize it can be moved around in the graph.

**Comment by pixelzoom** [comment]
Implemented in the above commit.  Initial position of the data probe looks like this:

<img width="502" alt="screenshot_465" src="https://user-images.githubusercontent.com/3046552/89942500-edaac780-dbd9-11ea-8587-1c7c16bae3fe.png">

@amanda-phet please review in master, close if it looks OK.

**Comment by pixelzoom** [comment]
In Slack, @amanda-phet said:

> We might also increase the size/color/design of the ball/handle.

Do you want to do anything about this?  The manipulator (aka "ball") currently has radius=5.   We could probably get away with as large as the graph radio buttons, which have radius=8.  Here are comparison screenshots:

radius=5
<img width="877" alt="screenshot_467" src="https://user-images.githubusercontent.com/3046552/89943459-7413d900-dbdb-11ea-9c6a-aceba1b1be11.png">

radius=8
<img width="879" alt="screenshot_466" src="https://user-images.githubusercontent.com/3046552/89943469-7a09ba00-dbdb-11ea-8c57-01e60a607d43.png">

**Comment by pixelzoom** [comment]
And here are the current pointer areas, if you want to adjust that while we're at it.

<img width="881" alt="screenshot_468" src="https://user-images.githubusercontent.com/3046552/89943607-b89f7480-dbdb-11ea-8677-28b5e56a69a4.png">

**Comment by amanda-phet** [comment]
I love the new starting position and am looking forward to interviewing with it tomorrow. 

If the student still doesn't move it, I'll vote for increasing the radius of the manipulator.

**Comment by amanda-phet** [comment]
8/13/20 design meeting: 

- in the final interview, the student immediately moved the data probe when it was visible
- we like increasing the radius of the manipulator to  7, and make the touch area as large as it can be without overlapping with the Generation buttons.

**Comment by pixelzoom** [comment]
In master, the manipulator radius has been changed to radius:7, and its pointer areas have been dilated to 2 x radius = 14.  I also adjusted pointer areas for checkboxes.  Screenshot below. @amanda-phet please review.

<img width="1122" alt="screenshot_482" src="https://user-images.githubusercontent.com/3046552/90183338-90954a00-dd70-11ea-843b-8ba199243a39.png">

**Comment by amanda-phet** [comment]
I like the new size, as well as the touch areas.

**Comment by pixelzoom** [comment]
Excellent. Closing, since master will be used for the next prototype RC.
