### ISSUE TITLE
Population y-axis ranges and tick intervals

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#174]
For the Population graph zoom control... The y-axis ranges and tick-mark intervals weren't specified in the design doc. The current values are something that I threw in (somewhat informed by the Java version, but not exactly the same), intending to review later.

There are currently 15 zoom levels.

yMax for the ranges are: `[ 2500, 2000, 1400, 1000, 500, 350, 240, 200, 140, 100, 70, 50, 30, 14, 5 ]`

The corresponding tick-mark intervals are: `[ 500, 200, 200, 100, 100, 50, 40, 40, 20, 20, 10, 10, 5, 2, 1 ]`

The jump between yMax 1000 and 500 is the one that feels like it needs something in between.

@amanda-phet and @ariel-phet your thoughts?

**Comment by amanda-phet** [comment]
I agree, I think an additional range that goes to 700 would make sense, with tick marks at every 100. Thanks for noticing that and requesting a review.

**Comment by pixelzoom** [comment]
Done in master, screenshot below.  @amanda-phet please review, close if this looks OK.

<img width="567" alt="screenshot_487" src="https://user-images.githubusercontent.com/3046552/90298384-59e23100-de4f-11ea-908b-3d158490597e.png">

**Comment by pixelzoom** [comment]
Whoops, closed accidentally.

**Comment by amanda-phet** [comment]
Looks good. Thanks for the suggestions.
