### ISSUE TITLE
add more shrubs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#176]
At 8/13/2020 design meeting, I suggested adding more shrubs, to make food look more abundant when the "Limited Food" checkbox is not checked.   It's easy to do, so I'll take a shot at this, and we can adjust from there.

**Comment by amanda-phet** [comment]
Thanks for taking a stab at it. I trust you will find a nice arrangement for the shrubs :)

**Comment by pixelzoom** [comment]
Ready for review by @amanda-phet.

Rather than attempting to guess at people's opinions (or even mine!) about number of shrubs, and come up with lots more fixed positions for shrubs, here's what I did:

* I added query parameter `shrubsRange=min,max` to specify the number of shrubs, where min is for limited food and max is for abundant food.  The default is `shrubsRange=10,75`.   I like this default - it looks really fun to me (see screenshot below) and very clearly communicates "limited food".   Let me know what values you like.  And we might want to decide this after deciding how the limited-food model is going to change in #169.

* Shrub positions are generated randomly.  We have 3 choices here: 
(1) generate new positions for each screen every time the sim loads
(2) use a different random seed for each screen to get the same positions each time the sim loads
(3) use the same random seed for both screens to get the same positions each time the sim loads

I'm not a fan of option (1).  There will be some random layouts that are not aesthetically pleasing. Each Shrub must be instrumented, and they will appear in Studio under `model.food.shrubs` and `shrub1`, `shrub2`, etc.  And because they're instrumented, it increases the memory footprint of the sim.

Option (2) is a little more complicated, using a different seed for each screen.  And I don't see the point in having different shrub positions for the 2 screens.

So I recommend (3).  We'll need to set a fixed seed for the random number generator. First, decide on what values to use for `shrubsRange`.  Then run the sim with `?log`, and repeatedly load the sim until you get a layout of shrubs that you like. Note the 2 log messages that looks like, which identity the seed:

`75 shrubs randomly placed using seed 0.720921556036829`

<img width="967" alt="screenshot_489" src="https://user-images.githubusercontent.com/3046552/90450701-86908580-e0a7-11ea-8387-e913905fa44f.png">

**Comment by pixelzoom** [comment]
I'm going to mark this as blocking the prototype publication.  I think that our new model for limited food (#183) will feel much better with more shrubs.  And I'm not sure if the current default (`shrubsRange=10,75`) is acceptable for the prototype.

**Comment by amanda-phet** [comment]
I think `shrubsRange=10,75` is the right range. I tried a few different ranges and that just seemed to work well!

`75 shrubs randomly placed using seed 0.3183031889262133` looks good to me.

![image](https://user-images.githubusercontent.com/7852916/90816050-e033c280-e2e8-11ea-8c28-1bf9d8bd7799.png)

![image](https://user-images.githubusercontent.com/7852916/90816242-2e48c600-e2e9-11ea-9737-7b3fa23bab53.png)

**Comment by amanda-phet** [comment]
Since I couldn't see tough food with the above seed (since it was used in the intro screen), I wanted to provide more options here. I also like this one. 

`75 shrubs randomly placed using seed 0.5853265884696416` 
![image](https://user-images.githubusercontent.com/7852916/90816563-b3cc7600-e2e9-11ea-96dc-5d3c564c777e.png)

![image](https://user-images.githubusercontent.com/7852916/90816583-bdee7480-e2e9-11ea-9e63-b2dd130896d5.png)

![image](https://user-images.githubusercontent.com/7852916/90816602-c8a90980-e2e9-11ea-8fd9-0571f2e782c1.png)

**Comment by amanda-phet** [comment]
@pixelzoom please go ahead and implement the seed in my most recent comment.

**Comment by pixelzoom** [comment]
Seed `0.5853265884696416` is used for both screens in the above commit.  PhET-iO instrumentation of shrubs is no longer necessary and has been removed.

@amanda-phet please review in master.

**Comment by amanda-phet** [comment]
Looks great to me. 

This is a strange ask.. but would it be difficult to use a different seed for the first screen? I wonder if it might be nice to see different plants on the two screens to make them feel more distinctive (since they both use the same background color and have mostly the same controls).

**Comment by pixelzoom** [comment]
It's relatively easy to use a different seed for each screen.   Use [1.1.0-dev.8](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.8/phet/natural-selection_en_phet.html) to find another layout that you like, and let me know what the seed is.  Please include a screenshot too, so that I can verify that the seed matches the visual.

**Comment by amanda-phet** [comment]
OK now I want two different ones! Here are my picks: 

For Intro screen, `75 shrubs randomly placed using seed 0.5286575215756223`
<img width="797" alt="image" src="https://user-images.githubusercontent.com/7852916/91344816-b886a380-e79b-11ea-8bed-5937b5316d5a.png">

Limited food:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/7852916/91344877-c9371980-e79b-11ea-8ae8-8efc19435bcf.png">


For Lab screen, `75 shrubs randomly placed using seed 0.9578375636205664`
<img width="795" alt="image" src="https://user-images.githubusercontent.com/7852916/91345025-fdaad580-e79b-11ea-98db-12e23811ad9e.png">

Limited food:
<img width="795" alt="image" src="https://user-images.githubusercontent.com/7852916/91345053-08656a80-e79c-11ea-963f-3a6e01b39a30.png">

Tough food:
<img width="797" alt="image" src="https://user-images.githubusercontent.com/7852916/91345171-32b72800-e79c-11ea-8ba6-e58e9ba52f36.png">


Thanks @pixelzoom ! I think it will look nice to have a different scenery on both screens.

**Comment by pixelzoom** [comment]
New seeds in the above commit. @amanda-phet please verify on phettest.

**Comment by amanda-phet** [comment]
I like them both! Thank you! Do you want to wait to close this since it's not in a dev version yet?

**Comment by pixelzoom** [comment]
I'm fine with closing it now.  For posterity, it will appear in dev versions >= 1.1.0-dev.16.
