### ISSUE TITLE
press and hold the fast-forward button was not discovered

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#179]
In interviews, students did not discover that they could press and hold the fast-forward button.  Perhaps we should switch to Fast/Normal radio buttons? Let's discuss.

**Comment by pixelzoom** [comment]
8/18/2020 design meeting:

I'll create a dev version that uses TimeControlNode with "Fast" and "Normal" radio buttons.  So that team can play around with it.

**Comment by pixelzoom** [comment]
While working on this, I realized that there's no reason why NS shouldn't be using the same model as sims that use TimeControlNode.  That is: `{EnumerationProperty.<TimeSpeed> timeSpeedProperty`.  So  I have converted the model to `timeSpeedProperty` in the above commit.   It looks like this in Studio, and makes it trivial to switch between TimeControlNode and other time controls.

<img width="969" alt="screenshot_494" src="https://user-images.githubusercontent.com/3046552/90579159-61247a00-e182-11ea-8af5-2a90190481b3.png">

**Comment by pixelzoom** [comment]
TimeControlNode requires a step-forward button, and we don't have room for one.  So I had to add an option to TimeControlNode to make it optional, similar to the option for TimeControlNode's step-backward button.

**Comment by pixelzoom** [comment]
This unfortunately turned into a lot of work that I couldn't foresee until I was way into it.  Model changes, PhET-iO changes, enhancements to TimeControlNode.... 

[1.1.0-dev.10](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.10/phet/natural-selection_en_phet.html) has the press-and-hold fast-forward button.

[1.1.0-dev.11](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.11/phet/natural-selection_en_phet.html) uses the common-code TimeControlNode.

@amanda-phet @kathy-phet @ariel-phet @oliver-phet please test drive.  I think that TimeControlNode is a step backward in both usability and aesthetics.

**Comment by pixelzoom** [comment]
I'm also wondering if the "Normal" and "Fast" buttons set up an expectation that _everytime_ (including motion of bunnies and wolves) will move faster.  We very deliberately made the fast-forward button apply to the generation clock, and not motion.

**Comment by amanda-phet** [comment]
>TimeControlNode requires a step-forward button, and we don't have room for one. So I had to add an option to TimeControlNode to make it optional, similar to the option for TimeControlNode's step-backward button.

I vaguely remember having this discussion way back when we made the custom FF button. Sorry that ended up being extra common code work! 

I can see benefits to both versions. I played with both for a while (so many other fun new things to play with!) and noticed that in 1.1.0-dev.11 I often left it in "Fast" mode, because why not. I'm not sure if that's a problem, but once I had it in fast I didn't see a reason to slow down... Maybe we can make the generation time length slightly shorter (it's something like 10 right now, right? if we stick with the FF button, maybe we could put it down to 8.) 

@kathy-phet please give both a spin!

**Comment by amanda-phet** [comment]
8/20/20 design meeting: 

This work led to a better PhET-iO interface and model change, but we'd still like to keep the FF-button (not the radio buttons).  Over to @pixelzoom to finalize the code.

**Comment by pixelzoom** [comment]
Cleanup is done. Closing.

**Comment by pixelzoom** [comment]
Just to document some reasons why we went with the FF button...

* If student don't find it, it doesn't compromise usability or learning goals.
* In a classroom, someone is likely to find it and spread the word.
* We can describe the FF button in Teacher Tips (noted in #195)
* Students are apt to leave the sim sim in "Fast" mode, which has more problems.
