### ISSUE TITLE
Proportion: how to display small percentages

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#18]
For the Proportion view, we have some decisions to make about how to present percentages that are < 1%.

As an example for discussion, suppose we have 900 bunnies and only 1 of them has long teeth, resulting in “Teeth” proportions of 99.9% short and 0.1% long.

First, there's the question of what percentage value to display.  We’re currently showing percentages rounded to the nearest integer, so this would be presented as 100% short and 0% long.  This is inaccurate and (because the bunnies are visible) potentially confusing.

Options:
(a) do nothing
(b) add 1 decimal place and display as 99.9% and 0.1%
(c) display as "> 99%" and “< 1%”
(d) ???

Second, there's the problem of how much of the bar to display. The bars are currently 120 pixels wide. 1% is only 1.2 pixels wide.  A value like 0.1% would only be 0.1 pixels wide. 

Options:
(a) do nothing
(b) display a minimum bar width for all values <= N%
(c) ???

Examples with a minimum bar width of 1%:

<img width="157" alt="screenshot_1712" src="https://user-images.githubusercontent.com/3046552/69586261-42040d80-0f9f-11ea-80f1-7291c77379fe.png">
<img width="153" alt="screenshot_1717" src="https://user-images.githubusercontent.com/3046552/69586292-61029f80-0f9f-11ea-85e4-e4bb6be9fc72.png">

<img width="158" alt="screenshot_1711" src="https://user-images.githubusercontent.com/3046552/69586237-27319900-0f9f-11ea-9438-205ee85a532a.png">

<img width="152" alt="screenshot_1716" src="https://user-images.githubusercontent.com/3046552/69586233-20a32180-0f9f-11ea-8b54-a6b1af0340b7.png">

With "Values" unchecked (the default) the 1% bars are difficult to see. We’ll have to keep this in mind when deciding the fate of the “Values” checkbox in #14.

<img width="136" alt="screenshot_1709" src="https://user-images.githubusercontent.com/3046552/69586395-b2129380-0f9f-11ea-8518-317dc5d7aefd.png">
<img width="136" alt="screenshot_1718" src="https://user-images.githubusercontent.com/3046552/69586396-b3dc5700-0f9f-11ea-8e2f-2463800f95f2.png">

**Comment by pixelzoom** [comment]
So that I can move forward, I've implemented this approach:

<img width="143" alt="screenshot_1719" src="https://user-images.githubusercontent.com/3046552/69592692-fad44780-0fb3-11ea-82c0-4c029f9b82ad.png">

Note that the percentage values can't extend past the left or right edge of the bar, because that would cause layout problems and possible overlapping with adjacent bars.

**Comment by amanda-phet** [comment]
I think this direction is looking great @pixelzoom . Thinking about the edge case of 1% (or < 1%) I am thinking that for #13 we should probably never have the option to hide values. Let's plan to discuss this at the next design meeting on 12/12/19.

**Comment by pixelzoom** [comment]
12/12/19 design meeting:

We're good with this approach. Closing.
