### ISSUE TITLE
Feature PhET-iO elements

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#180]
When completing #5  we identified elements that should be featured (and some that should not be featured).

**Comment by amanda-phet** [comment]
Questions to discuss with @arouinfar :

1. Should we feature xRangeProperty and yRangeProperty? Not sure it is useful for someone to know what the domain and range of the graph are that a student is viewing.
2. Featuring `naturalSelection.labScreen.model.graphs.proportionsModel.previousCounts` seems like a similar question. Are we anting to feature things that demonstrate how a student is navigating around in the graphs? 
3. Should we feature dialogs? 
4. The checkbox labels above the earsColumn, furColumn, and teethColumn are read-only and featured. Guessing they is read-only because it is an important label for the data, so it should not be featured.
5. Should we feature the generation spinner on the proportions graph? `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.generationSpinner.visibleProperty` Seems like we should not, but wanted to check in.

**Comment by pixelzoom** [comment]
The only one of the above questions that deals with something other than "featured" is:
> 4. The checkbox labels above the earsColumn, furColumn, and teethColumn are read-only and featured. Guessing they is read-only because it is an important label for the data, so it should not be featured.

There's no technical reason why these checkboxes need to be read-only.  The checkbox itself is currently `phetioReadOnly: true`, which makes all of its child elements read-only.

**Comment by amanda-phet** [comment]
8/20/20 Discussion

1. No, we don't need to feature these.
2. Each element in that array is the counts for that generation. This seems like data someone might pull into a wrapper. Leaning towards featuring `naturalSelection.labScreen.model.graphs.proportionsModel.previousCounts`. Perhaps we should put some documentation about ObservableArray into the general PhET-iO guide, not the sim-specific one. @kathy-phet will draft something to edit the description of this element. In the NS client guide, give an example about when you might use this. 
3. These could be useful for knowing whether the bunnies all died or took over the world. @pixelzoom said: There are emitters that let you know if the bunnies all died or took over the world- should we instrument those? He will connect with someone on the PhET-iO team about it. `memoryLimitDialog` doesn't seem as useful as `diedDialog` and `worldDialog`, but @pixelzoom will still put an emitter in for it. 
4. Since these are doing double-duty as a label for the column, we don't want clients to be able to hide them. However, @pixelzoom will make them readOnly: false. 
5. Seems like a bad idea to feature `generationSpinner.visibleProperty`. But OK to leave available for instructional designers if they want to toggle it.

**Comment by pixelzoom** [comment]
I've created separate issues (see above) for all of the things that I need to do.  So @amanda-phet you can close this issue when your tasks are completed.

**Comment by amanda-phet** [comment]
Featured list is complete. 

There are some questions though, for anyone interested in weighing in (unless I can discuss with @kathy-phet Tuesday morning). 

1. There are some elements that exist in the Intro screen that I assume we don't want to feature, such as `naturalSelection.labScreen.model.food.isToughProperty` or anything related to `ears` or `teeth`. Is this correct? (@kathy-phet , @pixelzoom , or @ariel-phet ) 
2. Since there is only one allele present in the Intro screen (fur), there are instances when it doesn't make sense to me to feature an element that we did in the Lab screen. For example, if someone chooses to make `naturalSelection.introScreen.view.graphs.pedigreeNode.allelesPanel.furRow.visibleProperty` false, then the Alleles panel will have nothing in it. We are already featuring `naturalSelection.labScreen.view.graphs.pedigreeNode.allelesPanel.visibleProperty`, so does it really make sense to feature this row as well? There are a few instances like this, and it's a bit related to (1) above. So an overall discussion here would be nice. 

@kathy-phet assigning to you to review if you are able to, but I'm thinking we can review this together Tuesday morning.

**Comment by amanda-phet** [comment]
9/15/20 discussion with @kathy-phet : 

I will go ahead and feature elements relating to ears, teeth, and tough food on the Intro screen so it's parallel to the lab screen.

**Comment by pixelzoom** [comment]
Sorry, I didn't see the mention in https://github.com/phetsims/natural-selection/issues/180#issuecomment-691341669 (always best to assign to me if you want input).

Re 1:  Up to you whether you want to feature elements (genes, environmental factors) the same for Intro and Lab screen, or only feature the elements that are by default included in the Intro screen. 

Re 2: I don't recommend featuring _any_ gene-related or allele-related UI components (like rows in panels). The Properties under `view.genes` are preferred because they will uniformly handle the visibility of all UI components related to a gene.

**Comment by amanda-phet** [comment]
@pixelzoom said:

>Re 2: I don't recommend featuring any gene-related or allele-related UI components (like rows in panels). The Properties under view.genes are preferred because they will uniformly handle the visibility of all UI components related to a gene. If the goal is to show/hide a gene in a screen, then the design should be using view.genes, not setting the visibility of individual UI components (as noted in the Client Guide).

@kathy-phet what are your thoughts about this? Also assigning this to you in case you will be able to review this by tomorrow. If not we'll proceed as -is.

**Comment by pixelzoom** [comment]
@amanda-phet can you clarify what "as is" means? Does that mean featuring `visibleProperty` for individual UI components related to genes?  If the 10/1 RC will be used by instructional designers, we should emphasize `view.genes` (by featuring those Properties), not emphasize `visibileProperty` individual UI components.   As noted in the Client Guide: set `view.genes` Properties first, then set `visibileProperty` individual UI components only if there's some special need.

**Comment by amanda-phet** [comment]
That is correct. We put the note in the client guide, and my understanding of how we're featuring items in studio is that we want to be consistent with other sims and consistent with general UI components. Visibility of nodes is standard. I am 100% ok not featuring those if @kathy-phet wants to go that route, though.

**Comment by pixelzoom** [comment]
I see that `view.gene.*` Properties are featured, so at least they are on equal footing with `visibleProperty`.

**Comment by kathy-phet** [comment]
When Amanda and I discussed, we thought of scenarios where you would want to do micro-customizations and not just use the convient vew.gene.* .... and for consistency of how PhET-iO works across sims, it seemed like the right thing to do to make checkbox visibility and such still available as featured. And then direct clients with recommendations in the client guide.

**Comment by pixelzoom** [comment]
OK. That sounds like "leave as is".   So closing  If I have that wrong, please reopen asap, because I'll be creating the 1.2 release branch this morning.
