### ISSUE TITLE
Dynamic layout bug in Proportions graph

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#182]
Found when completing #5 

When I toggle `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.generationSpinner.visibleProperty` in studio, the layout of the proportions graph gets really funky.

**Comment by pixelzoom** [comment]
Reproduced in master.

1. Start the sim in Studio
2. Go to Lab screen
3. Press "Add a Mate" button
4. Toggle `generationSpinner.visibleProperty` off then on.  See screenshot below.

<img width="968" alt="screenshot_491" src="https://user-images.githubusercontent.com/3046552/90553782-2c003380-e152-11ea-8720-db14a47c4ed8.png">

**Comment by pixelzoom** [comment]
The standard way of keeping a Node centered is to listen to its layoutBoundProperty.  In this case in PopulationGraphNode.js, we keep the graph's content centered on its  background like this:

```js
    // Center content on the background. Columns or generationSpinner may be hidden via PhET-iO. unlink is not necessary.
    content.localBoundsProperty.link( () => {
      content.center = backgroundNode.center;
    } );
```

@jonathanolson and I investigated this together on Zoom, and discovered that there's a general problem with bounds computation in scenery's Node.js.  It wasn't obvious what the best way to address it is, so @jonathanolson is going to create a scenery issue, link it to this issue, and investigate.

**Comment by pixelzoom** [comment]
This issue is not blocking for the prototype, because it only manifests when changing `generationSpinner.visibleProperty` via PhET-iO or Studio.

**Comment by pixelzoom** [comment]
On hold until phetsims/scenery#1071 is addressed.

**Comment by pixelzoom** [comment]
@jonathanolson added a workaround for this in https://github.com/phetsims/scenery/commit/414d42199d1e05b7d6d556462e908b006e623033.  So this specific problem is resolved and this issue can be closed.  The general problem is still unresolved, tracking in phetsims/scenery#1071.

@amanda-phet please verify in master.

**Comment by pixelzoom** [comment]
@ariel-phet please review this one.  Steps to verify are in https://github.com/phetsims/natural-selection/issues/182#issuecomment-675655268.

**Comment by pixelzoom** [comment]
@amanda-phet it looks like @ariel-phet has gotten busy, so assigning to you too.  Whichever one of you gets to this first...

**Comment by amanda-phet** [comment]
I think I reviewed this a while ago, but just checked again now and it look great.
