### ISSUE TITLE
recessive mutations should not be favored by environmental factors

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#184]
This came up in the context of https://github.com/phetsims/natural-selection/issues/183, revising the Food model.

Recessive mutants are currently excluded from application of environmental factors. This can lead to incorrect conclusions, and odd behavior if recessive mutants are the sole remaining bunnies. 

@amanda-phet and I discussed on Zoom, and decided that this behavior is incorrect. Recessive mutants can be favored during mating, to make them appear in the phenotype more quickly. But they should not be favored during selection. 

I will change this. If we discover that it causes other problem, we can revisit, and it's relatively easy to revert.

**Comment by pixelzoom** [comment]
Addressed in the above commits by changing the implementation of BunnyCollection `getSelectionCandidates`. It now returns the complete set of live bunnies, in random order.

**Comment by pixelzoom** [comment]
@amanda-phet this is ready for review.  Unfortunately there's nothing specific to review -- just apply recessive mutations and environmental factors together, and be on the lookout for any undesirable behavior.  You can review in master or [1.1.0-dev.9](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.9/phet/natural-selection_en_phet.html).

**Comment by amanda-phet** [comment]
Played with this for a bit and I don't see any undesirable behaviors. It seems like recessive and dominant mutants are just as likely to be killed as other bunnies.
