### ISSUE TITLE
rename Properties related to time and generations

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#187]
Preparing for code review. This is an internal code issue, and has no implications for the UI.  It will affect the PhET-iO API.

There are a confusing number of Properties in the code that have "time" and "generation" in their names, including:

```
GenerationClock.timeProperty - decimal
GenerationClock.generationsProperty - decimal
GenerationClock.currentGenerationProperty - integer
GenerationClock.percentTimeProperty - decimal

PopulationModel.generationsProperty (reference to GenerationClock.generationsProperty)
DataProbe.generationProperty - decimal, x-position of the probe

ProportionsModel.generationProperty - integer, the generation displayed
ProportionsModel.currentGenerationProperty (reference to GenerationClock.generationsProperty)
ProportionsModel.isDisplayingCurrentGenerationProperty - is the graph displaying
```

What's confusing is:
* whether the value is an integer or decimal
* whether the value pertains to the clock or something else

What needs to be communicated is:

The generation clock has 4 quantities related to time:
* the time in seconds (a decimal)
* the time in generations (a decimal)
* the percentage of the clock cycle that has elapsed (a decimal, not instrumented)
* the current generation (an integer)

The Population graph has 3 quantities relates to time:
* the current time in generations (a decimal), same as generation clock
* the generation range (integer) that is displayed by the graph
* the position of the data probe (decimal)

The Proportions graph has 2 quantities related to time:
* the current time in generations (a decimal), same as generation clock
* the generation (integer) whose data is displayed by the graph

I'm going to clean this up. It will undoubtedly result in changing some phetioIDs, which I'll have @amanda-phet review when I'm done.

**Comment by pixelzoom** [comment]
I'm really glad that I did this.  The code is now much easier to understand.  

Here are the changes to phetioIDs, with their documentation. Red is old value, green is new value.  

```diff
- naturalSelection.introScreen.model.generationClock.timeProperty
+ naturalSelection.introScreen.model.generationClock.timeInSecondsProperty
+ phetioDocumentation: 'time that the generation clock has been running, in seconds (decimal)',

- naturalSelection.introScreen.model.generationClock.generationsProperty
+ naturalSelection.introScreen.model.generationClock.timeInGenerationsProperty
+ phetioDocumentation: 'time that the generation clock has been running, in generations (decimal)',

- naturalSelection.introScreen.model.generationClock.currentGenerationProperty
+ naturalSelection.introScreen.model.generationClock.clockGenerationProperty
+ phetioDocumentation: 'generation number of the current cycle of the generation clock (integer)'

- naturalSelection.introScreen.model.graphs.populationModel.dataProbe.generationProperty
+ naturalSelection.introScreen.model.graphs.populationModel.dataProbe.dataProbeGenerationProperty
+ phetioDocumentation: 'the generation (x-axis) value where the data probe is positioned (decimal)'

- naturalSelection.introScreen.model.graphs.proportionsModel.generationProperty
+ naturalSelection.introScreen.model.graphs.proportionsModel.proportionsGenerationProperty
+ phetioDocumentation: 'the generation whose data is displayed by the Proportions graph (integer)'
```

Notes about the above:
* The names of "generation" Properties are now clearly qualified: i.e.`clockGenerationProperty`, `dataProbeGenerationProperty`, `proportionsModelGenerationProperty`.
* Documentation indicates whether a value is integer or decimal. This was a potential source of confusion in the code, and seemed like it would also be good to qualify here.
* It's not strictly necessary to instrument `generationClock.timeInGenerationsProperty` since it's a derived Property. If you don't think it's necessary to show in Studio or the data stream, let me know and I'll un-instrument it.

@amanda-phet please review the phetioIDs and documentation to verify that they look OK to you.

**Comment by amanda-phet** [comment]
These all look like great changes! I agree that sometimes it took a second to realize what you were looking at, although I did still figure it out. We were planning to feature `generationClock.timeInGenerationsProperty`(previously `generationsProperty`) and allow the user to derive the integer generation if they wanted. What do you mean it's a derived property? What is it derived from?

**Comment by pixelzoom** [comment]
>  ... What do you mean it's a derived property? What is it derived from?

A DerivedProperty is a Property whose value is wholly derived from one or more other Properties. In this case, 
`generationClock.timeInGenerationsProperty` is derived from `generationClock.timeInSecondsProperty`:

`timeInGenerations = timeInSeconds / secondsPerGeneration`

**Comment by pixelzoom** [comment]
> We were planning to feature `generationClock.timeInGenerationsProperty` (previously generationsProperty) and allow the user to derive the integer generation if they wanted

I'm not sure what you mean here. The user doesn't need to derive the integer generation, it's already derived (and instrumented) as `generationClock.clockGenerationProperty`.

**Comment by amanda-phet** [comment]
We were thinking of only featuring the decimal version (`timeInGenerationsProprty`) and if the user wants the integer version, they can figure it out. It wouldn't be a big deal to just feature both, but it seemed redundant to feature both. I still think both should be instrumented!

And thanks for clarifying. I do understand what a derived property is, but didn't realize it was simply derived from timeInSeconds in this case (which makes sense). 

I would like to leave all of these instrumented. The PhET-iO IDs and descriptions look good to me.
