### ISSUE TITLE
credits in images/license.json

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#19]
I'm not clear on who should be credited with which images, and there are some TODO items in license.json for images that were copied from the Java version.  We'll need to sort this out before 1.0.0 publication.

The license file is https://github.com/phetsims/natural-selection/blob/master/images/license.json.

**Comment by pixelzoom** [comment]
@amanda-phet I'm not anticipating any additional images for this sim, so you can review license.json at any time.  I suspect that you may need to adjust the "create by" attributions. Feel free to modify directly via GitHub web interface.  The URL for license.json is shown above.

**Comment by amanda-phet** [comment]
I adjusted a few attributions and the rest look good.
