### ISSUE TITLE
performance sign-off

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#191]
This is listed as a "standard GitHub issue" in the code-review checklist.  The lead designer must sign off on performance.

**Comment by pixelzoom** [comment]
@amanda-phet this is ready for review. The screenshot below shows pointer areas for the _Lab_ screen, _Intro_ screen is identical.

Uniform width for checkbox pointer areas is not supported by common-code, and imo not desirable. I also don't think it's desirable to have uniform widths for radio buttons, but we're currently stuck with that in common-code. 

<img width="1087" alt="screenshot_498" src="https://user-images.githubusercontent.com/3046552/90713643-06af1a80-e263-11ea-87f6-58a4f86e7efe.png">

**Comment by pixelzoom** [comment]
#60 and #140 are the 2 cases that were performance concerns. A lot of work was done to improve PhET-iO performance, and it now feels acceptable to me.  So over to @amanda-phet for performance sign-off.  I'm not quite sure how sign-off is going to work without access to PhET's test devices.  Let me know if you want to discuss.

**Comment by amanda-phet** [comment]
@ariel-phet Can you also help sign off on this one? I've read the performance issues and commented, and if @pixelzoom thinks it's acceptable then I'm inclined to accept the current performance status. #140 is a little bit of a usability issue combined with performance, and #60 seems fine to me.

**Comment by amanda-phet** [comment]
Oops, #166 is the usability issue. They are so similar I confused them.

**Comment by ariel-phet** [comment]
Looked over the issues, I think all is in a good place (certainly for PhET brand). It sounds like @pixelzoom has some thoughts for potential optimizations as this sim gets moved towards the iO dev release, but I think even without those we would be in pretty solid shape. 

Signing off and closing.
