### ISSUE TITLE
pointer areas sign-off

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#192]
This is listed as a "standard GitHub issue" in the code-review checklist. The lead designer must sign off on pointer areas.

**Comment by pixelzoom** [comment]
@amanda-phet this is ready for review. The screenshot below shows pointer areas for the _Lab_ screen, _Intro_ screen is identical.  Not shown are the Proportions and Pedigree graphs.

Note that the checkboxes in the Population panel do not have uniform width. I'll make them uniform if you want.  But unlike radio buttons, there's no support in common code. And imo, uniform width is not desirable for checkboxes or radio buttons.

<img width="1087" alt="screenshot_498" src="https://user-images.githubusercontent.com/3046552/90713643-06af1a80-e263-11ea-87f6-58a4f86e7efe.png">

**Comment by pixelzoom** [comment]
@ariel-phet and I discussed the Population panel. I'll make all of the checkboxes the same width.  It'll probably work out better for focus traversal.

**Comment by pixelzoom** [comment]
Population checkbox touch areas have been expanded, see screenshot below.  Proportions checkbox has not - there's only one, so nothing to expand to match.   I'd have to do something evil, like add an invisible horizontal strut, to make that one fill the control panel.

@ariel-phet please review in master.

<img width="907" alt="screenshot_521" src="https://user-images.githubusercontent.com/3046552/91236771-1d87be00-e6f6-11ea-8965-88c6bd600b37.png">

**Comment by pixelzoom** [comment]
Hold off on reviewing. Making the Population checkboxes all have the same size created a new problem, https://github.com/phetsims/natural-selection/issues/207.  So I'm going to have to come up with a different way of doing this.

**Comment by pixelzoom** [comment]
Fixed in the above commit. You may resume reviewing.

**Comment by pixelzoom** [comment]
@amanda-phet it looks like @ariel-phet has gotten busy, so assigning to you too.  Whichever one of you gets to this first...

**Comment by amanda-phet** [comment]
I think it all looks fine. 

I can't see the pointer areas for the Fur, Ears, and Teeth checkboxes on the Proportions screen. When I try to discern them with my cursor, they don't seem as roomy as the other checkboxes. It seems like I need to be right on the text or box, and not in a roomy rectangle around the text and box. 

@pixelzoom any way to confirm what those areas are, or expand them slightly?

**Comment by pixelzoom** [comment]
Good catch, addressed in the above commit. I've used the same dilation that's used for other checkboxes. See screenshot below. Back to @amanda-phet for review.

<img width="948" alt="screenshot_527" src="https://user-images.githubusercontent.com/3046552/91472730-1f1bc800-e855-11ea-999f-15f0395b3d01.png">

**Comment by amanda-phet** [comment]
Looks good. Thanks!

**Comment by pixelzoom** [comment]
Reopening. 

After testing on his phone, @ariel-phet has some requests.  Increase touchArea for these UI components:

Definitely:
* fast-forward button
* y-axis zoom buttons (asymmetric, common-code) 

Bonus:
* Generation arrow buttons below Population graph
* Generation arrow buttons below Proportions graph

We're not going to do these for the prototype RC.

**Comment by pixelzoom** [comment]
Here's a patch for the fast-forward button.  We thought that 6 looked like a good dilation.  But if we want the touchArea to be the same as the play button, the correct value is 4.  I'll discuss this with @ariel-phet later.

<details>
<summary>patch</summary>

```diff
Index: js/common/view/NaturalSelectionTimeControlNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/NaturalSelectionTimeControlNode.js	(revision 23f61b80837844e5347b912447f78e8ec6439491)
+++ js/common/view/NaturalSelectionTimeControlNode.js	(date 1598644626382)
@@ -19,6 +19,10 @@
 import naturalSelection from '../../naturalSelection.js';
 import FastForwardButton from './FastForwardButton.js';
 
+// constants
+const PLAY_BUTTON_RADIUS = 20;
+const FAST_FORWARD_BUTTON_RADIUS = 16;
+
 class NaturalSelectionTimeControlNode extends HBox {
 
   /**
@@ -40,12 +44,14 @@
     }, options );
 
     const playPauseButton = new PlayPauseButton( isPlayingProperty, {
-      radius: 20,
+      radius: PLAY_BUTTON_RADIUS,
       listener: () => fastForwardButton.interruptSubtreeInput(),
       tandem: options.tandem.createTandem( 'playPauseButton' )
     } );
 
     const fastForwardButton = new FastForwardButton( timeSpeedProperty, {
+      radius: FAST_FORWARD_BUTTON_RADIUS,
+      touchAreaDilation: PLAY_BUTTON_RADIUS - FAST_FORWARD_BUTTON_RADIUS,
       tandem: options.tandem.createTandem( 'fastForwardButton' )
     } );
 ```

</details>

**Comment by pixelzoom** [comment]
For this one:

> - [ ] Generation arrow buttons below Proportions graph (NumberSpinner)

I discovered that `NumberSpinner` has no way to dilate the pointer areas for its arrow buttons.  Doing that properly involves adding nested options arrowButtonOptions to NumberSpinner, and fixing up every place where NumberSpinner is used.  It will take at least 2 hours. @ariel-phet Do you want me to tackle that?

**Comment by pixelzoom** [comment]
I've noticed that for the sim-specific dialogs, the close button feels a little finicky for me on iPad.  Since there are no UI components in these dialogs, there's no reason that we can't make their close buttons have generous pointer areas.  So I've done that, they are all the same size, and they look like this:

<img width="553" alt="screenshot_537" src="https://user-images.githubusercontent.com/3046552/91909515-9b097c00-ec6a-11ea-851d-5e7e19a2c2b9.png">
<img width="358" alt="screenshot_536" src="https://user-images.githubusercontent.com/3046552/91909526-a197f380-ec6a-11ea-83df-bc0f9ec5dfff.png">
<img width="692" alt="screenshot_535" src="https://user-images.githubusercontent.com/3046552/91909535-a3fa4d80-ec6a-11ea-89b6-08f331a5b6da.png">

**Comment by pixelzoom** [comment]
All requests have been completed.  Most of them are shown in the first screenshot below. Generations below the Proportions graph is shown in the second screenshot.   See also the screenshots in the previous comment related to Dialog close buttons.

@ariel-phet please verify in master, and feel free to close.

<img width="1127" alt="screenshot_538" src="https://user-images.githubusercontent.com/3046552/91910885-179d5a00-ec6d-11ea-8efb-78017c718a97.png">
<img width="1126" alt="screenshot_539" src="https://user-images.githubusercontent.com/3046552/91910897-1c620e00-ec6d-11ea-822d-b9230b98dece.png">

**Comment by ariel-phet** [comment]
Played on my phone and the few previous problem areas were much more usable. Closing.
