### ISSUE TITLE
Teacher Tips

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#195]
This issue is for collecting things that could be in Teacher Tips.

**Comment by pixelzoom** [comment]
Questions from the PhET-iO client, with @kathy-phet's responses, which might might be appropriate for Teacher Tips:

Q: For the pedigree, I've typically taught students to write the dominant allele first. Some of the bunnies had them listed first but others second. I was just wondering why that was.
A: This is always written as allele from the left bunny and then the right bunny - so you can track what is coming from what. In the code it uses mother and father terminology, but for the purposes of the chart its just left and right.
@pixelzoom note: There's a more complete description of the genotype abbreviation convention in the [Genotype and Phenotype section of model.md](https://github.com/phetsims/natural-selection/blob/master/doc/model.md#genotype-and-phenotype).

Q: I love how the floppy-ear mutation showcases a dominant trait that isn't prevalent in the population! It's a great way to address a common student misconception. Is there a scenario where floppy-eared bunnies are advantageous? I was just wondering because I tried many different scenarios but couldn't find one where floppy-eared bunnies took over.
A: Your observation is correct, there are no situations in which floppy ears are advantageous. And that is purposeful for the pedagogical reasons you mention. :)

**Comment by amanda-phet** [comment]
From the design doc:

Model simplification: limited food does not select for a specific gene or genotype. 
Query parameter: startup population (issue #9), must be less than 1000 bunnies! 
Query parameter: hide alleles

**Comment by pixelzoom** [comment]
> Query parameter: startup population (issue #9), must be less than 1000 bunnies!

We lowered this to 750.  See query parameter `maxPopulation`.

**Comment by pixelzoom** [comment]
Note the the fast-forward button is press-and-hold.

**Comment by pixelzoom** [comment]
Info about the public query parameters might be relevant to Teach Tips.

**Comment by pixelzoom** [comment]
Should Teacher Tips have a link to model.md, so they can find out how the model works, and what simplifications we've made?

**Comment by amanda-phet** [comment]
Teacher tips are complete and I will upload after https://github.com/phetsims/website/issues/1133 is resolved.
