### ISSUE TITLE
initial y-axis range for Population graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#196]
The initial y-axis range for the Population graph is [0,70].  Is that the best initial range fo the HTML5 version? (The initial range in the Java version was [0,50].)

For example... If I start by checking "Limited Food" and press "Add a Mate", all of the data points after generation 4 are > y=70, so "Zoom out to see data" is displayed.  In that case, [0,350] would be the best range.

**Comment by amanda-phet** [comment]
I don't see a problem with the data going off the scale in 4 generations. Especially since we have such helpful feedback about zooming out! 

If anything, I'd start more zoomed in so it's easier to see the data to start, but I think [0,70] is working just fine.
