### ISSUE TITLE
Revise PhET-iO documentation for proportionsModel.previousCounts

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#198]
From https://github.com/phetsims/natural-selection/issues/180

>  2. Featuring naturalSelection.labScreen.model.graphs.proportionsModel.previousCounts seems like a similar question. Are we wanting to feature things that demonstrate how a student is navigating around in the graphs?

> Each element in that array is the counts for that generation. This seems like data someone might pull into a wrapper. Leaning towards featuring `naturalSelection.labScreen.model.graphs.proportionsModel.previousCounts`. Perhaps we should put some documentation about ObservableArray into the general PhET-iO guide, not the sim-specific one. @kathy-phet will draft something to edit the description of this element. In the NS client guide, give an example about when you might use this.

**Comment by pixelzoom** [comment]
I made a minor improvement:

<img width="672" alt="screenshot_506" src="https://user-images.githubusercontent.com/3046552/90825358-09a71b00-e2f6-11ea-89f8-bb02bb1ff831.png">

@amanda-phet @kathy-phet let me know how you'd like to revise.  Reminder that `previousCounts` does not include counts for the current generation.  And let's try not to put too much general info about ObservableArray here, since it will be going away.

**Comment by amanda-phet** [comment]
That looks fine to me. 

@kathy-phet is that documentation ok?

**Comment by pixelzoom** [comment]
@amanda-phet assign to you again to followup with @kathy-phet in your meetings with her.

**Comment by pixelzoom** [comment]
At 9/3/2020 design meeting, @kathy-phet said that if @amanda-phet is OK with the doc, she has the power to make the decision.  So since @amanda-phet said "That looks fine to me", I'll close this issue.
