### ISSUE TITLE
Opt-out of default layout behavior for Proportions graph

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#199]
Dynamic layout issue with Proportions graph. Right now, if you hide the proportionsPanel, the proportionsGraphNode shifts over, but that doesn't seem to happen with populationGraphNode and pedigreeGraphNode. 

Please override the default layout behavior.

**Comment by amanda-phet** [comment]
#5

**Comment by pixelzoom** [comment]
Done in the above commit.  @amanda-phet please verify in master.  In Studio, navigate to `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsPanel.visibleProperty` and toggle it.

**Comment by pixelzoom** [comment]
You can also verify using https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.15/phet-io/, which was published this morning.

**Comment by amanda-phet** [comment]
Confirmed using https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.15/phet-io/wrappers/studio/. The toggle works and the layout looks good. Thanks!
