### ISSUE TITLE
revise 'Bunnies have taken over the world' image

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#20]
NOTE: You might want to wait on this until we're certain that the bunnies will not change (after we've seen them in context).

The image of bunnies taking over the world will need to be revised, using new bunnies.  I'm currently using the PNG file from the Java version. The HTML5 image file is [natural-selection/images/world.png](https://github.com/phetsims/natural-selection/blob/master/images/world.png).

<img width="571" alt="screenshot_13" src="https://user-images.githubusercontent.com/3046552/70162845-9d0ec200-167b-11ea-9a7a-2694c6af2925.png">

If you want to start with [the assets for the Java version](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/browse?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Fnatural-selection%2Fassets&commit=75095), you'll need [GIMP](https://www.gimp.org) to open the .xcf files. There are 3 .xcf files that look related, and I'm not sure which one you'll want to start with. (I don't have GIMP installed, so I can't open them.)

<img width="955" alt="screenshot_10" src="https://user-images.githubusercontent.com/3046552/70160140-3daeb300-1677-11ea-989f-9cffc049e9c9.png">

**Comment by pixelzoom** [comment]
Note that the dialog background is black. So you can either provide the image on a black or transparent background.

**Comment by amanda-phet** [comment]
I downloaded GIMP and opened the files. They are all sort of the same. The question I have is whether or not we want to use the same earth image or not. It's pretty blurry, so I'm sure we could find a better image. 

I see the options as: (1) use the original earth image (not sure of the source), (2) find a new earth image (with an appropriate license), or (3) ask ML to draw a "cartoon" image of the earth.

**Comment by pixelzoom** [comment]
I can't find any documentation in Unfuddle about where the earth image came from. @jonathanolson do you recall?

Whatever we decide to do, the "look" should be consistent with other graphics in the sim.  So if we go "cartoon image", it shouldn't too cartoony.

**Comment by pixelzoom** [comment]
1/16/20 design meeting:

Go with a realistic looking Earth like in Java sim, try to find an existing image with appropriate license. @amanda-phet will investigate.

**Comment by amanda-phet** [comment]
I think I found the original photo, and perhaps the original artist added an effect (in GIMP, which is basically photoshop) to make it intentionally look less detailed and more cartoony. 

https://www.pexels.com/search/earth/ (first result on this page.) 

I can try a quick mockup using this stock photo but we might want to use the "original" after all.

**Comment by pixelzoom** [comment]
This dialog is now live in master and [1.0.0-dev.31](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.31/phet/natural-selection_en_phet.html).  So I can use new artwork anytime that it's available.

**Comment by amanda-phet** [comment]
I believe this is done! Ready to export and commit, but just pasting it here in case anyone has feedback. I am not using the original earth because I don't know how to give it that "painted" effect and can't see how they did it in GIMP. But I can use that earth if we like it better than this real image. 

![image](https://user-images.githubusercontent.com/7852916/80751093-6a5fdd00-8ae6-11ea-9d82-c1f33fe786c9.png)

**Comment by pixelzoom** [comment]
The image shown in https://github.com/phetsims/natural-selection/issues/20#issuecomment-622057569 is now in master, if anyone wants to try it in context.  Compare to [1.0.0-dev.33](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.33/phet/natural-selection_en_phet.html).

**Comment by amanda-phet** [comment]
Thank you! This helped me find a few places to make tweaks (too dense, or strange layering). At such a small size, the bunnies don't layer as well as the original sim, likely due to the decreased stroke weight in the bunny artwork. I also notice this in the active sim, that the stroke weight around the bunnies is maybe a little too thin. That's a different issue but related because it would impact all the bunnies across the board.

**Comment by pixelzoom** [comment]
Latest artwork was integrated on 5/4/2020.

Labeling this for design meeting to see if this issue can be closed.

**Comment by pixelzoom** [comment]
5/7/2020 design meeting:

Everyone is happy with the way this looks.

Get earth image source URL and put in license.json.

**Comment by pixelzoom** [comment]
Here's the info that I added to license.json, @amanda-phet please verify and close.

```js
  "world.png": {
    "text": [
      "Copyright 2020 University of Colorado Boulder"
    ],
    "projectURL": "http://phet.colorado.edu",
    "license": "contact phethelp@colorado.edu",
    "notes": "created by Amanda McGarry, Earth image from https://www.pexels.com/photo/sky-earth-galaxy-universe-2422/ with Creative Commons Zero (CC0) license"
  }
```

**Comment by amanda-phet** [comment]
Looks good. Thanks.
