### ISSUE TITLE
Instrument Emitters that are related to dialogs

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#200]
From #180:

> 3. Should we feature dialogs?

> These could be useful for knowing whether the bunnies all died or took over the world. @pixelzoom said: There are emitters that let you know if the bunnies all died or took over the world- should we instrument those? He will connect with someone on the PhET-iO team about it. memoryLimitDialog doesn't seem as useful as diedDialog and worldDialog, but @pixelzoom will still put an emitter in for it.

So what we really want to know is when bunnies have died, taken over the world, or memory limit has been reached. We don't particularly care if the dialogs are showing.  And the best way to do this is to listen to the same Emitter that causes the dialog to open.

**Comment by pixelzoom** [comment]
I confirmed that clients can listen to an Emitter.  In Slack phet-io channel:

> Chris Malley  2:01 PM
> If an Emitter is instrumented, can iO clients get notifications from it?
> 
> Sam Reid  2:21 PM
> Yes, EmitterIO has an addListener method

The relevant Emitters are now instrumented. @amanda-phet please review in master. The phetioIDs are:

```
naturalSelection.labScreen.model.bunnyCollection.allBunniesHaveDiedEmitter
naturalSelection.labScreen.model.bunnyCollection.bunniesHaveTakenOverTheWorldEmitter
naturalSelection.labScreen.model.memoryLimitEmitter
```

Note that `memoryLimitEmitter` is not a sibling of the other 2 Emitters because BunnyCollection is not responsible for memory management -- that's the responsible of the top-level model.

**Comment by amanda-phet** [comment]
I confirmed the Emitters are instrumented. 

Can you share how the instructional designer would use these? I see that I can click "emit" but where is the listener? Is this something I need to document for clients? It's not obvious to me how to listen to these.

**Comment by pixelzoom** [comment]
The listener is not available in Studio.  A listener is  client-specific function, and it's added by the client, in client-specific code.  The client uses the `addListener` method for Emitter, as described in the API documentation for EmitterIO.  For example, here's the doc for `allBunniesHaveDiedEmitter`:

<img width="685" alt="screenshot_522" src="https://user-images.githubusercontent.com/3046552/91354549-22a64500-e7aa-11ea-9af6-8f76ab55043c.png">

Client-side code to add a listener to `allBunniesHaveDiedEmitter` would look like:

```js
client.invoke( 'naturalSelection.introScreen.model.bunnyCollection.allBunniesHaveDiedEmitter', 'addListener', [],
  () => { 
    // code to do something here
  } );
```

**Comment by pixelzoom** [comment]
This does bring up a good point though. We don't want the instructional designer pressing those "Emit" buttons in Studio, because it opens those dialogs in circumstances when they should most definitely not be visible.  I had not previously noticed these Emit buttons, and I'm wondering if we've been making sure that they are enabled/visible only when appropriate.

**Comment by pixelzoom** [comment]
In Slack phet-io channel:

> Chris Malley  2:49 PM
For Emitter elements, Studio shows an "Emit" push button.  How do I disable/remove that button for Emitters where it's not appropriate? `phetioReadOnly: true` ?
> 
> Sam Reid:house_with_garden:  3:22 PM
> Yes, `phetioReadOnly: true` sounds like the right way to shut that off

In the above commit, I made the 3 Emitters for this issue `phetioReadOnly: true`, and confirmed that their "Emit" push buttons are now disabled in Studio.

Back to @amanda-phet.

**Comment by amanda-phet** [comment]
I can confirm that these emit buttons are disabled.
