### ISSUE TITLE
Make column checkboxes readOnly: false in Proportions

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#201]
From #180:

> 4. The checkbox labels above the earsColumn, furColumn, and teethColumn are read-only and featured. Guessing they is read-only because it is an important label for the data, so it should not be featured.

> Since these are doing double-duty as a label for the column, we don't want clients to be able to hide them. However, @pixelzoom will make them readOnly: false.

**Comment by pixelzoom** [comment]
Done in the above commit. @amanda-phet please review in master.  In Studio, navigate to:

```
naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.earsColumn.checkbox
naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.furColumn.checkbox
naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.teethColumn.checkbox
```

**Comment by amanda-phet** [comment]
Confirmed. Thanks.
