### ISSUE TITLE
Add PhET-iO documentation for populationModel.dataPoints children

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#202]
The children of `naturalSelection.introScreen.model.graphs.populationModel.dataPoints.brownFurPoints` need `phetioDocumentation`:

<img width="187" alt="screenshot_503" src="https://user-images.githubusercontent.com/3046552/90823102-acf63100-e2f2-11ea-9dec-51616d0a26c0.png">

**Comment by pixelzoom** [comment]
I made a first pass at this, for example:

<img width="741" alt="screenshot_504" src="https://user-images.githubusercontent.com/3046552/90825056-a0270c80-e2f5-11ea-8202-7ed68ff0e931.png">

@amanda-phet @kathy-phet let me know how you'd like to revise.

**Comment by pixelzoom** [comment]
At 9/3/2020 design meeting, @kathy-phet said that if @amanda-phet is OK with the doc, she has the power to make the decision. So unassigning @kathy-phet.

**Comment by amanda-phet** [comment]
Looks fine to me.
