### ISSUE TITLE
Should multiple selection pressures lead to all bunnies dying? 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#204]
While working on #183 I thought about the following:

I think MH said it was ok (or preferred) that with multiple selection pressures, the entire population would die. I notice that when I get some brown long-tooth bunnies, they maintain perfectly stable (although it's a small population) and I'm not sure this is what we want. I will check with MH.

**Comment by pixelzoom** [comment]
MH replied in email on 8/23/20 (Subject: Natural Selection prototype is available!)

> As for selection pressures leading to equilibrium, that is the preferred outcome!  That is what happens in real life most of the time, so I’m glad that it happens in the sim as well.  If all of the bunnies eventually died, that evolutionary path would end. That happens, of course, but most lines go on.

**Comment by amanda-phet** [comment]
Thanks @pixelzoom for including her response here. 

Looks like all is fine here. Closing.
