### ISSUE TITLE
Intro screen - population panel isn't appropriately resizing

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#207]
I can confirm that this is new in https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.15/phet/natural-selection_en_phet.html. The panel is too large (tall). 

![image](https://user-images.githubusercontent.com/7852916/91351081-e91f0b00-e7a4-11ea-9aaa-dc7bbb514c6f.png)

Previously: 
![image](https://user-images.githubusercontent.com/7852916/91351154-0b188d80-e7a5-11ea-81b5-776a3ee97e38.png)

**Comment by pixelzoom** [comment]
Ah rats. This is cause by yesterday's change to pointer areas, see https://github.com/phetsims/natural-selection/issues/192#issuecomment-680313828.   We made all checkboxes in the panel have the same effective width. But that also means that even the invisible ones still have the same effective width, and the panel doesn't resize.  I'll have to change how #192 is implemented.

**Comment by pixelzoom** [comment]
Fixed in the above commit. @amanda-phet please verify on phettest.

**Comment by pixelzoom** [comment]
This block prototype publication. It's fixed, but needs to be reviewed.

**Comment by amanda-phet** [comment]
Looks fixed to me!
