### ISSUE TITLE
PhET-iO RC version for the client (1.2)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#208]
Deliver a QA-tested dev version (both brands) to the client, 10/1 current milestone.

Do this before code review #203 is completed, since that's not likely to be done until 9/10-ish.

There will be another dev test before going to RC testing.

Client guide ideally to be included #106.

**Comment by amanda-phet** [comment]
9/3/20 design meeting: 

**Ideal milestones:**

9/15 client guide done
9/17 1st dev test starts
9/23 1st dev tests ends 
*time for @pixelzoom to fix bugs
9/25-9/28 time for a 2nd dev test
9/29-9/30 review any changes 
10/1 deliver dev version to client 
10/7 or 10/15 client "slip it in" deadline

**What follows:**

code review completed 
Full dev test 
RC process 
Publish again to website and deliver final version to client

**Comment by pixelzoom** [comment]
9/10/2020 status meeting:

We decided to make this an RC, since we may need to patch.

**Comment by pixelzoom** [comment]
9/10/2020 design meeting:

When I created the QA issue for the RC:
* label as both "QA:rc" and "QA:rc-lite"
* prioritize PhET-iO testing

**Comment by amanda-phet** [comment]
Since #106 is complete, I think I can unassigned this issue. 

#180 still needs review, but I will finish that with @kathy-phet 9/15/20 at our standing meeting.

**Comment by pixelzoom** [comment]
9/17/2020:  RC 1.2.0-rc.1 was published, QA issue https://github.com/phetsims/QA/issues/551.

https://phet-dev.colorado.edu/html/natural-selection/1.2.0-rc.1/phet-io/
https://phet-dev.colorado.edu/html/natural-selection/1.2.0-rc.1/phet/natural-selection_en_phet.html

**Comment by pixelzoom** [comment]
9/25/2020:

RC 1.2.0-rc.2 was published, QA issue https://github.com/phetsims/QA/issues/557.

I published both brands, but RC testing will be for PhET-iO brand only.

https://phet-dev.colorado.edu/html/natural-selection/1.2.0-rc.2/phet-io/
https://phet-dev.colorado.edu/html/natural-selection/1.2.0-rc.2/phet/natural-selection_en_phet.html

**Comment by pixelzoom** [comment]
@kathy-phet 1.2 RC testing has been completed, and 1.2.0-rc.2 is acceptable for delivery to the customer.  The link is:

https://phet-dev.colorado.edu/html/natural-selection/1.2.0-rc.2/phet-io/

Please comment in this issue when this release has been delivered.

**Comment by pixelzoom** [comment]
According to @kathy-phet, this release has now evolved to where it will be "student facing', and she requested to have it published on phet-io.colorado.edu.

@kathy, Natural Selection 1.2.0 (phet-io) has been published at https://phet-io.colorado.edu/sims/natural-selection/1.2.0/.  If you want a record of this release, please add it to https://github.com/phetsims/phet-io/blob/master/doc/partners.md.

**Comment by kathy-phet** [comment]
This version has been delivered to the client. 
https://phet-io.colorado.edu/sims/natural-selection/1.2.0/
Thanks, Chris!

**Comment by kathy-phet** [comment]
Looks like it has been recorded to partners.md.

**Comment by pixelzoom** [comment]
Our work here is done! 🎉Closing.
