### ISSUE TITLE
how to implement charts?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#21]
@ariel-phet @kathy-phet @amanda-phet 

I’m implementing charts/graphs for Natural Selection. Population is an XY plot. Proportions involves bar charts.  Pedigree is a tree.

When I provided my evaluation and estimate for Natural Selection (email 6/4/12019, subject “Natural Selection?”), I said:

> My estimate will be based on implementing charts that are specific to this sim.  If PhET wants to investigate the general issue of charts, that will greatly increase my time estimate.

Ariel replied:

> I don't think Chris would need to make a general charting library, just expand on what has been done so far to meet the needs of this sim. I think Jesse has had to make some extensions for ESP, so I would see this as complimentary work.

I’ve looked at [griddle](https://github.com/phetsims/griddle) (PhET’s chart repository), and using it in Natural Selection is problematic. There is very little there. What is there doesn’t meet PhET code standards. There is significant duplication - it looks like developers have been adding sim-specific stuff with no regard to reusing what’s already there (see https://github.com/phetsims/griddle/issues/46). And cleaning up griddle or writing a general chart library  is not something that fits the Natural Selection timeline (and frankly not something that I'm interested in taking on.)

Given the number of sims that have (or will have) charts, PhET needs a full-featured chart library, similar to JFreeChart. But using a 3rd party library is apparently not an option. @ariel-phet said in https://github.com/phetsims/tasks/issues/979#issuecomment-454875192:

> Discussed with @kathy-phet briefly and she agreed that given our desires for both a11y and iO we will need to "roll our own" charting library. Likely as we begin to design Moving Man we will simultaneously be considering requirements for a charting library and plan to work on this library as a supporting project potentially with several developers.

Rolling your own chart library will be an enormous investment, and I’m not aware of any progress or plans for that task. I also recommend that you investigate the feasibility of wrapping a 3rd-party library, and adding a11y and iO support in the wrapper. JSFreeChart (the JavaScript version of JFreeChart) might be a logical place to start, to lower the cost of porting Java sims.

That said… I’m back to how to proceed for Natural Selection. Unless you have an alternative… To meet milestones, I’ll need to implement sim-specific charts for Natural Selection, with no guarantee of generality or reusability.

Thoughts?

**Comment by ariel-phet** [comment]
@pixelzoom I do not see a problem with implementing sim specific charts here. I don't think there is a major issue with them not being reusable/generalizable at this point, since most sims with charts have been going in that direction. And considering your comments above it seems like the most viable option.

If you make something and feel it would be good to add to common code, we will leave that as your call.

**Comment by pixelzoom** [comment]
Understood, closing.

**Comment by samreid** [comment]
At today's meeting, we discussed the possibility that other phet developers could prepare griddle for usage in natural selection.  Reopening.  Next steps will be prioritization & delegation and making sure the developers understand the design requirements.

**Comment by pixelzoom** [comment]
Reopening this issue to revisit.

At 4/23/20 phet-io meeting, @samreid noted that other sims have a need for charts, and that it would be a shame if charts in Natural Selection were sim-specific.  I agree.  I've brought up the general need for charts before (most recently in phetsims/tasks#979) and the conclusion was that PhET will "roll its own" package.   PhET has so far not rolled its own.  griddle is a nice (but small) step forward, and has been improved since this issue was closed.  But the situation is still fundamentally the same as when this issue was closed: enhancing griddle to meet Natural Selection and PhET-iO requirements will be a significant piece of work, and does not fit the timeline for this sim.  

Assigning to @kathy-phet and @ariel-phet to decide on whether the prior decision should be changed.  My estimate is that enhancing griddle to meet Natural Selection requirements will extend the "feature complete" date for Natural Selection by 1-2 months (optomistically). I've already implemented most of the view for Population and Proportions graphs in a sim-specific way, and generalizing that will not be trivial.  Unclear on how the Pedigree graph will be supported by griddle, since it current contains no support for trees.  

I'm expecting to resume work on charts around 5/5/2020, so high priority on this decision.

**Comment by pixelzoom** [comment]
4/23/20 design meeting with @amanda-phet @ariel-phet @kathy-phet @samreid 

* Continue down the sim-specific path.
* Make the code general where possible, for future-proofing.
* In the future, replace sim-specific components with griddle components, as they mature.
* OK to close this issue.
