### ISSUE TITLE
Population graph layout issue with very long strings

### ISSUE THREAD

**Issue by ariel-phet** [phetsims/natural-selection#210]
Discovered while performing string tests for https://github.com/phetsims/QA/issues/539

With very long strings the population graph (but not the pedigree or proportion graph) gets very messed up in layout

I suspect there is something going on with the "generations" string on the bottom of the graph.

The sim passed all string tests, but this was noticed during `?stringTest=xss` (but passes for `?stringTest=long`

Although not a showstopper for the first release, this is probably good to fix for iO since a long string could potentially be put in place by an instructional designer

To reproduce:
1. Go to https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.18/phet/natural-selection_all_phet.html?stringTest=xss

![stringNs](https://user-images.githubusercontent.com/4051174/91506460-58712980-e88f-11ea-9f42-9e59253f3933.PNG)

**Comment by pixelzoom** [comment]
I thought this might be a problem with the string that `stringTest=xss` uses, so I tried doubling up the `stringTest=long` string, i.e.:

`?stringTest=1234567890123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890`

... and the result was:

<img width="947" alt="screenshot_528" src="https://user-images.githubusercontent.com/3046552/91509037-65dde200-e896-11ea-8e9b-ab95f8b02313.png">

So as the string gets longer, the Population graph is getting pushed more to the right. 

This also indicates that the current `stringTest=long` may be insufficient.

**Comment by pixelzoom** [comment]
Agree that this can be ignored for the prototype.

**Comment by pixelzoom** [comment]
Note to self... Testing with `stringTest=xss` is part of the CRC, and I recently completed a self code review. I know that I tested with `xss`, but I don't recall seeing this problem -- maybe I was just looking for a redirect.  In any case, test with a dev version from around that time, to see if this is something that snuck in recently.

**Comment by pixelzoom** [comment]
This problem first appears in [1.1.0-dev.4](https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.4/phet/natural-selection_en_phet.html).  1.1.0-dev.3 was published 2020-08-03 19:47.  1.1.0-dev.4 was published 2020-08-10 13:42.   I suspect that it's related to the "Zoom in to see data" string, which may not have a `maxWidth` set.

**Comment by pixelzoom** [comment]
Making the "Zoom to see data" string visible at all times confirms the problem.  And looking at the code in PopulationGraphNode.js, I neglected to set a maxWidth:

```js
    const zoomOutToSeeDataText = new Text( naturalSelectionStrings.zoomOutToSeeData, {
      font: NaturalSelectionConstants.INSTRUCTIONS_FONT,
      centerX: gridNode.x + gridWidth / 2,
      centerY: gridNode.y + gridHeight / 2
    } );
```

**Comment by pixelzoom** [comment]
Here's a 1-line patch that fixes the problem. I'm going to wait to commit this until we decide when this issue should be addressed. 

```diff
Index: js/common/view/population/PopulationGraphNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/population/PopulationGraphNode.js	(revision 4b4266ed8b81d55958056710a5e8d8b8b75d9fec)
+++ js/common/view/population/PopulationGraphNode.js	(date 1598582041505)
@@ -116,6 +116,7 @@
 
     const zoomOutToSeeDataText = new Text( naturalSelectionStrings.zoomOutToSeeData, {
       font: NaturalSelectionConstants.INSTRUCTIONS_FONT,
+      maxWidth: 0.75 * gridWidth,
       centerX: gridNode.x + gridWidth / 2,
       centerY: gridNode.y + gridHeight / 2
     } );
```

**Comment by pixelzoom** [comment]
There is almost zero risk in fixing this for the prototype RC.  I recommend we go for it.

**Comment by pixelzoom** [comment]
To verify in 1.1.0-rc.1:

1. Run the sim with `?stringTest=xss`
2. Go to either screen
3. Verify that the layout looks correct, and in particular does not look like the screenshot in https://github.com/phetsims/natural-selection/issues/210#issue-687615693

**Comment by amanda-phet** [comment]
Checked this out on the iPad and it looks good. I also made sure the "zoom in.." text showed up and it still looked good.

**Comment by ariel-phet** [comment]
Looks good, checked as https://github.com/phetsims/QA/issues/540

Closing
