### ISSUE TITLE
LoL may put up dialogs after pause

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#215]
For https://github.com/phetsims/QA/issues/542. Very minor, easier to see on a slower device like Lovelace ChromeOS.
If you click pause on LoL during the pause before a dialog comes up, but before it has loaded, then the sim will pause, and the dialog will appear while paused.
Steps:
1. Go to either screen.
2. Add a mate
3. Be ready to pause using harness
4. As the 5th gen finishes, pause before the dialog for bunnies taking over comes up.

Can be hard to reproduce, especially on fast devices.

**Comment by pixelzoom** [comment]
No idea why someone would even want to do this.  But I don't know anything about how sims are used by LoL.

When the 5th generation completes, and the sim pauses, the dialog has already been schedule to be displayed.   And you can't stop work that's already been scheduled as part of the current frame.   

My recommendation is to close this as "won't fix", but I'll let @ariel-phet decide.

**Comment by ariel-phet** [comment]
@KatieWoe certainly appreciate the diligence in finding this situation, but I agree, this seems unlikely to be an issue. Marking as `wontfix` and closing
