### ISSUE TITLE
double-click on Start Over button is a problem

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#217]
This was originally reported and addressed in https://github.com/phetsims/natural-selection/issues/166.  But the "solution" caused some problems there, and it really deserves its own issue.

When bunnies have taken over the world, the "Start Over" button can take a second to complete on slower devices. @KatieWoe reported that it was easy to click twice on Start Over. Then the second click would be processed by the Add a Mate button, and you might not even see that button. I can reproduce the same behavior on faster platforms by rapidly double-clicking on Start Over.

I solved this problem by adding a timer, and @KatieWoe and @amanda-phet reported that it worked nicely. The shas were: https://github.com/phetsims/natural-selection/commit/cebb40161cbd31027e9363a3cc0242ed34e2297c https://github.com/phetsims/natural-selection/commit/645d60d0fc839399fef4916b608b6214307592f8

Unfortunately, those changes resulted in new PhET-iO problems, specifically #211 and (perhaps) #212.  Version 1.1.0 was published with this known issues, since that version is brand=phet only.

So... I need to revert the above changes, and find a way to make this approach play nice with PhET-iO.

**Comment by pixelzoom** [comment]
In the above commit, I used the same approach that I had used in #166 (timer), but in a way that plays nice with PhET-iO.

Sorry to have to ask you to do this again, but...
* @KatieWoe please verify in phettest on a slow device.
* @amanda-phet please verify in phettest on any device.

**Comment by pixelzoom** [comment]
... or if you don't have VPN and would prefer to test in a dev version, use [1.2.0-dev.2](https://phet-dev.colorado.edu/html/natural-selection/1.2.0-dev.2/phet/natural-selection_en_phet.html).

**Comment by pixelzoom** [comment]
There's still a problem. Please pause testing while I fix it.  From Slack with @KatieWoe:

Kathryn Woessner:house_with_garden:  3:59 PM
There seems to be a new "play" button? It doesn't seem to do anything. Is it intended?

Chris Malley  4:00 PM
Ah rats, I see it too.  It's only supposed to show up when the initial population is > 1.  Please pause your testing while I fix it.

Kathryn Woessner:house_with_garden:  4:01 PM
The double click thing seems fine at least

Chris Malley  4:01 PM
How the heck did I miss THAT ?!?

**Comment by pixelzoom** [comment]
OK, problem with "Play" button appearing when it shouldn't is fixed.  Please verify in [1.2.0-dev.3](https://phet-dev.colorado.edu/html/natural-selection/1.2.0-dev.3/phet/natural-selection_en_phet.html) or phettest.

**Comment by KatieWoe** [comment]
Dev.3 looks ok on the Lovelace ChromeOS device.

**Comment by amanda-phet** [comment]
I don't see a "Play" button, and the double-clicking seems to be working just fine! If I try to double-click really fast, I still notice the "Add a mate" button is being clicked on the second one. So I think all is good here.
