### ISSUE TITLE
order of icons and abbreviations in Alleles panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#22]
This mockup for the "Alleles" panel appears in the design doc:

<img width="287" alt="screenshot_15" src="https://user-images.githubusercontent.com/3046552/70261277-55f20100-174f-11ea-8302-14b2c812a874.png">

In absence of an explicit specification, the implicit specification here is that the icons remain in fixed locations, and the abbreviations change to match whether those icons are dominant or recessive.  

In 12/5/19 status meeting, @kathy-phet pointed out that this behavior is different than the "Add Mutations" panel, where dominant is always on the left, recessive is always on the right, and the position of the icons changes based on selection.  E.g.:

<img width="243" alt="screenshot_17" src="https://user-images.githubusercontent.com/3046552/70261597-fe07ca00-174f-11ea-9bd4-c713e4d59edb.png">

So what should we do for the "Alles" panel? My recommendation is to match the order of icons in the "Add Mutations" panel.

**Comment by amanda-phet** [comment]
>So what should we do for the "Alles" panel? My recommendation is to match the order of icons in the "Add Mutations" panel.

I thought it would be simpler to keep the icons static, but if they can be displayed in the same order as they appear in the Add Mutations panel, that seem ideal to me.

**Comment by pixelzoom** [comment]
12/12/19 design meeting:

Allele abbreviation will stay in fixed locations (dominant recessive) and icons will change.

**Comment by pixelzoom** [comment]
Noted in AllelesPanel.js for when I wire this up.  Closing.
