### ISSUE TITLE
when do I need to handle PhET-iO serialization?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#220]
I'm wondering if I'm handling serialization of some Core Types that is also being done automatically.

In Bunny.toStateObject:

```js
      genotype: Genotype.GenotypeIO.toStateObject( this.genotype ),
      phenotype: Phenotype.PhenotypeIO.toStateObject( this.phenotype ),
```

In Genotype.toStateObject:

```js
      furGenePair: GenePair.GenePairIO.toStateObject( this.furGenePair ),
      earsGenePair: GenePair.GenePairIO.toStateObject( this.earsGenePair ),
      teethGenePair: GenePair.GenePairIO.toStateObject( this.teethGenePair ),
```

Are GenotypeIO, PhenotypeIO, and GenePairIO already handling the serialization of the above fields?

I'll need to discuss this with someone from the iO team.

**Comment by pixelzoom** [comment]
I tried commenting out the `applyState` calls in https://github.com/phetsims/natural-selection/issues/220#issue-692199695.  So I'm guessing that these are unnecessary because, like Property, Genotype, Phenotype, and GenePair are stateful. So save/restore of state is handled by PhET-iO.

**Comment by pixelzoom** [comment]
Similar questions about these cases:

```
// Bunny.toStateObject
      father: NullableIO( ReferenceIO( Bunny.BunnyIO ) ).toStateObject( this.father ),
      mother: NullableIO( ReferenceIO( Bunny.BunnyIO ) ).toStateObject( this.mother ),

// GenePair.toStateObject
      fatherAllele: Allele.AlleleIO.toStateObject( this.fatherAllele ),
      motherAllele: Allele.AlleleIO.toStateObject( this.motherAllele )

// Genotype.toStateObject
 mutation: NullableIO( ReferenceIO( Allele.AlleleIO ) ).toStateObject( this.mutation )

// Phenotype.toStateObject
      furAllele: Allele.AlleleIO.toStateObject( this.furAllele ),
      earsAllele: Allele.AlleleIO.toStateObject( this.earsAllele ),
      teethAllele: Allele.AlleleIO.toStateObject( this.teethAllele )

// ProportionsCounts.toStateObject
      startCounts: BunnyCounts.BunnyCountsIO.toStateObject( this.startCounts ),
      endCounts: BunnyCounts.BunnyCountsIO.toStateObject( this.endCounts )
```

**Comment by samreid** [comment]
I asked in slack:

> Can you comment in the issue which types are used like data types and which are like reference types?  That will tell us which methods are necessary

**Comment by pixelzoom** [comment]
The type of serialization is docuemented for every IO Type created in NS. 

Examples:

```js
/**
 * AlleleIO handles PhET-iO serialization of Allele. It implements 'Reference type serialization',
 * as described in the Serialization section of
 * https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-guide.md#serialization
 */
class AlleleIO extends ReferenceIO( ObjectIO ) {}
```

```
/**
 * ProportionsCountsIO handles PhET-iO serialization of ProportionsCounts. It does so by delegating to BunnyCounts.
 * The methods that BunnyCountsIO implements are typical of 'Data type serialization', as described in
 * the Serialization section of
 * https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-guide.md#serialization
 */
class ProportionsCountsIO extends ObjectIO {
```

```js
/**
 * BunnyIO handles PhET-iO serialization of Bunny. Because serialization involves accessing private members,
 * it delegates to Bunny. The methods that BunnyIO overrides are typical of 'Dynamic element serialization',
 * as described in the Serialization section of
 * https://github.com/phetsims/phet-io/blob/master/doc/phet-io-instrumentation-guide.md#serialization
 */
class BunnyIO extends ObjectIO {
```

Is this what you're looking for?

**Comment by samreid** [comment]
> father: NullableIO( ReferenceIO( Bunny.BunnyIO ) ).toStateObject( this.father ),

This seems important to store. Even though the `father` is stateful and stored, the `bunny` needs to record its reference to the `father`.

I don't have enough domain specific knowledge about the application to answer about the other parts. You could try removing them and see what happens or we could schedule an appointment.

**Comment by pixelzoom** [comment]
OK, thanks for looking! I'll poke around some more next week.

**Comment by pixelzoom** [comment]
9/9/2020 Zoom call with @samreid and @zepumph.

We walked through the examples in the comments above, and they all look correct. I now have a better understanding of when and why I need to explicitly serialize things that have a ReferenceIO type. 

One small change is in this example:

```js
// Genotype.toStateObject
      mutation: NullableIO( ReferenceIO( Allele.AlleleIO ) ).toStateObject( this.mutation )
```

In this case the `ReferenceIO` is redundant, so this can be changed to 

```js
      mutation: NullableIO( Allele.AlleleIO ).toStateObject( this.mutation )
```

**Comment by pixelzoom** [comment]
All work here is done, closing.
