### ISSUE TITLE
should button labels be instrumented?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#223]
The labels on the "Add a Mate", "Play", and "Start Over" buttons are not currently instrumented, and therefore not editable in Studio.   I don't recall if this was a deliberate decision or just the way it is. 

If they will not be instrumented, then I should add `tandem: Tandem.OPT_OUT` in the code.

**Comment by pixelzoom** [comment]
the problem with sun buttons (phetsims/sun#623) is unlikely to be addressed there.  Instead, in today's PhET-iO meeting, there was a discussion about adding a Rosetta-like UI to Studio for changing strings, and eventually un-instrumenting most `textProperty` elements.  But that's going to be a ways off.    So in the meantime,  I recommend that we leave these button labels uninstrumented.  

@arouinfar do you agree?

**Comment by amanda-phet** [comment]
I'm fine leaving these labels uninstrumented for now. 

Did you want @arouinfar 's feedback too, or just mine?

**Comment by pixelzoom** [comment]
9/10/2020 design meeting: Leave uninstrumented. Closing.
