### ISSUE TITLE
add "Allele" suffix to Allele tandem names

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#225]
An oversight that I noticed...  The set of Alleles looks like this:

<img width="186" alt="screenshot_557" src="https://user-images.githubusercontent.com/3046552/92756646-3e811d80-f34a-11ea-83e5-cbb2efadbb6f.png">

They tandem name really should have an "Allele" suffix, like this:

<img width="214" alt="screenshot_558" src="https://user-images.githubusercontent.com/3046552/92756759-5658a180-f34a-11ea-87ae-1e3a7d519e0c.png">

**Comment by pixelzoom** [comment]
None of these elements are featured, so I doubt that this change is very significant.  But over to @amanda-phet so that's she's aware of the change, and in case there's anything related in the Client Guide that needs to change.

**Comment by amanda-phet** [comment]
Thanks for the heads up. Nothing in the client guide needs to change.

**Comment by amanda-phet** [comment]
Anything else to do here?

**Comment by pixelzoom** [comment]
9/10/2020 design meeting: looks good, closing.
