### ISSUE TITLE
Check the mipmaps

### ISSUE THREAD

**Issue by samreid** [phetsims/natural-selection#228]
During https://github.com/phetsims/chipper/issues/978 the mipmaps were updated.  Can you please review them and make sure they are OK?

**Comment by pixelzoom** [comment]
This sim doesn't have any mipmaps.  I'm wondering why 7 .js files for images/ were revised in https://github.com/phetsims/natural-selection/commit/927553bafdaa5f219d08d4330504e221a33cb6ed.  @jessegreenberg @samreid ?

**Comment by pixelzoom** [comment]
Looking at 927553b, the only difference I see is the deleting of a blank line in each of the *_png.js files.  For example:

<img width="617" alt="screenshot_562" src="https://user-images.githubusercontent.com/3046552/93002390-f56ccd00-f4f3-11ea-978f-282f6ed4170c.png">

**Comment by samreid** [comment]
I see, the formatter adds a blank line, but the file is generated without the blank line.  It seems like I should change the file generation so it outputs the blank line after the import, so that it is compatible with our formatter.  @pixelzoom does that sound good to you?

**Comment by pixelzoom** [comment]
Yeah, that sounds correct.

**Comment by samreid** [comment]
Thanks, I'll address that in https://github.com/phetsims/chipper/issues/982.  Up to you what you wish to do with this issue.
