### ISSUE TITLE
fix options handling in PopulationGridNode.VerticalLines

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#229]
Related to #203 (code review) @jonathanolson had this REVIEW comment about PopulationGridNode.VerticalLines:

```js
class VerticalLines extends Node {
...
  constructor( xRangeProperty, options ) {
...
    const path = new Path( shape, options );
...
    super( options ); //REVIEW: We're passing the options both to the VerticalLines AND its Path? And clipArea is applied to both?
  }
...
}
```

Good catch, this is not what I intended here.  Passing all options to a subcomponent is (imo) an anti-pattern.  And clipArea makes it worse here.  I will address, probably via nested options for the Path.

**Comment by pixelzoom** [comment]
Fixed in above commit, using nested option `pathOptions` for the Path subcomponent of VerticalLines.

@jonathanolson please review.

**Comment by pixelzoom** [comment]
I'll be taking shas for the 1.2 branch on 9/17, and this needs to be reviewed before then. So high priority please.

**Comment by jonathanolson** [comment]
Looks great to me, thanks!
