### ISSUE TITLE
does the Proportions graph advance automatically while the sim is running?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#23]
A question related to the Proportions graph... The design doc says:

> If the user scrolls back to view the data at a previous generation, the sim pauses. Once they click play the sim resumes and the chart jumps back to current time.  

What happens when the user is viewing the current generation (call it Generation N), the sim is running, and a new generation begins (call it Generation N+1)?  Does the Proportions graph automatically advance to Generation N+1?

**Comment by amanda-phet** [comment]
>What happens when the user is viewing the current generation (call it Generation N), the sim is running, and a new generation begins (call it Generation N+1)? Does the Proportions graph automatically advance to Generation N+1?

yes

**Comment by pixelzoom** [comment]
Got it.  If there's no need to discuss with the team, @amanda-phet you can feel free to close this issue.
