### ISSUE TITLE
getting black screen

### ISSUE THREAD

**Issue by nagulvali555** [phetsims/natural-selection#231]
![image](https://user-images.githubusercontent.com/71317991/93239083-27ba3c80-f737-11ea-8315-5021cc75d143.png)

**Comment by pixelzoom** [comment]
@nagulvali555 This is not enough info for us to troubleshoot.   

Questions:
* Have you followed the setup instructions in the [PhET Development Overview](https://github.com/phetsims/phet-info/blob/master/doc/phet-development-overview.md)?  
* How are you running the sim? 
* What is your browser version and OS version? 
* Are there any error messages in the console?  
* I see that you've forked natural-selection. Are you running from your fork, or from PhET's repo? Have you made any changes in the fork?

**Comment by pixelzoom** [comment]
No response after 1 week, and we can't investigate without more information. So closing this issue.
