### ISSUE TITLE
memory test for brand=phet-io (1.2 branch)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#233]
This is a memory test for brand=phet-io, prior to creating the 1.2 branch.  The previous test was in #189.

There are 2 test procedures:

(1) Standard fuzz test

1. Take a heap snapshot at startup.
2. Run with `?fuzz` for 10 minutes, taking snapshots at 1-minute intervals.
3. Take a heap snapshot at t=15 minutes.

(2) Heap snapshots every 100 generations

1. Run the sim with `secondsPerGeneration=0.25` (so this test can be done quickly)
2. Go to the _Lab_ screen
3. In the "Add Mutations" panel, press the dominant buttons for Fur, Ears, Teeth (so that we create a lot of points on the Population graph)
4. In the "Environmental Factors" panel, check the "Limited Food" checkbox (so that the population stabilizes)
5. In the Population graph, zoom out to y-axis range 0-500 (so that we create the view for plots)
6. Take a heap snapshot at Generation 0
7. Press the "Add a Mate" button
8. Take a heap snapshot every ~100 generations, including generation 1000. Heap size should be similar for each of these snapshots.
9. Close the "Memory Limit" dialog that pops up at Generation 1000.
10. Press the "Reset All" button, then take another Generation 0 heap snapshot. Heap size should be similar to the heap size in step 6.

**Comment by pixelzoom** [comment]
Test configuration:
* https://phet-dev.colorado.edu/html/natural-selection/1.2.0-dev.4/phet/natural-selection_en_phet.html
* MacBookPro16,1
* Chrome 85.0.4183.102, Incognito

(1) Standard fuzz test:

| Time (minutes) | Heap Size (MB) |
| --: | --: |
| 0 | 24.8 |
| 1 | 28.6 |
| 2 | 29.9 |
| 3 | 30.2 |
| 4 | 30.3 |
| 5 | 30.7 |
| 6 | 30.9 |
| 7 | 30.8 |
| 8 | 31.1 |
| 9 | 31.2 |
| 10 | 31.2 |

**Comment by KatieWoe** [comment]
Win 10 Chrome 84.0.4147.89 Standard Test:
Start: 26.9
1 min: 30.4
2 min: 31.0
3 min: 31.3
4 min: 31.5
5 min: 31.7
6 min: 31.8
7 min: 32.0
8 min: 31.9
9 min: 32.1
10 min: 32.2
15 min:32.6

**Comment by KatieWoe** [comment]
Win 10 Chrome 85.0.4183.121 Generation 100 Test:
0: 26.2
100: 55.2
200: 55.1
300: 56.1
400: 56.0
500: 56.2
600: 55.5
700: 56.3
800: 56.2
900: 56.3
1000: 57.1
0: 28.8

**Comment by pixelzoom** [comment]
Excellent, thanks @KatieWoe.  Memory test for the 1.2 branch looks good, so this issue can be closed.
