### ISSUE TITLE
populationPanel.visibleProperty mistakenly not featured 

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#236]
@KatieWoe noticed in https://github.com/phetsims/QA/issues/551 that an element that was supposed to be featured was not.

I'll feature `naturalSelection.labScreen.view.graphs.populationNode.populationPanel.visibleProperty` in master, then @pixelzoom will patch the 1.2 branch.

**Comment by pixelzoom** [comment]
I discussed with @amanda-phet on Slack. Faster for me to do this in master and 1.2, and I'll have @amanda-phet review master.

**Comment by pixelzoom** [comment]
Actually a good thing that I did this. Because I'm using WebStorm, I discovered that overrides.js formatting does not match PhET style, https://github.com/phetsims/studio/issues/196.

**Comment by pixelzoom** [comment]
Addressed in master and 1.2 by the above commits.  @amanda-phet please review in master.   If it looks OK, assign back to me.

**Comment by amanda-phet** [comment]
Looks good. 

As for  phetsims/studio#196, do we need to do something with the formatting when we paste into overrides? Or can we keep doing what we are doing?

**Comment by pixelzoom** [comment]
> As for phetsims/studio#196, do we need to do something with the formatting when we paste into overrides? Or can we keep doing what we are doing?

Best to ask that in phetsims/studio#196.  I'll move your questions there.

**Comment by pixelzoom** [comment]
Ready for testing in the next 1.2 RC.

**Comment by KatieWoe** [comment]
This does look fixed in rc.2
