### ISSUE TITLE
Launched Sim on iPadOS 14.0 takes up more than full screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#237]
See https://github.com/phetsims/phet-io-wrappers/issues/377. For phetsims/QA#551.

**Comment by zepumph** [comment]
Ready for cherry-pick, see https://github.com/phetsims/phet-io-wrappers/issues/377#issuecomment-697926530

**Comment by zepumph** [comment]
Make sure that this bug get's double checked by RC.

**Comment by pixelzoom** [comment]
Patch completed, using the shas identified in https://github.com/phetsims/phet-io-wrappers/issues/377#issuecomment-697926530:

```
% cd perennial
% grunt checkout-target --repo=natural-selection --target=1.2
% cd ../phet-io-wrappers
% git checkout -b natural-selection-1.2
% git cherry-pick ece0ee1edcaaca0c41eacca32fc0cc860e1a8975
% git cherry-pick a6687e8dd01a981e2b6ad97e72719d9854bab0ee
% git push origin natural-selection-1.2
```

**Comment by pixelzoom** [comment]
Oops, forgot to update dependencies.json.  Done in the above commits (first commit was an oops).

**Comment by pixelzoom** [comment]
Verified with a local build:

```
% cd perennial 
% grunt checkout-target --repo=natural-selection --target=1.2
% grunt --brands=phet-io
```

Then opened the wrapper index and pressed "Launch Template" button.

**Comment by pixelzoom** [comment]
Ready for testing in the next 1.2 RC.

**Comment by KatieWoe** [comment]
This seems fixed in rc.2
