### ISSUE TITLE
option to hide the concept of alleles

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#24]
From the PHET-io design doc:

> Ability to hide any mention of alleles. Hide the alleles from the pedigree, as well as the panel titled "Alleles." The goal is to accommodate a client who works with younger kids who will want to hide anything with the word alleles, as well as any symbolic representations of genotype.  

This is a feature that will also be available for `brand=phet`.  So it will be controlled via a query parameter, `?allelesVisible=false`.

**Comment by pixelzoom** [comment]
The `allelesVisible` query parameter was added in the above commit.  It currently excludes the entire "Alleles" panel, and will hide alleles in the Pedigree tree (when it's implemented).   When the Alleles panel is excluded, the Pedigree tree expands to fill the available space.

Note that PhET-iO does not currently support conditional creation of elements via query parameters, see https://github.com/phetsims/phet-io/issues/1584.  So the Alleles panel is created regardless of this value of `?allelesVisible`, because not creating it would cause API validation to fail.  When running with `?allelesVisible=false`, the Alleles panel and all of its sub-elements will appear in the Studio tree, but setting their values will have no effect because the Alleles panel is not added to the scenegraph.

**Comment by pixelzoom** [comment]
Unassigning until I implement the Pedigree tree.

**Comment by pixelzoom** [comment]
Labeling for design meeting discussion, to discuss and approve the fact that the Alleles panel (and possibly other related things) will appear in Studio regardless of the value of `?allelesVisible`.

**Comment by pixelzoom** [comment]
12/11/19 design meeting

Add `phetioDocumentation` for `naturalSelection.labScreen.view.addMutationsPanel` describing that it's not in the scenegraph when `?allelesVisible=false`.

**Comment by pixelzoom** [comment]
`phetioDocumentation` was added for the Alleles panel in the above commit.  See screenshot of Studio below.  @amanda-phet @kathy-phet please let me know if you'd like any changes.

<img width="728" alt="screenshot_21" src="https://user-images.githubusercontent.com/3046552/70726932-129e1200-1cbc-11ea-98c2-77d5fdb86777.png">

**Comment by amanda-phet** [comment]
That looks clear to me.

**Comment by pixelzoom** [comment]
I'm going to go ahead and close this.  It will get another review and opportunity for change later in the process.
