### ISSUE TITLE
Typo in client-requests.md

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#241]
@loganbraywork found a typo in [client-requests.md](https://github.com/phetsims/phet-io-client-guides/blob/master/natural-selection/client-requests.md). 

Where it says `naturalSelection.introScreen.view.addMutationsPanel.teethsRow.visibleProperty` it should say `naturalSelection.introScreen.view.addMutationsPanel.teethRow.visibleProperty`. 

This will need to be branched and patched.

**Comment by amanda-phet** [comment]
I made the update. 

Over to you @pixelzoom

**Comment by pixelzoom** [comment]
Note to self:  I need to create branch "natural-selection-1.2" of phet-io-client-guides, then cherry-pick 7323b2abc1dfd52a1b77aa020de7ec3c7e7ce414 to that branch.

**Comment by pixelzoom** [comment]
Patch completed.  To be tested in next RC.

**Comment by pixelzoom** [comment]
Oops, forgot to update dependencies.json.  Done in the above commit.

**Comment by phet-steele** [comment]
I found 0 instances of `naturalSelection.introScreen.view.addMutationsPanel.teethsRow.visibleProperty` in [client-requests.md](https://github.com/phetsims/phet-io-client-guides/blob/master/natural-selection/client-requests.md), and 1 instance of `naturalSelection.introScreen.view.addMutationsPanel.teethRow.visibleProperty`. Closing.
