### ISSUE TITLE
Bunny says it is alive when it isn't

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#242]
For https://github.com/phetsims/QA/issues/551 in Studio. Mac 10.15 Safari.
If I am misunderstanding, please let me know and feel free to close. However, when looking at a bunny in the model, such as `naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_0` you can things like its generation. It will also read `isAlive` and then True or False. However, it seems to always read true, even if the bunny is dead. Easiest way to see this is to highlight the first bunny, limit food, and wait for it to die and check the studio read out.
Visuals: https://drive.google.com/file/d/1cLVA2aWukub3wLe32FLTfy5qtxwquwNA/view?usp=sharing

**Comment by pixelzoom** [comment]
When you say "looking at a bunny in the model", do you mean looking at it in the Studio metadata panel, like the screenshot below?  If so, note that the value shown is labeled  "Initial state".  It does not update dynamically. 

@KatieWoe does that answer your question? 

<img width="634" alt="screenshot_574" src="https://user-images.githubusercontent.com/3046552/94059442-a4849080-fd9f-11ea-8298-9f424de1d8b5.png">

**Comment by KatieWoe** [comment]
Yes it does, I missed the initial state part.
