### ISSUE TITLE
Playback wrapper slow or fails (macOS 10.15 + Chrome)

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#246]
In https://github.com/phetsims/QA/issues/551#issuecomment-696846871, @KatieWoe reported:

> Playback wrapper seems to be exceedingly slow on Mac 10.15 Chrome for both loading log and starting playback. Having trouble even getting it to start. @zepumph please advise. In fact it seems to have timed out: `Failed to load resource: net::ERR_CONNECTION_RESET`

Blocks publication until someone decides otherwise.

**Comment by zepumph** [comment]
Partial duplicate-ish of https://github.com/phetsims/phet-io-wrappers/issues/376. I'm not sure about blocking. It would be nice to ask @kathy-phet during the phet-io meeting about the priority of the playback wrapper for NS.

**Comment by pixelzoom** [comment]
From 9/24/2020 phet-io meeting over in https://github.com/phetsims/phet-io-wrappers/issues/376#issuecomment-698480693:
> This should not block the current version of Natural Selection (1.2), but should still be high priority to look into. This will block the next version of NS though (the one that will be fully published). Marking as such.
> 
> We haven't seen this behavior outside of NS, but if we do, that will further up the priority on this.

**Comment by zepumph** [comment]
@pixelzoom, if you are planning to take shas from master for 1.3, this issue can be closed.

**Comment by zepumph** [comment]
If we need to cherry-pick, see https://github.com/phetsims/phet-io-wrappers/issues/378#issuecomment-701665340

**Comment by pixelzoom** [comment]
The next milestones (#251) will be taking shas from master.   I'll label this as "fixed", and leave open for verification by QA.

**Comment by KatieWoe** [comment]
This doesn't seem to happen anymore in dev.1. I did see https://github.com/phetsims/gravity-and-orbits/issues/376. @pixelzoom up to you if you want to close.

**Comment by pixelzoom** [comment]
> This doesn't seem to happen anymore in dev.1. I did see phetsims/gravity-and-orbits#376.

Is phetsims/gravity-and-orbits#376 significant here? Something that needs to be addressed? I have no idea.

>  @pixelzoom up to you if you want to close.

I'm not at all familiar with this feature, so don't feel qualified to decide whether this is ready to close.   Assigning to the PhET-iO team to decide.

**Comment by pixelzoom** [comment]
For phetsims/QA/issues/636.

**Comment by pixelzoom** [comment]
@KatieWoe said:
> This doesn't seem to happen anymore in dev.1. I did see phetsims/gravity-and-orbits#376.

To clarify, based on Slack discussion with @KatieWoe ...   She no longer sees the problem reported here (Playback wrapper slow or fails).  But she may see phetsims/gravity-and-orbits#376 occurring in NS now, but isn't certain.   I'm not clear on the differences between this issue (#246) and phetsims/gravity-and-orbits#376, so I'd like the PhET-iO team's recommendation on how to proceed.  Can this issue be closed? Do we need a new issue for some aspect of phetsims/gravity-and-orbits#376 that is occurring with NS? Is any of this blocking?

**Comment by kathy-phet** [comment]
Playback wrapper needs general attention at some point when it becomes a priority for clients or researchers, but phetsims/gravity-and-orbits#376 is not a high priority and is not blocking for publication of NS.

**Comment by kathy-phet** [comment]
I'll make a central comment for playback wrapper.

**Comment by pixelzoom** [comment]
Since @kathy-phet says that nothing here is blocking, I'm guessing that it's OK to close this issue.  If someone disagrees, please reopen ASAP.
