### ISSUE TITLE
test Screenshot feature

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#256]
In phetsims/joist#664, the quality of the Screenshot feature was improved.  At 11/12/2020 phet-io meeting, @kathy-phet said that this issue is not blocking for Natural Selection, but she would like it to be testing in the next release.

**Comment by pixelzoom** [comment]
At 11/12/2020 phet-io meeting, this was tested and it still seemed to have problems.  So removing "fixed-awaiting-deploy" label.

**Comment by pixelzoom** [comment]
@KatieWoe could you please verify that this is working in master?

**Comment by KatieWoe** [comment]
Looks better on master.
Old version:
![Screen Shot 2020-11-12 at 12 31 12 PM](https://user-images.githubusercontent.com/41024075/98987780-f0bc9900-24e3-11eb-89f1-5928d154f548.png)
Master:
![Screen Shot 2020-11-12 at 12 32 56 PM](https://user-images.githubusercontent.com/41024075/98987986-36796180-24e4-11eb-9430-a1b4f5398c80.png)

**Comment by KatieWoe** [comment]
Things look good in dev.1. Will reopen if something comes up
