### ISSUE TITLE
Add a label to the Generation Clock

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#258]
This was requested in https://github.com/phetsims/natural-selection/issues/257. But as a new feature request, it deserves its own issue.  So moving here.

@kathy-phet asked the client whether they had any change requests for the upcoming 1.3 release.  

@kathy-phet said:
> Here is the reply: 
> 
> > Great to hear from you! I was just about to send you a (hopefully) small request, which is to have a label (or option for one?) on the circular pink timer in this sim. Maybe that's not the only/best solution, but I've encountered a couple times with folks that it can be difficult to understand what it does.
> > 
> >What do you think? Is this something that can be added in relatively easily?
> 
> Shall we discuss at design meeting?
> 👍🏻 @amanda-phet

**Comment by pixelzoom** [comment]
I don't feel like I have enough info to proceed with a design meeting for this request.

@kathy-phet Can you please ask the client for label suggestions, and what specifically they'd like the label to communicate? Does the label need to communicate just "Generation Clock", or does it need to somehow explain how/why the sections of the clock are colored? (dark pink, light pink, green, gray)

This also seems like the type of request where we'd like to avoid making this an option -- either do it or don't do it. If we feel the client's concern is legitimate, then presumably it's a legitimate concern in general.

**Comment by pixelzoom** [comment]
@kathy-phet said: 
> I think this has come up some before -- that the generation clock is a bit of a challenge to interpret. Is there a title we could give it that would help generally? I think a discussion will be useful.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I would just label it "Generation". A design meeting would be helpful to determine where to put the label, and if we want it as an option for just PhET-iO or for all users. Once we have the label, the client can always rename it, so I don't think we need to know what they'd want to call it.

**Comment by pixelzoom** [comment]
Intepretation and complexity of the Generation Clock definitely came up before, more than once if I recall correctly.   And we did make a few changes from the original design.

During development, I added the generation number below the clock, because I didn't think it was reasonable to have to look elsewhere to see that the generation number was changing on each clock cycle.

In https://github.com/phetsims/natural-selection/issues/92, we decided to add icons next to the Environmental Factors checkboxes:

<img width="219" alt="screenshot_868" src="https://user-images.githubusercontent.com/3046552/108120519-9e4cc480-705e-11eb-958e-d658ab9461d1.png">

... to communicate what the "gray" and "green" slices of the clock signify.  I don't know if this was successful, or whether it was specifically tested in interviews.

Instead of just showing the generation number (eg '2') we could show "Generation 2".   But again, without asking the client a couple more questions, I'm not certain that will address their request.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> I would just label it "Generation".

I'm not a fan of a new label. If it's "Generation", then I'd prefer to integrate it with the value, e.g. "Generation 2".  And that's problematic for the "let the client change it" approach.

> A design meeting would be helpful to determine where to put the label, and if we want it as an option for just PhET-iO or for all users. 

I'm not a fan of a PhET-iO only feature unless that's absolutely necessary.  If it's PhET-iO only, the reality is that it will not receive the same level of testing as a regular feature.

> Once we have the label, the client can always rename it, so I don't think we need to know what they'd want to call it.

Why not simply ask the client if "Generation 2" would address the issue for them?  Or ask them what they would suggest - they might have a good idea.  And if what we implement works for the client, then we'll save us and them some effort.

**Comment by pixelzoom** [comment]
https://github.com/phetsims/natural-selection/issues/162#issuecomment-673726376:
> Yes, students understood the generation clock- a full cycle, when mating occurred, and 2/3 easily interpreted the color-coded slices without assistance. While one called a cycle a "day", that could easily be cleared up in a classroom setting, especially since he could tell the x-axis of the population graph was Generations.

So another possibility for addressing this issue would be to share these interview results with the client, and see if that addresses their concern.

**Comment by kathy-phet** [comment]
I've pinged the client for their ideas, and passed the idea of a "Generation 1" label by them.

**Comment by pixelzoom** [comment]
Time estimate to label the clock with "Generation {{number}}" is < 1 hour. Here's how that would look in context:

<img width="968" alt="screenshot_869" src="https://user-images.githubusercontent.com/3046552/108128006-5f703c00-7069-11eb-9b3a-86641962a919.png">

**Comment by pixelzoom** [comment]
If we change the label to (e.g.) "Generation 2" we will need to add a new string to the translated-strings file.  PhET convention says that we should not grab an existing "Generation" string translation and use it here because of:

(a) Ordering:  the translator should be able to change the order of the label and number to fit their locale
(b) Context: the translator may choose to use a different label in this context

So we would be adding this to the English strings file:

```json
"generationNumber": {
  "value": "Generation {{generationNumber}}"
} 
```

Does PhET have a process for notifying translators when a new release adds a string? Or do translators find out some other way?

**Comment by pixelzoom** [comment]
> If we change the label to (e.g.) "Generation 2" we will need to add a new string to the translated-strings file.   ...

Perhaps we can avoid having to add a new string.

I see that we have this translated string, used in the Proportions graph:

```json
  "generationValue": {
    "value": "Generation {{value}}"
  },
```

Even though it's a slightly different context, I think it would be safe and appropriate to use this string for labeling the Generation Clock.

**Comment by pixelzoom** [comment]
I've prepared this patch, which we can use as a starting point for our design meeting. It reuses the `generationValue` string, keeps the font size the same, and moves the entire clock up 5 pixels.

<details>
<summary>Patch</summary>

```diff
Index: js/common/view/GenerationClockNode.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/GenerationClockNode.js b/js/common/view/GenerationClockNode.js
--- a/js/common/view/GenerationClockNode.js	(revision e846b26589a983021b4df4d3fcacd09c82559c7f)
+++ b/js/common/view/GenerationClockNode.js	(date 1613670762744)
@@ -12,6 +12,7 @@
 import Shape from '../../../../kite/js/Shape.js';
 import merge from '../../../../phet-core/js/merge.js';
 import AssertUtils from '../../../../phetcommon/js/AssertUtils.js';
+import StringUtils from '../../../../phetcommon/js/util/StringUtils.js';
 import PhetFont from '../../../../scenery-phet/js/PhetFont.js';
 import Circle from '../../../../scenery/js/nodes/Circle.js';
 import Node from '../../../../scenery/js/nodes/Node.js';
@@ -19,6 +20,7 @@
 import Text from '../../../../scenery/js/nodes/Text.js';
 import Tandem from '../../../../tandem/js/Tandem.js';
 import naturalSelection from '../../naturalSelection.js';
+import naturalSelectionStrings from '../../naturalSelectionStrings.js';
 import GenerationClock from '../model/GenerationClock.js';
 import NaturalSelectionColors from '../NaturalSelectionColors.js';
 import NaturalSelectionConstants from '../NaturalSelectionConstants.js';
@@ -78,7 +80,8 @@
     const generationNode = new Text( '', {
       font: GENERATION_FONT,
       fill: 'black',
-      top: circle.bottom + 3
+      top: circle.bottom + 3,
+      maxWidth: 150 // determined empirically
     } );
 
     // Layering order is important here!
@@ -89,7 +92,9 @@
 
     // Update the generation number. unlink is not necessary.
     generationClock.clockGenerationProperty.link( clockGeneration => {
-      generationNode.text = clockGeneration;
+      generationNode.text = StringUtils.fillIn( naturalSelectionStrings.generationValue, {
+        value: clockGeneration
+      } );
       generationNode.centerX = circle.centerX;
     } );
 
Index: js/common/view/NaturalSelectionScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/NaturalSelectionScreenView.js b/js/common/view/NaturalSelectionScreenView.js
--- a/js/common/view/NaturalSelectionScreenView.js	(revision e846b26589a983021b4df4d3fcacd09c82559c7f)
+++ b/js/common/view/NaturalSelectionScreenView.js	(date 1613670810378)
@@ -76,7 +76,7 @@
     const generationClockNode = new GenerationClockNode( model.generationClock,
       model.food.enabledProperty, model.wolfCollection.enabledProperty, {
         centerX: environmentNode.centerX,
-        top: environmentNode.top + NaturalSelectionConstants.ENVIRONMENT_DISPLAY_Y_MARGIN,
+        top: environmentNode.top + NaturalSelectionConstants.ENVIRONMENT_DISPLAY_Y_MARGIN - 5,
         tandem: options.tandem.createTandem( 'generationClockNode' )
       } );
 ```diff

</details>

**Comment by amanda-phet** [comment]
>I see that we have this translated string, used in the Proportions graph:
`````
  "generationValue": {
    "value": "Generation {{value}}"
  },
`````
>Even though it's a slightly different context, I think it would be safe (and appropriate) to use this string for labeling the Generation Clock.

I actually think it's ideal to use the same string here because they are referring to the exact same thing, not a different context at all. I'm glad you found that string!

**Comment by pixelzoom** [comment]
2/18/21 design meeting: @amanda-phet @kathy-phet @arouinfar @pixelzoom 

We decided to add the "Generation X" label.  We tweaked my patch until everyone was happy with the font size and spacing, and I commited the change in c331115.   No one felt the need for a review step, so I've marked this as "fixed-awaiting-deploy".

**Comment by KatieWoe** [comment]
Looks good in dev.1. Will reopen if any problems are found.
