### ISSUE TITLE
PhET-iO requirements for "Add Mutations" panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#26]
Client requirement from the PhET-iO design doc:

> Each allele in the Mutation panel should be selectable and hideable. The entire panel should also be hideable.

Visibility of the entire panel is supported by common code (`SUN/Panel`).

If "Each allele" really means "Each trait" (Fur, Ears, Teeth), then we are talking about rows in the panel. Each row can be made visible/enabled/pickable by appropriately structuring the scenegraph, and this has been done in the currently implementation.

If "Each allele" means subcomponents of a row, then we have a problem.  We haven't discussed whether any of the subcomponents that make up a row will be instrumented, and if so, what should be read-only.   The look of each row changes as the sim state changes, so giving the client write-access to subcomponents is problematic.

**Comment by amanda-phet** [comment]
>If "Each allele" really means "Each trait" (Fur, Ears, Teeth), then we are talking about rows in the panel. Each row can be made visible/enabled/pickable by appropriately structuring the scenegraph, and this has been done in the currently implementation.

I'm pretty sure this is what the client meant, that they might only want some traits available.

**Comment by pixelzoom** [comment]
12/11/19 design meeting:

Demoed with Studio in 1.0.0-dev.13. This looks good, closing.
