### ISSUE TITLE
String internationalization should not appear in the PhET-iO API

### ISSUE THREAD

**Issue by samreid** [phetsims/natural-selection#260]
In https://github.com/phetsims/phet-io-wrappers/issues/400 it was discovered that this code in Natural Selection:

```js
      const property = new BooleanProperty( visible, {
        tandem: tandem,
        phetioDocumentation: `sets the visibility of all user-interface components related to ${gene.name} for this screen`
      } );
```
is adding internationalized strings into the PhET-iO API.  This can be demonstrated by adding this line of code:

```diff
Index: js/common/view/GenesVisibilityManager.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/js/common/view/GenesVisibilityManager.js b/js/common/view/GenesVisibilityManager.js
--- a/js/common/view/GenesVisibilityManager.js	(revision 1fb6eafd2cd754631e236cdb7b36e04d416b0113)
+++ b/js/common/view/GenesVisibilityManager.js	(date 1615064692334)
@@ -62,6 +62,8 @@
         phetioDocumentation: `sets the visibility of all user-interface components related to ${gene.name} for this screen`
       } );
 
+      console.log( property.phetioDocumentation );
+
       // Set the visibility of UI components related to the gene. unlink is not necessary.
       property.link( visible => {
         addMutationsPanel.setGeneVisible( gene, visible );

```

and running in PhET-iO Standalone with `?locale=hu`.  It prints:

> sets the visibility of all user-interface components related to Metszőfog for this screen

I'll open up another issue to develop tooling to help us detect when i18n strings end up in the API files.  The way we detected it for this issue is described in https://github.com/phetsims/phet-io-wrappers/issues/400 (possibly embedding marks).

This issue is for changing natural selection itself so it doesn't use string translations in the PhET-iO API.

**Comment by pixelzoom** [comment]
Fixed in the above commit. PhET-iO documentation is unchanged. Closing.
