### ISSUE TITLE
Review inputEnabledProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#261]
https://github.com/phetsims/scenery/issues/1158 changed pickableProperty to inputEnabledProperty.   Review this sim's use of inputEnbledProperty.  Locate candidates by searching for `addInputListener`.

**Comment by pixelzoom** [comment]
These sim-specific candidates are candidates for `inputEnabledProperty`:

* `naturalSelection.introScreen.view.environmentNode` - This is the top panel that should the environment and bunnies hopping around. Pressing anywhere other than on a bunny clears the Pedigree graph.
* `naturalSelection.introScreen.view.environmentNode.sprites` - This is the scenery Sprites for the bunnies shown in the environment view. Pressing a bunny shows it in the Pedigree graph.
* naturalSelection.introScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode` - This is the data probe in the Population graph. All parts of it are draggable, and it has a sphere at the bottom to encourage dragging.

@amanda-phet @kathy-phet questions:
(1) Do you want to instrument any of these elements?
(2) Does the look of any of these elements need to change when `inputEnabledProperty` is false? (For example, do we need to hide the sphere at the bottom of the data probe?)

**Comment by kathy-phet** [comment]
I would favor adding it to this node: 
naturalSelection.introScreen.view.environmentNode.sprites - so that if you decide to remove the pedigree chart option, you can also turn off the bunny selection entirely. 

The other two I would not add it to at this point as I cannot think of a condition you would want this behavior. If a client has a reason to want it that we cannot think of right now, then we can add it later.

**Comment by pixelzoom** [comment]
Sounds good to me. @amanda-phet do you agree?

**Comment by amanda-phet** [comment]
Yes that sounds good. 

I was starting to write a case for instrumenting `naturalSelection.introScreen.view.environmentNode` but I changed my mind in the process. I also don't think it's useful to make the data probe not pickable.

**Comment by pixelzoom** [comment]
`*.view.environmentNode.sprites.inputEnabledProperty` has been instrumented. If there is a selected bunny, the selection is cleared when `inputEnabledProperty` is set to false.  

@amanda-phet please review in master.

**Comment by amanda-phet** [comment]
Looks like it is working just fine.
