### ISSUE TITLE
Should environmentNode.visibleProperty be read-only?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#263]
I noticed that `*.environmentNode.visibleProperty` is not currently read-only.  When it's set to false, it looks odd, see screenshot below.  Should it be read-only?

![screenshot_210](https://user-images.githubusercontent.com/3046552/111815781-adaf6f80-88a1-11eb-978c-56844cd09747.png)

**Comment by pixelzoom** [comment]
If for some reason we need to support hiding the environmentNode and everything that's on top of it (clock, radio buttons, push buttons) then we will need to add an additional parent for all of those things.  

Studio tree is currently:

![screenshot_211](https://user-images.githubusercontent.com/3046552/111816258-3cbc8780-88a2-11eb-9d92-94efc9660c6f.png)

That would change to:

```
view
  visibleProperty
  +addMutationsPanel
  +dialogs
  +environmentalFactorsPanel
  +environmentNode
    +environmentRadioButtonGroup
    +generationClock
    +playButtonGroup
  +genes
  +graphs
  +resetAllButton
  +timeControlNode
```

**Comment by amanda-phet** [comment]
Yikes! I don't know how we didn't notice this before when we reviewed studio. Let's definitely make this read-only. I can't think of a reason to want to set `environmentNode.visibleProperty` to false.

**Comment by pixelzoom** [comment]
@amanda-phet what do you think about the restructuring of the Studio tree that I proposed in https://github.com/phetsims/natural-selection/issues/263#issuecomment-802978938?

**Comment by amanda-phet** [comment]
I prefer to not restructure the tree that way. I also think it would be incredibly strange for someone to want to hide the entire environment (or `environmentPanel`) in this sim. Without it, the sim is not very useful.

**Comment by pixelzoom** [comment]
OK, no `environmentPanel`, and n changes to the tree structure. 

I have made `environmentNode.visibleProperty` read-only. @amanda-phet please review in master, then please close.

**Comment by pixelzoom** [comment]
Re the tree structure... @amanda-phet and I discussed this more on Slack.   We discussed how this part of the UI might be interpretted by the instructional designer:

<img width="797" alt="screenshot_923" src="https://user-images.githubusercontent.com/3046552/112064633-e90f9f80-8b28-11eb-8b3d-b2e560945386.png">

Is it a panel, with the clock, radio buttons, and push buttons inside of it - children of the panel in the tree?  Or is it a panel with the clock, radio buttons, and push buttons on top of it - siblings in the tree?  We decided that the former made more sense, and that's the structural change that I describe in https://github.com/phetsims/natural-selection/issues/263#issuecomment-802978938.  

It's a relatively easy change, and is nice structural improvement, so I will make it so.  And `environmentPanel.visibleProperty` will be read-only.

**Comment by pixelzoom** [comment]
@amanda-phet ready for review.  The revised tree structure is shown below.  And these 2 elements are now read-only:

`environmentPanel.visibleProperty`
`environmentPanel.environmentNode.visibleProperty`

<img width="278" alt="screenshot_924" src="https://user-images.githubusercontent.com/3046552/112065232-ebbec480-8b29-11eb-855c-b5aea4965322.png">

**Comment by amanda-phet** [comment]
Looks great! Glad we made the change.
