### ISSUE TITLE
Dominant and recessive traits are the same

### ISSUE THREAD

**Issue by liam-mulhall** [phetsims/natural-selection#265]
<b>Test Device</b>

MacBook Air

<b>Operating System</b>

macOS 11.2.3

<b>Browser</b>

Safari 14.0.3

<b>Problem Description</b>

~On the Lab screen, it looks like both options for the teeth are long teeth. See screenshot below and images pulled from this repo's images directory for comparison.~ It looks like the dominant and recessive traits are the same. Is this how it's supposed to be?

<b>Visuals</b>

In the sim:
![issue](https://user-images.githubusercontent.com/60749003/113935776-2c6a3f00-97b4-11eb-9e2a-a28e49225359.png)

longTeeth.png:
![longTeeth](https://user-images.githubusercontent.com/60749003/113935911-591e5680-97b4-11eb-99fc-eebf5370439f.png)

shortTeeth.png:
![shortTeeth](https://user-images.githubusercontent.com/60749003/113935941-63405500-97b4-11eb-99e8-c6b2b3c5812b.png)

<details>
<summary><b>Troubleshooting Information</b></summary>

Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.3.0-dev.1/phet/natural-selection_all_phet.html
Version: 1.3.0-dev.1 2021-04-05 21:34:10 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/14.0.3 Safari/605.1.15
Language: en-us
Window: 1440x820
Pixel Ratio: 1/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
@liam-mulhall I think you're confused about what's going on here.  Notice that the button have identical icons for all 3 traits.  Those are the icons for the mutant allele (form of the gene). What this control is doing is choosing whether the mutant allele is dominant or recessive. 

If I haven't understood the problem you're reporting, try again.

**Comment by liam-mulhall** [comment]
Ah, I see now. Thanks, @pixelzoom. My brain is a bit fried.

**Comment by pixelzoom** [comment]
No problem!
