### ISSUE TITLE
No second multi sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#267]
For https://github.com/phetsims/QA/issues/636. Seen on both iPad and on Win 10 Chrome.
In the multi wrapper, only the first sim shows up.
<img width="806" alt="nosecondmulti" src="https://user-images.githubusercontent.com/41024075/114472274-29ee5780-9baf-11eb-9910-a7f65329b855.png">

**Comment by pixelzoom** [comment]
@KatieWoe is this different than https://github.com/phetsims/natural-selection/issues/266?

**Comment by KatieWoe** [comment]
I don't think so. I just didn't see that. Sorry. Closing as duplicate
