### ISSUE TITLE
Update credits for 1.3 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#270]
@KatieWoe please let me know who should be added to the credits for the 1.3 release.  Please provide the exact spelling of names. Current credits are shown below:

<img width="653" alt="screenshot_953" src="https://user-images.githubusercontent.com/3046552/115440108-9cbd8b00-a1cc-11eb-8d23-8e623a54b493.png">

**Comment by KatieWoe** [comment]
Please add Devon Quispe

**Comment by KatieWoe** [comment]
Please also add Brooklyn Lash

**Comment by pixelzoom** [comment]
@KatieWoe I've made the requested changes, so labeling this as "fixed", to be testing in the next RC. If you have any more additions before 1.3 is published, please note here and assign back to me.

**Comment by amanda-phet** [comment]
@pixelzoom can you please move Noah Podolefsky to Lead Design. So, the changes are as follows: 

Lead Design: Amanda McGarry, Noah Podolefsky
Team: Wendy Adams, Megan Hoffman, Oliver Nix, Jonathan Olson, Ariel Paul, Kathy Perkins, Carl Wieman 

@kathy-phet and I reviewed a bunch of recent HTML5 ports, and we'd like to keep up the convention of listing the original designer when we do a port. The sims are inconsistent, but let's make this change here.

**Comment by pixelzoom** [comment]
OK, will do.  Removing "ready-for-qa" label.

**Comment by pixelzoom** [comment]
NP is now listed as a lead designer, in master and 1.3 branches.  Ready for QA.

**Comment by KatieWoe** [comment]
No new QA that haven't been mentioned.

**Comment by KatieWoe** [comment]
Looks good in RC.2

**Comment by pixelzoom** [comment]
Thanks, closing.
