### ISSUE TITLE
Studio tree highlighting clears when toggling Featured/All elements

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#272]
https://github.com/phetsims/studio/issues/214 has reappeared. At 4/22/21 phet-io meeting, @kathy-phet said that she would like that evaluated for inclusion in the 1.3 release.  

Assigning to @zepumph @samreid to inform me when it has been fixed, and how to patch the 1.3 branch.

UPDATE from @zepumph: changed the link.

**Comment by arouinfar** [comment]
@pixelzoom I verified the fix in https://github.com/phetsims/studio/issues/214, here's the commit to cherry-pick:

https://github.com/phetsims/studio/commit/c6f4728e6a5ef6b69640c9152090a910788a0fd9

**Comment by pixelzoom** [comment]
No one has summarized what the final behavior is, and I'm not going to spend the time trying to figure that out by reading through https://github.com/phetsims/studio/issues/214.   I'm going to assume that what @samreid described in #issuecomment-825906062 is what you ended up doing.  So I'm just going to patch Natural Selection 1.3, and assume that all is well.

**Comment by pixelzoom** [comment]
I create a new studio branch (natural-selection-1.3) and patched in phetsims/studio@c6f4728.  

I still have some questions about how this is supposed to behave, see https://github.com/phetsims/studio/issues/214#issuecomment-826984877.   On hold until those questions are answered.

**Comment by pixelzoom** [comment]
My questions were answered in phetsims/studio#214, and this seems to be behaving as designed.   So ready for QA.

To verify:

1. Start Natural Selection in Studio.
2. Set "PhET-iO Elements" to "All".
3. Select `naturalSelection.introScreen.model.simulationModeProperty` in the Studio Tree.
4. Set "PhET-iO Elements" to "Featured".
5. Verify that `naturalSelection.introScreen.model` becomes selected in the Studio Tree.
6. Set "PhET-iO Elements" to "All".
7. Verify that `naturalSelection.introScreen.model` remains selected in the Studio Tree.

**Comment by KatieWoe** [comment]
Verified on Win 10 Chrome in rc.2

**Comment by liam-mulhall** [comment]
Also seems to be working on macOS 11 + Chrome.

**Comment by liam-mulhall** [comment]
Also seems to be working on macOS 11 + Safari.

**Comment by KatieWoe** [comment]
And Win 10 Firefox, closing
