### ISSUE TITLE
Review PhET-iO API changes between 1.2 and 1.3

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#275]
When the Diff wrapper is fixed (see https://github.com/phetsims/natural-selection/issues/271),  we'll presumably want to use the Diff wrapper to determine if there were unintended changes between 1.2 and 1.3.   This issue is to review and verify those changes.

**Comment by pixelzoom** [comment]
While I'm waiting to be able to patch the 1.3 branch, I did a diff between 1.2 and master (which should be the same as 1.3).  Below is the set of breaking changes.  It's going to take me hours to go through this.

@kathy-phet @amanda-phet please advise: Do you want the API changes reviewed and verified, to identify any unintended changes that may have been introduced? 

<details>
<summary>diff: 1.2 vs master</summary>

PhET-iO Element missing: naturalSelection.general.controller.input.gotPointerCaptureAction
PhET-iO Element missing: naturalSelection.general.controller.input.lostPointerCaptureAction
naturalSelection.general.controller.input.mouseDownAction.phetioTypeName changed from ActionIO<NullableIO<NumberIO>, Vector2IO, EventIO> to ActionIO<Vector2IO, EventIO>
PhET-iO Element missing: naturalSelection.general.controller.keyStateTracker
PhET-iO Element missing: naturalSelection.general.model.simInfo
PhET-iO Element missing: naturalSelection.general.view.navigationBar.phetButton.phetMenu.visibleProperty
PhET-iO Element missing: naturalSelection.general.view.navigationBar.phetButton.visibleProperty
PhET-iO Element missing: naturalSelection.general.view.panZoomListener
PhET-iO Element missing: naturalSelection.introScreen.model.bunnyCollection.bunnyGroup.bunny_0
PhET-iO Element missing: naturalSelection.introScreen.model.bunnyCollection.deadBunnies.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.bunnyCollection.deadBunnies.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.bunnyCollection.liveBunnies.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.bunnyCollection.liveBunnies.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.bunnyCollection.recessiveMutants.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.bunnyCollection.recessiveMutants.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.brownFurPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.brownFurPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.floppyEarsPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.floppyEarsPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.longTeethPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.longTeethPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.shortTeethPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.shortTeethPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.straightEarsPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.straightEarsPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.totalPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.totalPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.whiteFurPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.populationModel.dataPoints.whiteFurPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.proportionsModel.previousCounts.elementAddedEmitter
PhET-iO Element missing: naturalSelection.introScreen.model.graphs.proportionsModel.previousCounts.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.introScreen.view.environmentPanel
naturalSelection.introScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode.visibleProperty.phetioTypeName changed from LinkedElementIO to PropertyIO<BooleanIO>
PhET-iO Element missing: naturalSelection.introScreen.view.graphs.proportionsNode.proportionsGraphNode.generationSpinner.enabledProperty
naturalSelection.introScreen.view.timeControlNode.fastForwardButton.phetioTypeName changed from NodeIO to RoundMomentaryButtonIO
PhET-iO Element missing: naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_0
PhET-iO Element missing: naturalSelection.labScreen.model.bunnyCollection.deadBunnies.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.bunnyCollection.deadBunnies.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.bunnyCollection.liveBunnies.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.bunnyCollection.liveBunnies.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.bunnyCollection.recessiveMutants.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.bunnyCollection.recessiveMutants.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.brownFurPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.brownFurPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.floppyEarsPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.floppyEarsPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.longTeethPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.longTeethPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.shortTeethPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.shortTeethPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.straightEarsPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.straightEarsPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.totalPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.totalPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.whiteFurPoints.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.populationModel.dataPoints.whiteFurPoints.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.proportionsModel.previousCounts.elementAddedEmitter
PhET-iO Element missing: naturalSelection.labScreen.model.graphs.proportionsModel.previousCounts.elementRemovedEmitter
PhET-iO Element missing: naturalSelection.labScreen.view.environmentPanel
naturalSelection.labScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode.visibleProperty.phetioTypeName changed from LinkedElementIO to PropertyIO<BooleanIO>
PhET-iO Element missing: naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.generationSpinner.enabledProperty
naturalSelection.labScreen.view.timeControlNode.fastForwardButton.phetioTypeName changed from NodeIO to RoundMomentaryButtonIO
PhET-iO Element missing: phetioEngine.phetioElementAddedEmitter
PhET-iO Element missing: phetioEngine.phetioElementRemovedEmitter
PhET-iO Element missing: phetioEngine.phetioElementsBaselineEmitter
PhET-iO Element missing: phetioEngine.phetioTypesAddedEmitter
Type missing: ActionIO<NullableIO<NumberIO>, Vector2IO, EventIO>
Type missing: ActionIO<NumberIO, EventIO>
Type missing: ActionIO<ObjectLiteralIO>
Type missing: ActionIO<ProportionsCountsIO>
Type missing: ActionIO<ReferenceIO<BunnyIO>>
Type missing: ActionIO<StringIO, ObjectLiteralIO, NullableIO<ObjectLiteralIO>>
Type missing: ActionIO<StringIO, StringIO>
Type missing: ActionIO<Vector2IO>
AlleleIO parameter types changed from to ObjectIO. This may or may not be a breaking change, but we are reporting it just in case.
BooleanIO supertype changed from ValueIO to ObjectIO. This may or may not be a breaking change, but we are reporting it just in case.
Type missing: Bounds2IO
DialogIO supertype changed from ReferenceIO<NodeIO> to NodeIO. This may or may not be a breaking change, but we are reporting it just in case.
Method missing, type=EmitterIO<>, method=removeListener
Method missing, type=EmitterIO<NullableIO<SceneryEventIO>>, method=removeListener
Type missing: EmitterIO<ObjectLiteralIO>
Type missing: EmitterIO<ProportionsCountsIO>
Type missing: EmitterIO<ReferenceIO<BunnyIO>>
Type missing: EmitterIO<StringIO, ObjectLiteralIO, NullableIO<ObjectLiteralIO>>
Type missing: EmitterIO<StringIO, StringIO>
Type missing: EmitterIO<Vector2IO>
Type missing: FunctionIO(Bounds2IO)=>VoidIO
Type missing: FunctionIO(Bounds2IO,NullableIO<Bounds2IO>)=>VoidIO
Type missing: FunctionIO(Matrix3IO)=>VoidIO
Type missing: FunctionIO(Matrix3IO,NullableIO<Matrix3IO>)=>VoidIO
Type missing: FunctionIO(ObjectLiteralIO)=>VoidIO
Type missing: FunctionIO(StringIO,ObjectLiteralIO,NullableIO<ObjectLiteralIO>)=>VoidIO
GeneIO parameter types changed from to ObjectIO. This may or may not be a breaking change, but we are reporting it just in case.
Type missing: Matrix3IO
Type missing: NullableIO<Bounds2IO>
Type missing: NullableIO<Matrix3IO>
Type missing: NullableIO<ObjectLiteralIO>
Type missing: ObjectLiteralIO
PhetioEngineIO.addEventListener has different parameter types: FunctionIO(ObjectLiteralIO)=>VoidIO => FunctionIO(ObjectIO)=>VoidIO
PhetioEngineIO.getChangedState has a different return type ObjectLiteralIO => ObjectIO
PhetioEngineIO.getPhetioElementMetadata has a different return type ObjectLiteralIO => ObjectIO
PhetioEngineIO.getState has a different return type ObjectLiteralIO => ObjectIO
PhetioEngineIO.getStateForObject has a different return type NullableIO<ObjectLiteralIO> => ObjectIO
PhetioEngineIO.getValues has a different return type ObjectLiteralIO => ObjectIO
PhetioEngineIO.invokeControllerInputEvent has different parameter types: ObjectLiteralIO => ObjectIO
PhetioEngineIO.setSimStartedMetadata has different parameter types: ObjectLiteralIO => ObjectIO
PhetioEngineIO.setState has different parameter types: ObjectLiteralIO => ObjectIO
PhetioEngineIO.triggerEvent has different parameter types: ObjectLiteralIO => ObjectIO
Type missing: PropertyIO<Bounds2IO>
Type missing: PropertyIO<Matrix3IO>
Type missing: ReferenceIO<NodeIO>
ScreenIO parameter types changed from to ObjectIO. This may or may not be a breaking change, but we are reporting it just in case.
Type missing: SimInfoIO
StringIO supertype changed from ValueIO to ObjectIO. This may or may not be a breaking change, but we are reporting it just in case.
Type missing: ValueIO

</details>

**Comment by pixelzoom** [comment]
Please DO NOT review the diff above.  We just discovered that Diff wrapper has its comparison inverted, see https://github.com/phetsims/phet-io-wrappers/issues/408.  So the above diff results are meaningless.

**Comment by pixelzoom** [comment]
This issue is on hold until #271 (Diff wrapper is broken) is resolved.

**Comment by samreid** [comment]
@zepumph and I used the diff wrapper and our knowledge of recent changes to write this condensed migration guide.  This guide or something like it would be useful to supply to clients that we know are using 1.2.  In the future, we may wish to include migration guides like this into builds, as part of or adjacent to the diff wrapper.

```
Natural Selection 1.2 -> 1.3 Migration guide

naturalSelection.general.controller.input.mouseDownAction.phetioTypeName changed from ActionIO<Vector2IO, EventIO> to ActionIO<NullableIO<NumberIO>, Vector2IO, EventIO>
PhET-iO Element missing: naturalSelection.introScreen.view.environmentNode
PhET-iO Element missing: naturalSelection.introScreen.view.environmentRadioButtonGroup
PhET-iO Element missing: naturalSelection.introScreen.view.generationClockNode
naturalSelection.introScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to LinkedElementIO
PhET-iO Element missing: naturalSelection.introScreen.view.playButtonGroup
naturalSelection.introScreen.view.timeControlNode.fastForwardButton.phetioTypeName changed from RoundMomentaryButtonIO to NodeIO
PhET-iO Element missing: naturalSelection.labScreen.view.environmentNode
PhET-iO Element missing: naturalSelection.labScreen.view.environmentRadioButtonGroup
PhET-iO Element missing: naturalSelection.labScreen.view.generationClockNode
naturalSelection.labScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to LinkedElementIO
PhET-iO Element missing: naturalSelection.labScreen.view.playButtonGroup
naturalSelection.labScreen.view.timeControlNode.fastForwardButton.phetioTypeName changed from RoundMomentaryButtonIO to NodeIO
AlleleIO parameter types changed from ObjectIO to . This may or may not be a breaking change, but we are reporting it just in case.
GeneIO parameter types changed from ObjectIO to . This may or may not be a breaking change, but we are reporting it just in case.

Pickable property have been replaced with inputEnabledProperty
Opacity property has been removed
pressAction and releaseAction became phetioReadOnly

ObservableArrayIO is missing event: itemAdded, please see the emitted event from the elementAddedEmitter
ObservableArrayIO is missing event: itemRemoved, please see the emitted event from the elementRemovedEmitter

Method missing, type=ObservableArrayIO, method=addItemAddedListener, please use elementAddedEmitter
Method missing, type=ObservableArrayIO, method=addItemRemovedListener, please use elementRemovedEmitter
Method missing, type=ObservableArrayIO, method=getLength, please use lengthProperty

Look for corresponding emitters for the following:
Method missing, type=PhetioEngineIO, method=addPhetioElementAddedListener
Method missing, type=PhetioEngineIO, method=addPhetioElementRemovedListener
Method missing, type=PhetioEngineIO, method=addPhetioElementsBaselineListener
Method missing, type=PhetioEngineIO, method=addTypesAddedListener
Method missing, type=PhetioEngineIO, method=endEvent
Method missing, type=PhetioEngineIO, method=startEvent
```

**Comment by pixelzoom** [comment]
Feedback on "condensed migration guide"....

> naturalSelection.general.controller.input.mouseDownAction.phetioTypeName changed from ActionIO<Vector2IO, EventIO> to ActionIO<NullableIO<NumberIO>, Vector2IO, EventIO>
PhET-iO Element missing: naturalSelection.introScreen.view.environmentNode
PhET-iO Element missing: naturalSelection.introScreen.view.environmentRadioButtonGroup
PhET-iO Element missing: naturalSelection.introScreen.view.generationClockNode
PhET-iO Element missing: naturalSelection.introScreen.view.playButtonGroup
PhET-iO Element missing: naturalSelection.labScreen.view.environmentNode
PhET-iO Element missing: naturalSelection.labScreen.view.environmentRadioButtonGroup
PhET-iO Element missing: naturalSelection.labScreen.view.generationClockNode
PhET-iO Element missing: naturalSelection.labScreen.view.playButtonGroup

None of the above elements are missing - they have been relocated.  A new `environmentPanel` element was introduced as an ancestor.  And that's probably what's useful to tell clients in a migraton guide. 

> naturalSelection.introScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to LinkedElementIO
naturalSelection.introScreen.view.timeControlNode.fastForwardButton.phetioTypeName changed from RoundMomentaryButtonIO to NodeIO
naturalSelection.labScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to LinkedElementIO

I have no idea what the above is telling me, or how I'd use it.

> AlleleIO parameter types changed from ObjectIO to . This may or may not be a breaking change, but we are reporting it just in case.
GeneIO parameter types changed from ObjectIO to . This may or may not be a breaking change, but we are reporting it just in case.

"from ObjectIO to ." ?? What does that mean?  

> Pickable property have been replaced with inputEnabledProperty
> Opacity property has been removed

Uppercase "property" please.  And why not `pickableProperty` and `opacityProperty`, which is what the element names were? 

> Method missing, type=ObservableArrayIO, method=addItemAddedListener, please use elementAddedEmitter
Method missing, type=ObservableArrayIO, method=addItemRemovedListener, please use elementRemovedEmitter
Method missing, type=ObservableArrayIO, method=getLength, please use lengthProperty
> 
> Look for corresponding emitters for the following:
Method missing, type=PhetioEngineIO, method=addPhetioElementAddedListener
Method missing, type=PhetioEngineIO, method=addPhetioElementRemovedListener
Method missing, type=PhetioEngineIO, method=addPhetioElementsBaselineListener
Method missing, type=PhetioEngineIO, method=addTypesAddedListener
Method missing, type=PhetioEngineIO, method=endEvent
Method missing, type=PhetioEngineIO, method=startEvent

No idea how what the above is telling me, or how I'd use this info.

So I think this is a good idea in concept.  But if PhET decides to produce a migration guide, it needs to be a little more instructive and informative.

**Comment by samreid** [comment]
I agree it needs to be more instructive and informative, and knowing the sim specific details will help in that regard.

> "from ObjectIO to ." ?? What does that mean?

It changed from having a parameter type of `ObjectIO` to not having a parameter type at all.  I'm sure we can phrase that better.

> Uppercase "property" please. 

Great idea!

All of @pixelzoom comments are good ideas, but it unclear how much time we should spend refining this document, or producing similar documents when this comes up in the future.

**Comment by zepumph** [comment]
@pixelzoom, sorry we weren't clear, we did not try to understand any of the natural-selection specific changes, but were thinking that you would instead apply the same strategy-esque writing that we did for common code.

**Comment by pixelzoom** [comment]
Got it, thanks for clarifying.

**Comment by zepumph** [comment]
>AlleleIO parameter types changed from ObjectIO to . This may or may not be a breaking change, but we are reporting it just in case.
GeneIO parameter types changed from ObjectIO to . This may or may not be a breaking change, but we are reporting it just in case.

After the above commit, these now look like:

AlleleIO parameter types changed from [ObjectIO] to []. This may or may not be a breaking change, but we are reporting it just in case.
GeneIO parameter types changed from [ObjectIO] to []. This may or may not be a breaking change, but we are reporting it just in case.

Most likely this change was because the supertype is parametric now (ReferenceIO<Object>), and so it doesn't have to be.

**Comment by zepumph** [comment]
@pixelzoom, @samreid and I took the above in https://github.com/phetsims/natural-selection/issues/275#issuecomment-827973296 and annotated the rest of it. Here is the updated guide:

```

Natural Selection 1.2 -> 1.3 Migration guide

// model visibleProperty is now passed to view, https://github.com/phetsims/natural-selection/issues/262
naturalSelection.introScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to LinkedElementIO
naturalSelection.labScreen.view.graphs.populationNode.populationGraphNode.dataProbeNode.visibleProperty.phetioTypeName changed from PropertyIO<BooleanIO> to LinkedElementIO

// Removed useless IOType, use parent instead, https://github.com/phetsims/sun/issues/558
naturalSelection.introScreen.view.timeControlNode.fastForwardButton.phetioTypeName changed from RoundMomentaryButtonIO to NodeIO
naturalSelection.labScreen.view.timeControlNode.fastForwardButton.phetioTypeName changed from RoundMomentaryButtonIO to NodeIO

// Used to extend ReferenceIO but now uses IOType.supertype, https://github.com/phetsims/tandem/issues/211
AlleleIO parameter types changed from ObjectIO to . This may or may not be a breaking change, but we are reporting it just in case.
GeneIO parameter types changed from ObjectIO to . This may or may not be a breaking change, but we are reporting it just in case.

// environmentPanel created in the view, https://github.com/phetsims/natural-selection/issues/263
naturalSelection.introScreen.view.environmentNode moved to naturalSelection.introScreen.view.environmentPanel.environmentNode
naturalSelection.introScreen.view.environmentRadioButtonGroup moved to naturalSelection.introScreen.view.environmentPanel.environmentRadioButtonGroup
naturalSelection.introScreen.view.generationClockNode moved to naturalSelection.introScreen.view.environmentPanel.generationClockNode
naturalSelection.introScreen.view.playButtonGroup moved to naturalSelection.introScreen.view.environmentPanel.playButtonGroup
naturalSelection.labScreen.view.environmentNode moved to naturalSelection.labScreen.view.environmentPanel.environmentNode
naturalSelection.labScreen.view.environmentRadioButtonGroup moved to naturalSelection.labScreen.view.environmentPanel.environmentRadioButtonGroup
naturalSelection.labScreen.view.generationClockNode moved to naturalSelection.labScreen.view.environmentPanel.generationClockNode
naturalSelection.labScreen.view.playButtonGroup moved to naturalSelection.labScreen.view.environmentPanel.playButtonGroup

// pickableProperty have been replaced with inputEnabledProperty
. . . 

// opacityProperty has been removed
. . .

// pressAction and releaseAction became phetioReadOnly
. . .

// ObservableArray events/methods now are in sub-emitters
ObservableArrayIO is missing event: itemAdded, please see the emitted event from the elementAddedEmitter
ObservableArrayIO is missing event: itemRemoved, please see the emitted event from the elementRemovedEmitter
Method missing, type=ObservableArrayIO, method=addItemAddedListener, please use elementAddedEmitter
Method missing, type=ObservableArrayIO, method=addItemRemovedListener, please use elementRemovedEmitter
Method missing, type=ObservableArrayIO, method=getLength, please use lengthProperty

// Look for corresponding sub-emitters in phetioEngine for the following:
Method missing, type=PhetioEngineIO, method=addPhetioElementAddedListener
Method missing, type=PhetioEngineIO, method=addPhetioElementRemovedListener
Method missing, type=PhetioEngineIO, method=addPhetioElementsBaselineListener
Method missing, type=PhetioEngineIO, method=addTypesAddedListener
Method missing, type=PhetioEngineIO, method=endEvent
Method missing, type=PhetioEngineIO, method=startEvent

// mouseDownAction parameter signature changed to support fix in https://github.com/phetsims/natural-selection/issues/264:
naturalSelection.general.controller.input.mouseDownAction.phetioTypeName changed from ActionIO<Vector2IO, EventIO> to ActionIO<NullableIO<NumberIO>, Vector2IO, EventIO> changed a parameter

```

**Comment by pixelzoom** [comment]
I added some misisng issue numbers to the migration guide in the previous commit, so that all changes are documented with a GitHub issue.  

All of the diffs reported appear to be intended and accounted for, so I don't see any reason to have @amanda-phet and @kathy-phet review this.  I'll close this issue and proceed with the next RC.
