### ISSUE TITLE
method of specifying query parameters in Studio

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#28]
This sim will have some very complicated query parameters that are related to client requirements. For example, https://github.com/phetsims/natural-selection/issues/9 for specifying the initial population.

There have been multiple references to a “query parameter UI” (for phet and phet-io brands).  I asked the PhET-iO team about this, and they referred me to https://github.com/phetsims/joist/issues/576.  That work is not specific to PhET-iO or Studio, it does not appear to be prioritized, and there is no milestone for completing it.  

The current approach (being used in EFAC) involves no UI per se.  The client manually adds query parameters to the URL, which will then be passed through to the sim by Studio.  So start the sim in Studio, edit the URL to add query parameters, and reload the sim. Optionally bookmark your URL if you expect to need that configuration again. 

Is this manual solution acceptable for Natural Selection?  Is any confirmation with the client needed?

**Comment by ariel-phet** [comment]
IMO the manual solution is absolutely acceptable.

Although a UI will be a longterm solution for both iO and PhET brand, the scope of that work seems beyond what is needed for now.

**Comment by amanda-phet** [comment]
I think the manual solution will be fine, and I don't think we need to confirm this with the client.

**Comment by amanda-phet** [comment]
12/11/19 meeting decision: manual query parameters are fine.
