### ISSUE TITLE
Short strings misalign Add Mutation panel buttons

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#281]
**Test device**
Dell
**Operating System**
Win 10
**Browser**
Chrome
**Problem description**
Found in https://github.com/phetsims/QA/issues/644. Found in published Sim.
With short string, the buttons in the Add Mutation Panel are pushed to the left and close together.
**Steps to reproduce**
1. Use `stringTest=X` parameter

**Visuals**
<img width="163" alt="stringtest_short" src="https://user-images.githubusercontent.com/41024075/120677936-d680e300-c454-11eb-823c-9362776ff507.png">
<img width="160" alt="stringtest_normal" src="https://user-images.githubusercontent.com/41024075/120677939-d7197980-c454-11eb-9334-800cad3c7193.png">

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.3.0-rc.3/phet/natural-selection_all_phet.html
Version: 1.3.0-rc.3 2021-04-28 22:00:28 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36
Language: en-US
Window: 1280x658
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by pixelzoom** [comment]
@KatieWoe I don't folllow, please clarify. What exactly do you think is misaligned? 

The title of this issue indicates that the buttons are misaligned, and I don't see a problem with the buttons.  The column headings need to be centered over the buttons, and that looks fine with stringTest.

Or maybe you're referring to the horizontal alignment of the Mutation icon (yellow circle)? There is no requirement that the Mutation icon be horizontally centered on the 'X' above it (the title) and the 'X' below it (gene name).  See examples from various languages below. 

<img width="233" alt="screenshot_1007" src="https://user-images.githubusercontent.com/3046552/120681647-d387f180-c458-11eb-9b04-f312a0848478.png">
<img width="238" alt="screenshot_1008" src="https://user-images.githubusercontent.com/3046552/120681656-d5ea4b80-c458-11eb-9dac-fc52c1cc1b74.png">
<img width="230" alt="screenshot_1009" src="https://user-images.githubusercontent.com/3046552/120681665-d8e53c00-c458-11eb-9629-a7302f38a71c.png">

**Comment by KatieWoe** [comment]
I mean that the buttons are further to the left and it leaves a large amount of white space on the right, which looked misaligned to me.

**Comment by pixelzoom** [comment]
The control panels in this sim are designed to be fixed-width, and are supposed to fill the negative space to the right of the charts.  And elements in the panels are supposesd to be left aligned.  So... it's behaving as requested, whitespace has to be put somewhere, it's not affecting usability, and having something as short as "X" never occurs in reality.  Arabic (see screenshot above) is about as short as it gets, and in context it looks fine.   

So thanks for reporting. But I'm going to close this was "won't fix".
