### ISSUE TITLE
Playback fails to load

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/natural-selection#283]
### Test Device

Windows 10 Laptop

### Operating System

Widows 10

### Browser

Chrome 

### Problem Description
For https://github.com/phetsims/QA/issues/659

Currently, the playback wrapper fails to load in the exact same manner as in https://github.com/phetsims/gravity-and-orbits/issues/387

### Visuals

![2021-06-18NoplaybackIssue](https://user-images.githubusercontent.com/54685448/122624667-8dd54680-d05e-11eb-89c0-1869b7deb506.PNG)

**Comment by KatieWoe** [comment]
This issue is fixed on master. Though https://github.com/phetsims/phet-io-wrappers/issues/420 may still be an issue, as it is seperate.

**Comment by samreid** [comment]
Closing since this issue is fixed on master, and we don't need any cherry-picks.

**Comment by pixelzoom** [comment]
@samreid Please confirm that is fixed and can be closed.  It looks like it was addressed in the context of https://github.com/phetsims/gravity-and-orbits/issues/387, but I’m unclear if there is anything sim-specific that still needs to be addressed.
