### ISSUE TITLE
Pedigree alleles have inconsistent string lengths

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#285]
**Test device**
Dell and Lovelace
**Operating System**
Win 10 and ChromeOS
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/QA/issues/662. In published. May not be worth fixing.
The alleles for recessive fur and teeth are larger than the others when strings are doubled.
**Steps to reproduce**
1. Go to the second screen with `?stringTest=double`
2. Add mutations to all of the traits
3. Look at the legend in the pedigree graph

**Visuals**
<img width="119" alt="oddsizes" src="https://user-images.githubusercontent.com/41024075/123704937-7d258d00-d823-11eb-9a32-46bab33696ee.png">

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Natural Selection‬:‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.4.0-rc.1/phet/natural-selection_all_phet.html?stringTest=double
Version: 1.4.0-rc.1 2021-06-21 23:54:30 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.114 Safari/537.36
Language: en-US
Window: 1280x657
Pixel Ratio: 1.5/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by pixelzoom** [comment]
Allele abbreviations are single characters, so this is not a problem that will occur in practice.  Unfortunately we currently have no way to enforce "single character"  via Rosetta, so it's possible (though unlikely) that someone could use more than 1 character.   If that happens, then this is behaving correctly, as this stringTest demonstrates.

So... Closing at "won't fix".
