### ISSUE TITLE
Mutation Coming disabled if Add Mutation button is hidden

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#287]
**Device**
Dell
**OS**
Win
**Browser**
Chrome
**Problem Description**
For https://github.com/phetsims/QA/issues/662. Feel free to close if this is intended behavior, but it seemed odd to me.
In Studio, if you add a mutation, but it hasn't appeared, and then you hide that mutation button (such as with `naturalSelection.labScreen.view.addMutationsPanel.teethRow.visibleProperty`) the mutation is canceled and isn't added in the next generation. This doesn't seem to cause a problem in the mutation is already introduced.
**Visuals**
![goesawaywhenhidden](https://user-images.githubusercontent.com/41024075/124006710-d31b4180-d997-11eb-9dc3-3499b78dc81f.gif)

**Comment by KatieWoe** [comment]
Not sure if it is a bug, feel free to remove if not. I did also notice that hiding the gene didn't seem to remove the line from the graph. You would have to disable that line first, then hide the gene.
<img width="959" alt="stillingraph" src="https://user-images.githubusercontent.com/41024075/124010268-da444e80-d99b-11eb-9578-2dbb2985a157.png">

**Comment by KatieWoe** [comment]
If you hide the whole panel, this visual oddity happens.
<img width="698" alt="maybemoreodd" src="https://user-images.githubusercontent.com/41024075/124011444-41163780-d99d-11eb-8b71-640b7ea8c0a4.png">

**Comment by pixelzoom** [comment]
As @amanda-phet said, this is a strange use of Studio.  It's also not a supported use of this feature - you can't schedule a mutation to occur, hide the mutation, and expect what you scheduled to be cancelled.   Showing/hiding a mutation (or the Add Mutation panel) is something that is configured for the screen, and there's no pedagogical reason to change it after configuration.   So...  Closing as "won't fix".
