### ISSUE TITLE
Long strings cause next/previous generation buttons to shrink

### ISSUE THREAD

**Issue by stemilymill** [phetsims/natural-selection#290]
**Test device**
Chromebook, Dell laptop

**Operating System**
Chrome OS, Win10

**Browser**
Chrome, Firefox
Chromebook : 90.0.4430.218
windows chrome: 91.0.4472.124
firefox: 89.0.2

**Problem description**
For https://github.com/phetsims/QA/issues/662

Minor issue which likely would not occur in real-life use
Using query parameter stringTest=long causes scroll buttons for next/previous generation to shrink along with font size in Proportions graph panel

Occurs in published and phet-io versions

**Steps to reproduce**
go to https://phet-dev.colorado.edu/html/natural-selection/1.4.0-rc.1/phet/natural-selection_all_phet.html
use query ?stringTest=long
Enter either Intro or Lab screen
Click "Add a Mate"
Select "Proportions" radio button

**Visuals**

![Screenshot 2021-07-01 122547](https://user-images.githubusercontent.com/85511101/124171525-b144bc00-da76-11eb-81cf-45ab93d42d58.jpg)

Expected:
![Screenshot 2021-07-01 135919](https://user-images.githubusercontent.com/85511101/124171764-fa950b80-da76-11eb-84af-c489af7712e2.jpg)

Note: "Fur" checkbox remains same size with long string
Scroll buttons remain the original size in the Population graph panel regardless of string length

![Screenshot 2021-07-01 142004](https://user-images.githubusercontent.com/85511101/124172157-7c853480-da77-11eb-8fd9-bc5157d7391e.jpg)

<details>
<summary>Troubleshooting information:</summary>
<br>
!!!!! DO NOT EDIT !!!!!

Name: ‪Natural Selection‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.4.0-rc.1/phet/natural-selection_all_phet.html
Version: 1.4.0-rc.1 2021-06-21 23:54:30 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 
Safari/537.36
Language: en-US
Window: 1418x688
Pixel Ratio: 1.3541666269302368/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
Thanks for reporting @stemilymill.

PhET convention is to size the radio buttons to match the height of the text.  So this is behaving as expected.   And this presents no usability problem, because in reality the strings will never be this long. 

So closing as "won't fix".
