### ISSUE TITLE
Update QA credits for 1.4 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#291]
@KatieWoe please provide any QA credit updates for the 1.4 release.

**Comment by KatieWoe** [comment]
Emily Miller should be added.

**Comment by pixelzoom** [comment]
Emily Miller was added to QA credits in master and 1.4 branches.

**Comment by KatieWoe** [comment]
Looks good in rc.2. If anyone else needs to be added after this round I'll let you know.

**Comment by KatieWoe** [comment]
Nancy Salpepi should be added after the third RC

**Comment by pixelzoom** [comment]
Since another RC is not needed, and we're ready to publish, changing the credits creates a bit of a dilemma.  After patching the credits in the 1.4 branch, should I (a) test myself, then publish, or (b) create another RC spot-check, have the credits verified by QA, then publish?   I consulted with @KatieWoe, and we decided on (a).

<details>
<summary>Slack discussion</summary>

Chris Malley  1:32 PM
Re adding to the QA credits for NS 1.4…. Are you OK with me just adding that in NS 1.4, testing myself, then publishing? Or would you like to do an RC spot-check of 1.4.0-rc.4, with the credits change as the only issue to verify?  And what have other devs been doing in this situation, where RC testing is done, and an additional QA credits change needs to be made?

Kathryn Woessner  1:33 PM
That works since changing the about page is all that needs to be done. That tends to be what other devs do as well

Chris Malley  1:33 PM
OK. So test myself, then publish?

Kathryn Woessner  1:34 PM
Yup!

</details>

**Comment by pixelzoom** [comment]
Credits have been updated in master and the 1.4 branch, see below.   I will now close this issue, and publish 1.4.0.

<img width="669" alt="screenshot_1083" src="https://user-images.githubusercontent.com/3046552/126834447-242875fa-0ef0-464e-b91f-d4687abbf975.png">
