### ISSUE TITLE
Long screen names push navigation bar icon to the right when sim is launched 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#295]
For https://github.com/phetsims/QA/issues/662. https://github.com/phetsims/joist/issues/725 is a problem in the natural-selection 1.4 branch.  Blocking because it impacts usability of the navigation bar.

**Comment by pixelzoom** [comment]
Assigning to @jonathanolson, because he's responsbile for the blocking issue https://github.com/phetsims/joist/issues/725.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/joist/issues/725#issuecomment-879274934, the commits to cherry-pick (in this order) are:

https://github.com/phetsims/joist/commit/321e7888eb9feb56133d98f6d35db079678fc7bb
https://github.com/phetsims/joist/commit/58fd74142ca8144982ecc13df4abeab6fa946280
https://github.com/phetsims/joist/commit/6299e69d256f1d997832f5b8d4f88ac50ae5ad08
https://github.com/phetsims/joist/commit/eb2a5d97cd2fe4196f5e98e84ad681c49aaf7a75
https://github.com/phetsims/joist/commit/720b149991e62d7ccfa11f1fb97fe1a3879d038f
https://github.com/phetsims/joist/commit/33aab76edf4019b34a23ace105389ae787c251a3

https://github.com/phetsims/scenery/commit/f0adaceb9b2d8f0420258c1dc65bb94def77c1bd
https://github.com/phetsims/scenery/commit/7656bb0fda91e7f78b8e21ddd77bd404f4568e84
https://github.com/phetsims/scenery/commit/aa0952dc985575aa52f75316b222721b9dd6206b

**Comment by pixelzoom** [comment]
Cherry-picked the above shas, in order, without any problems.  Tested a local build by:

1. Lauch the sim in Studio
2. Change the value of `naturalSelection.introScreen.nameProperty` to "Into The Spiderverse"
3. Press the "Preview Sim" button. Verify that the screen name looks correct in the navbar and home screen.

Ready for testing in the next RC.

**Comment by KatieWoe** [comment]
Looks good in rc.2
