### ISSUE TITLE
triage Unfuddle tickets

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#3]
The active Unfuddle tickets are:

https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2189
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/2340
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3566
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3775
https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3731

**Comment by amanda-phet** [comment]
I reviewed all of these and made notes/questions for brainstorming meetings. Do I need to do anything with the actual unfuddle tickets?

**Comment by pixelzoom** [comment]
I'm not totally clear on the process either (or if there is one).  But ideally, I think that any Unfuddle issues that will be pursued should be transferred to GitHub.  And all Unfuddle issues should be closed.

**Comment by amanda-phet** [comment]
I closed the issues, since we have already discussed the changes we are planning to make in the HTML5 version of the sim. 

I left one open because I noticed the same teacher emailed twice about an issue and I'd like to email him once the port is published. I'll make a new issue for it.
