### ISSUE TITLE
Support items marked as DELETED in the Studio save file

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#300]
For https://github.com/phetsims/qa/issues/662

This is issue https://github.com/phetsims/studio/issues/223, related to the Studio console message that I reported in https://github.com/phetsims/natural-selection/issues/298#issuecomment-875047308.

It's unclear whether this is blocking for NS 1.4.  From https://github.com/phetsims/studio/issues/223#issuecomment-875086340:
> @zepumph can you recommend how to proceed here? Should this block NS RC2?

So I'll err on the side of caution, and label as blocking.

**Comment by pixelzoom** [comment]
In https://github.com/phetsims/studio/issues/223#issuecomment-875766700, @zepumph said:
> After going through this with @samreid, I committed the fix above. The only one to cherry-pick is https://github.com/phetsims/studio/commit/fb832741ae9353f349a8796b9f755a92d0a73eb5. Over to @samreid and @pixelzoom to cherry pick into their own sims (unassign or close this issue when complete, or if you will continue in your own, sim-specific issues.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/studio/issues/223#issuecomment-875818527:

> Steps to reproduce:
> 
> * Launch the sim in Studio with `?secondsPerGeneration=1`
* Press the "Add a Mate" button
* Check the "Limited Food" checkbox
* Run until generation 20
* Pause the sim
* Press  the "Preview Sim" button.
* Go back to the Studio tab and open Dev Tools. Verify that you don't see this message in the console: `state could not be computed as initialState + changedState, storing.`

**Comment by pixelzoom** [comment]
Cherry-picked and patched:

```
% cd perennial
% grunt checkout-target --repo=natural-selection --target=1.4
% cd studio
% git checkout natural-selection-1.4
% git cherry-pick fb832741ae9353f349a8796b9f755a92d0a73eb5
% cd natural-selection
% grunt --brands=phet-io
// test
% cd studio
% git push origin natural-selection-1.4
% cd natural-selection
% cp build/phet-io/dependencies.json .
% git add dependencies.json 
% git commit -m ...
% git push origin 1.4
```

Ready for testing in the next 1.4 RC.

**Comment by pixelzoom** [comment]
To verify in RC testing, see the steps in https://github.com/phetsims/natural-selection/issues/300#issuecomment-875851038.

**Comment by KatieWoe** [comment]
This is impacted by https://github.com/phetsims/natural-selection/issues/298#issuecomment-881757317 as well. What @samreid said in https://github.com/phetsims/natural-selection/issues/298#issuecomment-882738797 makes me think this might be related. Assigning him for that. I didn't see `state could not be computed as initialState + changedState, storing.` but this may be due to this bug, so I won't mark as fixed.

**Comment by samreid** [comment]
@zepumph and I addressed the new problem in https://github.com/phetsims/natural-selection/issues/303, it should also be cherry picked and tested.

**Comment by pixelzoom** [comment]
Even though it sounds like https://github.com/phetsims/natural-selection/issues/303 is a new issue, this issue has technically not been signed off by QA.  So I'll keep this issue open for verification in the next RC.

**Comment by Nancy-Salpepi** [comment]
Could not reproduce using "Steps to Reproduce" in https://github.com/phetsims/natural-selection/issues/300#issuecomment-875851038.  (Mac 11 w/M1 chip + chrome)
