### ISSUE TITLE
Use STATE_SCHEMA to limit IOType boilerplate

### ISSUE THREAD

**Issue by zepumph** [phetsims/natural-selection#305]
Over in https://github.com/phetsims/phet-io/issues/1782, I finally got to cleaning up how stateSchema duplicates much of how applyState and toStateObject are most likely implemented.

In this sim specifically, I found 2 potential problems with just blowing away the toStateObject and the applyState methods on Bunny.js

* There was documentation associated with each, specific to parts of the implementation. Perhaps this could be moved to the declaration of the STATE_SCHEMA
* There is a side effect in applyState, to validateInstance. I went with using the new feature as a "library" function instead of using the framework in IOType to do it automatically (both are supported).

Note that the `required` calls are redundant because there is a lot of type validation that is done for anything in the state schema, both for applyState and toStateObject.

**Comment by zepumph** [comment]
@pixelzoom, would you please review the above commit. If you feel like the `validateInstance` isn't actually needed, then you can delete the entire applyState function and the IOType will automatically grab it from `StateSchema.defaultApplyState`.

**Comment by pixelzoom** [comment]
I'm going to leave the call to `validateInstance` in Bunny `applyState`.  It's a useful additional layer of protection again PhET-iO regressions, and it's a pattern that I've used throughout Natural Selection.  But thanks for bringing this to my attention.  Closing.
