### ISSUE TITLE
Error message when loading older version into Studio

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/natural-selection#310]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
Safari

**Problem description**
For https://github.com/phetsims/qa/issues/818, when loading a saved state from the older version (1.4) into Studio version 1.5, an error appears in the console. I didn't see this error when testing Gravity and Orbits https://github.com/phetsims/qa/issues/816. 
After a quick check things seem to be working OK except for additional errors that appear in console when I press the Reset All button (I will post in separate issue). 

**Steps to reproduce**
1. In Studio version 1.4, select the intro screen and press the Save button
2. Open Studio version 1.5.0-dev.1 and open the console. 
3. Load the saved sim

**Visuals**
<img width="500" alt="Screen Shot 2022-07-07 at 1 22 08 PM" src="https://user-images.githubusercontent.com/87318828/177836447-794e9475-9a0e-4968-b025-8e8942b02aa2.png">

**Comment by pixelzoom** [comment]
This is outside of my wheelhouse, and (presumably) related to migration from older versions. Assigning to @zepumph and @samreid.

**Comment by zepumph** [comment]
This is an expected new part of migration and credentials. We always try to request without credentials, and if we get back a 401 (credentials needed), then we request again with the credentials. Please update QA doc appropriately with this pattern. Feel free to close.
