### ISSUE TITLE
Console errors when pressing Reset All after loading saved state

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/natural-selection#311]
**Test device**
MacBook Air (m1 chip)

**Operating System**
macOS 12.4

**Browser**
safari

**Problem description**
For https://github.com/phetsims/qa/issues/818, after loading a saved state (from version 1.5 or version 1.4), pressing the Reset All button results in console errors. After a quick check, the sim seems to be working correctly after the errors appear. 

**Steps to reproduce**
1. In Studio version 1.5.0-dev.1, select the Intro screen.
2. Open the console
3. Save the state (Feel free to make changes to the sim, but not necessary)
4. Load the saved state into Studio version 1.5.0-dev.1
5. Press the Reset All button

**Visuals**
<img width="500" alt="Screen Shot 2022-07-07 at 1 08 09 PM" src="https://user-images.githubusercontent.com/87318828/177841860-66bf3bfe-e5ea-4e60-8a6d-7f08b99133b9.png">

**Comment by pixelzoom** [comment]
As with #310... This is presumably related to migration, so assigning to @zepumph and @samreid.

**Comment by zepumph** [comment]
This is not specific to migration, you can also reproduce this by loading in a saved file from the same version. It is most likely a regression from https://github.com/phetsims/tandem/issues/264. I'll take a look.

**Comment by Nancy-Salpepi** [comment]
Looks fixed @zepumph! 
Closing

**Comment by pixelzoom** [comment]
@Nancy-Salpepi Sounds like you meant to close this issue, so I'll do so.
