### ISSUE TITLE
Inconsistency when setting state while fast forwarding

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/natural-selection#312]
**Test device**
Dell
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/818.
In the state wrapper, if you hold down the fast forward button in the top sim while the sim is paused, one of the states set in the bottom sim will be un paused. While holding down the button, the bottom sim will behave like the top one. Once you let go, the next state will have the bottom sim playing, instead of paused. The state after that will be correct. This may not be worth addressing, but recording here.
**Steps to reproduce**
1. Go to the state wrapper and make sure state is automatically set every second or so (default)
2. In the top sim go to the first screen
3. Add a bunny
4. Pause the sim
5. Hold down the forward button and observe bottom sim
6. Let go of forward button and observe bottom sim

**Visuals**
![stateoff](https://user-images.githubusercontent.com/41024075/177881050-ef329f73-0f80-4ce7-921e-8bcb7d848495.gif)

**Comment by pixelzoom** [comment]
Dev test https://github.com/phetsims/qa/issues/818 is completed, and this is the only issue that has not been addressed.  I'm not clear on whether we're in a hurry (or even ready) to create a release branch.

**Comment by samreid** [comment]
I committed a proposed fix, @KatieWoe can you please review on phettest?

**Comment by samreid** [comment]
Thanks, since this was reported in a dev test, it seems ready for the next version.  Closing.

**Comment by pixelzoom** [comment]
Thanks for handling this. Looks good.
