### ISSUE TITLE
Update QA credits for 1.5 release.

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#316]
Update QA credits for 1.5 release.
```[tasklist]
### Tasks
```

**Comment by pixelzoom** [comment]
Please indicate whether any updates are needed for https://github.com/phetsims/qa/issues/967, then assign back to me.

**Comment by Nancy-Salpepi** [comment]
Please add Clifford Hardin and Jaron Droder to QA credits.

**Comment by pixelzoom** [comment]
Please indicate whether any updates are needed for https://github.com/phetsims/qa/issues/968, then assign back to me.

**Comment by pixelzoom** [comment]
Please indicate whether any updates are needed for https://github.com/phetsims/qa/issues/971, then assign back to me.

**Comment by KatieWoe** [comment]
No new credits for rc.2

**Comment by pixelzoom** [comment]
We're ready for production deploy of 1.5.0, so closing this issue.
