### ISSUE TITLE
Should `allelesVisible` be settable via a Property?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#317]
In https://github.com/phetsims/studio/issues/268, it was determined that using query parameters with wrappers is problematic, and that setting a Property (or calling an API function) should be preferred.

The `allelesVisible` query parameter determines whether the Alleles panel is added to the Pedigree graph. It does not have an associated Property or API function.

With `allelesVisible=true` (the default):

<img width="574" alt="screenshot_1806" src="https://user-images.githubusercontent.com/3046552/186018016-cd6ae408-2c24-4995-8b31-00358792685c.png">

With `allelesVisible=false`:

<img width="580" alt="screenshot_1805" src="https://user-images.githubusercontent.com/3046552/186018062-1f365da6-e28f-4cf7-91f3-050432a42b2c.png">

If you run the sim with `allelesVisible=false`, changing the value of `graphs.pedigreeNode.visibleProperty` does not affect the visibility of the panel.  The panel is added to the scenegraph only when `allelesVisible=true`.

Is this OK?  Or do we need to add `allelesVisibleProperty` so that the client can change this from Studio, instead of using the query parameter?

Propority high, because Natural Selection is up next for https://github.com/orgs/phetsims/projects/44.

**Comment by pixelzoom** [comment]
I invetigated this a bit.  Being able to dynamically show/hide the Alleles panel is going to be a big project, because the Pedigree graph is not implemented to have dynamic size.  Everything about the layout of the Pedigree graph is static, and making it dynamic is going to be a big project.  An alternative would be to make the Pedigree the same size, regardless of whether the Alleles panel is visible, leaving a big empty spae to the left.  But presumably we would like the Pedigree graph to use that available space.

**Comment by pixelzoom** [comment]
@kathy-phet and I discussed this a bit.  Her feeling was that this is OK as is, and I agree.  If the client wants to hide the Alleles panel and maximize the space used for the Pedigree graph, then they should use the `allelesVisible` query parameter.  If they want to dynamically show/hide the AllelesPanel for some reason (and we had a difficult time thinking of a reason) then they can use the `pedigreeNode.allelesPanel.visibleProperty` and live with a bit of blank space to the right of the graph.   

@amanda-phet please comment. And if our conclusion is OK with you, please close.

**Comment by amanda-phet** [comment]
Sounds good to me.
