### ISSUE TITLE
element name for ...pedigreeModel.earsAllelesVisibleProperty

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#32]
From https://github.com/phetsims/natural-selection/issues/30#issuecomment-566708654:

> **Model**
> ...
> We noticed that the alleles checkbox property is named `naturalSelection.labScreen.model.pedigreeModel.earsAllelesVisibleProperty`.

**Comment by pixelzoom** [comment]
There 3 checkboxes in the Alleles panel, and therefore 3 Properties. Those Properties are: 

`naturalSelection.labScreen.model.pedigreeModel.furAllelesVisibleProperty`
`naturalSelection.labScreen.model.pedigreeModel.earsAllelesVisibleProperty`
`naturalSelection.labScreen.model.pedigreeModel.teethAllelesVisibleProperty`

... and they determine whether the allele abbreviations for a trait appear in the Pedigree graph.  For example, if `furAllelesVisibleProperty` is true, then 'F' and 'f' will appear in the genotype labels for bunnies in the Pedigree graph.

Those Properties are also linked to each checkbox that appears under `naturalSelection.labScreen.view.pedigreeNode.allelesPanel`.

What would you do differently here?

**Comment by amanda-phet** [comment]
That was related to (1) in that issue, now #31 . 

I listed the two instances of checkbox states (checked/unchecked) and noted that they have different formats. `earsAllelesVisibleProperty` is more consistent with other sims (@kathy-phet is more familiar with the other instrumented sims and how they handle checkbox states).

**Comment by pixelzoom** [comment]
@amanda-phet I don't follow.  How are checkboxes for environmental factors (which control whether those factors are enabled) related to the checkboxes for alleles (which control visibility of alleles)?  Are you saying that you expect their Properties to be named "enabled" or "visible" in all cases?  That is not the case -- a checkbox can be associated with _any_ boolean Property.  And "enabled" and "visible" are different boolean states, with different semantics and (therefore) different Property names.

**Comment by pixelzoom** [comment]
12/19/19 design meeting: OK as is.
