### ISSUE TITLE
PhET-iO design review for 1.5 release

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#323]
#319 (add support for dynamic locale) is requiring a large number of API changes.  And there are many API changes and additions that have been added to common code (e.g. Preferences dialog).  It's impossible for me to enumerate the changes.  So this sim will need a full PhET-iO design review by @amanda-phet and @kathy-phet.

Hold off on this until #319 and other PhET-iO development work has been completed.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet the portion of the design related to support for dynamic local (https://github.com/phetsims/natural-selection/issues/319) is ready for review.

**Comment by pixelzoom** [comment]
In 9/1/2022 design meeting, @kathy-phet said that design review should preceed migration rules #324.  So this is ready for review.

**Comment by pixelzoom** [comment]
Related to https://github.com/phetsims/tandem/issues/267 ... Tandem names for all `Text` nodes now have a "Text" suffix, for example "labelText", "titleText".   This is an API change. See above commits.

**Comment by zepumph** [comment]
We looked here during PhET-iO meeting today to see where the progress currently was.

**Comment by arouinfar** [comment]
This simulation is not a current PhET-iO design priority, so unassigning.

**Comment by arouinfar** [comment]
I've completed my design review and identified only a few (mostly minor) issues which are tagged above. The remaining design work pertains to examples.md, which is being tracked in #346, so I will close this issue.
