### ISSUE TITLE
ScreenView `visibleProperty` should not be featured

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#332]
Noticed when migrating overrides.js into code for #331.

In natural-selection-overrides.js, I see that the `visibleProperty` of both ScreenViews is featured:

```ts
    "naturalSelection.introScreen.view.visibleProperty": {
      "phetioFeatured": true
    },
    "naturalSelection.labScreen.view.visibleProperty": {
      "phetioFeatured": true
    }
```

This seems odd, because
* these `visiblePropety`elements are `phetioReadOnly: true`
* no other sims feature this Property (search all overrides.js for "Screen.view.visibleProperty" to confirm)

@amanda-phet was this intentional, or is this a bug?  I recommend not featuring these elements.

**Comment by amanda-phet** [comment]
I have no recollection of featuring this, and can't understand why it's featured (being read-only). Please un-feature!

**Comment by pixelzoom** [comment]
Done in the above commits. Closing.
