### ISSUE TITLE
Missing feature for `playButtonGroup.visibleProperty` in Lab screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#334]
Noticed when migrating overrides.js into code for https://github.com/phetsims/natural-selection/issues/331.

In natural-selection-overrides.js, I see:

```ts
    "naturalSelection.introScreen.view.environmentPanel.playButtonGroup.visibleProperty": {
      "phetioFeatured": true
    },
```

This is for the Intro screen.  I do not see the corresponding `playButtonGroup.visibleProperty` for the Lab screen.  This seems like a bug.   

@amanda-phet should `playButtonGroup.visibleProperty` be featured for both screens? Or did you have a reason for featuring it only in the Intro screen?

**Comment by amanda-phet** [comment]
Looking at this again, I'm not sure why I featured this. I can't think of a good use-case for hiding this button. Please un-feature.

**Comment by pixelzoom** [comment]
Done in the above commits. `playButtonGroup.visibleProperty` is now `phetioFeatured: false` in both screens.
