### ISSUE TITLE
Should `visibleProperty` of the Proportions graph columns be featured? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#335]
Noticed when migrating overrides.js into code for https://github.com/phetsims/natural-selection/issues/331.

In natural-selection-overides.js:

```ts
    "naturalSelection.introScreen.view.graphs.proportionsNode.proportionsGraphNode.columns.earsColumn.visibleProperty": {
      "phetioFeatured": true
    },
    "naturalSelection.introScreen.view.graphs.proportionsNode.proportionsGraphNode.columns.furColumn.visibleProperty": {
      "phetioFeatured": true
    },
    "naturalSelection.introScreen.view.graphs.proportionsNode.proportionsGraphNode.columns.teethColumn.visibleProperty": {
      "phetioFeatured": true
    },
    "naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.columns.earsColumn.visibleProperty": {
      "phetioFeatured": true
    },
    "naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.columns.furColumn.visibleProperty": {
      "phetioFeatured": true
    },
    "naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.columns.teethColumn.visibleProperty": {
      "phetioFeatured": true
    },
```

This features the `visibleProperty` of each column in the Proportions graph:

<img width="479" alt="screenshot_2505" src="https://user-images.githubusercontent.com/3046552/236651671-f30cf6e6-1c39-45af-9d55-575d495dd8a8.png">

But the `visibleProperty` is also `phetioReadOnly: true`, and cannot be controlled by the user.  Recall that the visibility of gene-related UI components is controlled by the Properties under `view.genes`, for example:

<img width="252" alt="screenshot_2506" src="https://user-images.githubusercontent.com/3046552/236651703-50e2268e-99fd-4e58-93cb-2302091f0d74.png">

So do we really want to feature something that the user can't change? I recommend that we unfeature these elements.

**Comment by pixelzoom** [comment]
Note to self: This is now featured in code. To un-feature, go to ProportionsGraphNode.ts, and delete `phetioFeatured: true` from inner class `Column`.

**Comment by amanda-phet** [comment]
Discussed with @pixelzoom and again, can't understand why I featured this, so we agreed it should be un-featured.

**Comment by pixelzoom** [comment]
Done in the above commits. `proportionsGraphNode.columns.*Column.visibleProperty` is now `phetioFeatured: false` throughout.
