### ISSUE TITLE
`populationModel.totalVisibleProperty` should be featured for both screens

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#337]
In natural-selection-overrides.js:

```ts
    "naturalSelection.labScreen.model.graphs.populationModel.totalVisibleProperty": {
      "phetioFeatured": true
    },
```

`populationModel.totalVisibleProperty` is relevant for both screens, but is only featured for the Lab screen.  @amanda-phet is this a bug or intentional?

**Comment by amanda-phet** [comment]
Seems like a "bug" (an error in the featured process using overrides). That should be featured for the Intro screen as well.

**Comment by pixelzoom** [comment]
Fixed in the above commits.`populationModel.totalVisibleProperty` is now featured in both screens.

Closing.
