### ISSUE TITLE
Revise examples.md for 1.5 release

### ISSUE THREAD

**Issue by arouinfar** [phetsims/natural-selection#346]
For #323 

The [examples.md](https://github.com/phetsims/phet-io-sim-specific/blob/master/repos/natural-selection/examples.md) doc should be updated for the 1.5 release.

TODOs include
- [x] Delete customizations we wouldn't normally recommend to clients
- [x] Prune examples related to basic customization described in the PhET-iO Guide
- [x] Describe how to use the query parameters, see [deprecated guide](https://phet-io.colorado.edu/sims/natural-selection/1.4/doc/guides/phet-io-guide.html)
- [x] Examples highlighting how to use `getStateForObject` to get bunny data.
- [x] Possibly add a note about large populations, #350

**Comment by pixelzoom** [comment]
The empty examples.md is https://github.com/phetsims/phet-io-sim-specific/blob/master/repos/acid-base-solutions/examples.md

**Comment by pixelzoom** [comment]
For https://github.com/phetsims/qa/issues/967, note that 1.5.0-dev.5 was published with an empty examples.md file. 
Please contact @arouinfar for the status of examples.md.  It may be ready to review in master by the time that this test is underway.

**Comment by arouinfar** [comment]
In the above commit, I removed customizations that we wouldn't recommend to clients and some simpler examples covered in the general PhET-iO Guide. I also added examples describing the query parameters. There's still quite a bit to do here, though.

**Comment by arouinfar** [comment]
I completed the examples doc in the commit above and it is ready for review by QA. I added notes in the main QA  issue, but here there are again:

> QA, please review [examples.md](https://github.com/phetsims/phet-io-sim-specific/blob/master/repos/natural-selection/examples.md#select-which-mutations-are-visible) on master. Note that the example links containing {{STUDIO_PATH}} will only work in a built version. To test, please copy and paste the query string yourself.

**Comment by Nancy-Salpepi** [comment]
@arouinfar this phetioID needs to be fixed:

<img width="736" alt="Screenshot 2023-08-03 at 1 45 20 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/b59ecdc7-5c94-40fe-96a8-3bbb38198ef7">

**Comment by Nancy-Salpepi** [comment]
Cool. Shall we close this then?

**Comment by arouinfar** [comment]
Yes, let's close.

**Comment by arouinfar** [comment]
Reopening. I goofed and didn't actually format the links like links, so they are showing up like this in the built version:
<img width="916" alt="image" src="https://github.com/phetsims/natural-selection/assets/8419308/0abf7cbf-bcba-4cbd-8585-d1f66e7acd5f">

**Comment by pixelzoom** [comment]
Verified links in https://phet-dev.colorado.edu/html/natural-selection/1.5.0-dev.7/phet-io/doc/guides/examples.html

**Comment by arouinfar** [comment]
Thanks @pixelzoom. Looks good to me too, closing.
