### ISSUE TITLE
Some Pointer/Touch areas don't change when switching locale

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/natural-selection#348]
**Test device**
MacBook air (m1 chip)

**Operating System**
13.5

**Browser**
safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/967, the pointer/touch areas are sometimes smaller than the text in locales other than English. This is seen on both screens, with the dataProbeCheckbox, the allelesPanel and with all the checkboxes that appear when the proportionsRadioButton is selected. 
The pointer areas also sometimes end in an odd spot in the environmentalFactorsPanel.

**Steps to reproduce**
1. add to url:  ?showPointerAreas&stringTest=dynamic
2. On either screen, press the right arrow once (or more)
3. Select the pedigreeRadioButton
4. Select the proportionsRadioButton
 
**Visuals**
with ?stringTest=dynamic:
<img width="183" alt="Screenshot 2023-07-31 at 4 49 33 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/dd3cb402-a722-41f2-9136-650f01e8034b">

<img width="231" alt="Screenshot 2023-07-31 at 4 49 47 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/425cb930-e593-48c7-852c-64191b7125ef">
<img width="163" alt="Screenshot 2023-07-31 at 4 50 09 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/f14784c9-f9f0-4048-9017-56328537273e">
<img width="765" alt="Screenshot 2023-07-31 at 5 02 19 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/8f2cf6cf-4ef2-4ab1-9fa5-3c247bd2c306">

<details>
Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Hautespen naturala‬
URL: https://phet-dev.colorado.edu/html/natural-selection/1.5.0-dev.5/phet/natural-selection_all_phet.html?showPointerAreas
Version: 1.5.0-dev.5 2023-07-31 18:14:35 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.6 Safari/605.1.15
Language: en-US
Window: 1233x690
Pixel Ratio: 2/1
WebGL: WebGL 1.0
GLSL: WebGL GLSL ES 1.0 (1.0)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}
</details>

**Comment by pixelzoom** [comment]
I seem to recall a similar issue recently in some other sim. @Nancy-Salpepi @arouinfar does that ring a bell?

**Comment by Nancy-Salpepi** [comment]
Looks good on master. Closing.
