### ISSUE TITLE
Mutation Alert misaligned when row added to Mutation Panel

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/natural-selection#349]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/967, on the Intro Screen if 1 row is added to the Mutation Panel, the "Mutation Coming" alert will be lower than the mutation row. This doesn't happen if all 3 rows are visible. 

If I remove a row on the Lab Screen, the alert is still aligned with the row. 

**Steps to reproduce**
1. On the intro screen, make either the ears row or teeth row visible. `naturalSelection.introScreen.view.addMutationsPanel.earsRow.visibleProperty`
`naturalSelection.introScreen.view.addMutationsPanel.teethRow.visibleProperty`
2. Press the test button
3. In the Standard PhEt-iO wrapper, select either dominant or recessive for that trait so the "Mutation Coming" alert appears
4. Switching steps 2 and 3 also produces the same result

**Visuals**
<img width="503" alt="Screenshot 2023-08-01 at 8 27 32 AM" src="https://github.com/phetsims/natural-selection/assets/87318828/e76ab4a3-58ff-4b7c-8ef5-a9dff1aac2a5">
<img width="503" alt="Screenshot 2023-08-01 at 8 30 59 AM" src="https://github.com/phetsims/natural-selection/assets/87318828/aa9f6357-aa55-4fcf-8d27-86a76a5864da">

**Comment by pixelzoom** [comment]
I reproduced in the standard wrapper.   Also noting that in Studio, the alerts are in the correct position.

**Comment by Nancy-Salpepi** [comment]
I also tested several scenarios and all looks good to me. Closing!

**Comment by pixelzoom** [comment]
🎉 Good find!
