### ISSUE TITLE
Proportion data missing after migrating from 1.4 to 1.5

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/natural-selection#354]
**Test device**
MacBook Air M1 chip

**Operating System**
13.5

**Browser**
Safari 16.6

**Problem description**
For https://github.com/phetsims/qa/issues/967, and possibly related to https://github.com/phetsims/natural-selection/issues/353: the proportions graph will say "no data" in version 1.5 even though there is data in 1.4.
This occurs when migrating in both Play and Pause mode, and when in any generation. 
This doesn't happen with the Populations graph.

**Steps to reproduce**
In the migration wrapper:
1. On either screen, select the Proportions radio button
2. Click "Add a Mate"
3. Click "Migrate Now"

**Visuals**
<img width="452" alt="Screenshot 2023-08-01 at 7 04 58 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/5054904f-9113-49f4-81d1-eed5bd24f244">
<img width="386" alt="Screenshot 2023-08-01 at 7 05 11 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/5744b84c-a913-4ecc-bc34-9b40253f28c5">

**Comment by pixelzoom** [comment]
Definitely related to https://github.com/phetsims/natural-selection/issues/353, where assertion failure is in ProportionsModel.ts `recordEndCounts`.

**Comment by pixelzoom** [comment]
This problem does not occur in the State wrapper, so it's probably not related to the order that state is restored.

**Comment by pixelzoom** [comment]
The 1.5 sim is displaying "No Data" for the same reason that `recordEndCounts` is failing in #353.  The value of `currentStartCountsProperty` is null.  In ProportionsModel:

```ts
    this.hasDataProperty = new DerivedProperty(
      [ currentStartCountsProperty ], currentStartCounts => !!currentStartCounts, {
        tandem: Tandem.OPT_OUT
      } );
```

**Comment by pixelzoom** [comment]
This was 100% caused by #353, and resolved by the fix over there, which involved deleting this a bogus migration rule (duh):

```ts
new TandemFragmentDelete( 'proportionsModel.currentStartCountsProperty' ),
```

We want to get this sim into RC ASAP. So I'm going to proceed with creating the release branch and have @Nancy-Salpepi verify this issue in 1.5.0-rc.1, rather than in master.

**Comment by Nancy-Salpepi** [comment]
This is fixed in rc.1. 🙂
Closing!
