### ISSUE TITLE
Canvas 2D warning message in Chrome console

### ISSUE THREAD

**Issue by Nancy-Salpepi** [phetsims/natural-selection#355]
**Test device**
MacBook Air (M1 chip) and Dell

**Operating System**
macOS13.5 and Win10

**Browser**
Chrome 115

**Problem description**
For https://github.com/phetsims/qa/issues/967, a warning message appears in the console on startup for the PhET brand sim and PhET-iO wrappers.

**Visuals**
<img width="562" alt="Screenshot 2023-08-02 at 1 51 08 PM" src="https://github.com/phetsims/natural-selection/assets/87318828/876e7019-30ef-4713-ae53-cd8b2cb10a68">

**Comment by pixelzoom** [comment]
Reproduced with master in Chrome 115.

This is a warning, informing us that there's a way to improve performance of how we're using the Canvas2D API. 

Natural Selection is using Sprite, which is supposed to default to webgl, with canvas fallback.  So I'm not entirely sure where this is relevant.   The only sim-specific use of Canvas that I can find is in BunnySelectionRectangleSprite.ts;

```ts
    // Convert to {HTMLCanvasElement}, as required by Sprite
    let selectionRectangleSpriteImage: SpriteImage;
    selectionRectangle.toCanvas( canvas => {
      const offset = new Vector2( selectionRectangleBounds.width / 2, selectionRectangleBounds.height - SELECTION_RECTANGLE_DILATION );
      selectionRectangleSpriteImage = new SpriteImage( canvas, offset, { pickable: false } );
    } );
```

@jonathanolson Is there something that should be done here that might improve performance? Or should we just ignore this warning?

**Comment by jonathanolson** [comment]
We were reading a scratch Canvas multiple times (it was reused) in order to support the `hitTestPixels` feature (used at least for the bunnies). The Canvas's only use is for that purpose, so I've added the flag so that it should be CPU-side and won't have the warning.

**Comment by pixelzoom** [comment]
Back to @Nancy-Salpepi to verify in master.  You should no longer see this warning in Chrome.  Close if OK.

**Comment by Nancy-Salpepi** [comment]
I no longer see the warning in Chrome. Closing.
