### ISSUE TITLE
Links to model Properties in addMutationsPanel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#36]
From https://github.com/phetsims/natural-selection/issues/30#issuecomment-566708654:

> **View**
> ...
> 5. We also think the mutations selections panel `naturalSelection.labScreen.view.addMutationsPanel` should have links to the model property that identifies the mutation selection. This isn't currently in the tree yet, right?

**Comment by pixelzoom** [comment]
Yes, it will. But those model Properties don't exist yet.  And there's much to do for this panel (model and view). 

Feel free to close this issue if that's an acceptable answer for now.

**Comment by amanda-phet** [comment]
That's what we thought, but I wanted to ask anyway!

**Comment by pixelzoom** [comment]
Reopening this one.  It occurred to me that there are no UI components in this panel that have linked Properties.  A push buttons does not have an associated Property, it has a listener that fires when the button is pressed.  The action that listener performs may or may not result in the change to a Property.  In this case, there is unlikely to be a Property involved, and certainly not a Property that we want/need to expose.  Pressing the button will queue up a mutation, which will be applied the next time that mating occurs. 

Let me know if that makes sense, or requires more discussion.

**Comment by pixelzoom** [comment]
12/19/19 design meeting:  This panel probably does need any linked elements.  We'll revisit when the model is more fleshed out.
