### ISSUE TITLE
Difficulty in catching error: IntentionalAny

### ISSUE THREAD

**Issue by samreid** [phetsims/natural-selection#365]
After working on https://github.com/phetsims/perennial/issues/406, natural selection shows an odd problem in natural-selection/js/common/model/parseInitialPopulation.ts

Different messages I have seen:
1. lint error: import of `IntentionalAny` is unused (even though it is used in the catch type)
2. type error: TS1196: Catch clause variable type annotation must be any or unknown if specified.

**Comment by samreid** [comment]
I added a workaround that passes both linting and type checking. @pixelzoom would you like to review?

**Comment by pixelzoom** [comment]
Thanks for handling this. I changed to a more idiomatic cast: `( error as Error ).message`.
