### ISSUE TITLE
Artwork needed

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#4]
I had a discussion with @megan-phet about this sim and the artwork needs for it, and here is the list of artwork tasks we came up with: 

- [x] start with a basic bunny (white, tall ears, short/no teeth)

Then, create the following bunnies that can be easily colored to be white or brown: 
- [x] bunny with tall ears and no visible teeth
- [x] bunny with tall ears and long teeth
- [x] bunny with floppy ears and no visible teeth
- [x] bunny with floppy ears and long teeth

Icons to represent the following traits:
- [x] fur swatch that can be white or brown
- [x] floppy ears
- [x] tall ears 
- [x] no visible teeth
- [x] long teeth

Two scenes that have dimensions around 780x315 (maybe a little extra around in case we need to adjust the size a few pixels in either dimensions):
- [x] equator (puffy clouds, a few trees, dirt ground)
- [x] arctic (thin clouds, no trees, maybe rocks/mountains, and ice/snow ground) 

And selection agents:
- [x] food that is soft/grassy, perhaps light green, tall and bushy looking
- [x] food that is tough/woody, perhaps darker pine, short, and more sparse looking 
- [x] a wolf, perhaps looking like it is on the prowl

**Comment by pixelzoom** [comment]
Addition artwork needed:

- [ ] equator radio button icon
- [ ] arctic radio button icon
- [ ] mutation icon

**Comment by pixelzoom** [comment]
For these radio buttons:

<img width="109" alt="screenshot_1564" src="https://user-images.githubusercontent.com/3046552/66335277-ee0e6e00-e8f7-11e9-9f91-6ea2860819df.png">

... I need the sun and snowflake icons only, not the background colors.

**Comment by pixelzoom** [comment]
Looks like I could use fontawesome icons for the above buttons, if you don't mind the sun being a little different.

https://fontawesome.com/icons/sun?style=duotone
<img width="115" alt="screenshot_1565" src="https://user-images.githubusercontent.com/3046552/66335625-a4725300-e8f8-11e9-8c03-04b332d4d52f.png">

https://fontawesome.com/icons/snowflake: 
<img width="84" alt="screenshot_1566" src="https://user-images.githubusercontent.com/3046552/66335618-9e7c7200-e8f8-11e9-85fc-b35d1cbcd9ee.png">

**Comment by pixelzoom** [comment]
Here's are the fontawesome options for 'sun', https://fontawesome.com/icons?d=gallery&q=sun:

<img width="511" alt="screenshot_1567" src="https://user-images.githubusercontent.com/3046552/66335741-e00d1d00-e8f8-11e9-8afb-16a909b8364a.png">

**Comment by pixelzoom** [comment]
@amanda-phet I went ahead and used fontawesome icons for the sun and snowflake.  Here's what they currently look like in master, colors are easily changed:

<img width="106" alt="screenshot_1570" src="https://user-images.githubusercontent.com/3046552/66340425-5f531e80-e902-11e9-9c13-1adad49b6304.png">

**Comment by pixelzoom** [comment]
On 10/8/19, @amanda-phet gave me a "temporary" .ai file containing all of the artwork. I've checked it into GitHub as assets/natural-selection-artwork.ai.  I'm going to use this for the artwork going forward.  @amanda-phet please update this file in GitHub when the artwork is updated.

Eventually, I'd prefer to get individual .ai files for images or groups of related images (e.g. bunnies), so that we don't need to sort out whether we have the correct asset (.ai) files at the end.

**Comment by pixelzoom** [comment]
I generated PNG files from new .ai files on 10/30/19.  Problems with background artwork are noted in #6.

**Comment by amanda-phet** [comment]
The mutation icon is being tracked in https://github.com/phetsims/natural-selection/issues/7. Can we close this issue?

**Comment by pixelzoom** [comment]
Yes, good to close.
