### ISSUE TITLE
data collection can exceed memory limits

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#46]
As designed,  a scenario can potentially run forever.  As long as all bunnies don't die, and bunnies don't take over the world, the current scenario will continue to run, and (more importantly) collect data for the Population and Proportions graph. Memory footprint will continue to grow, and will (eventually) exceed the memory limits of the browser.  This can occur if the population enters a stable state and stays there, or if the user repeatedly takes the sim in and out of a stable state.   

Some ways that this could be address:
* Limit the sim to N generations.  This would cause the sim to stop when N is reached, regardless of what state it's in.
* Keep only data for the N most recent generations. This would limit how far back in time the graphs can be scrolled.
* ?

@amanda-phet how should this be addressed?

**Comment by amanda-phet** [comment]
I thought I had replied to this right away. My inclination is to limit the number of generation, if that number can be large enough that most people won't easily approach it. 

Do you have any idea how long it might take to reach the browser memory limits? Should we wait for QA to test the memory use once the model is up and running, or will the decision impact how you start working on the model?

**Comment by pixelzoom** [comment]
If we decide that having a max number of generations is the proper strategy, then I'm fine with waiting for QA to decide what that max number should be.  But we should not wait to decide on a strategy.

I don't know how many generations it might take to cause a memory problem.  This sim isn't storing  any big data structures, so I would guess that it will be a large number of generations, probably > 100.    How long it takes to reach 100 generations will depend on the time we need for 1 revolution of the generation clock (the "clock period").  I'm guessing that the clock period will need to be significantly longer than in the Java version, since we're not pausing the clock to apply environmental factors.

The memory limit itself will likely be determined by one of the mobile device platforms.  If we want this sim to be well-behaved on a phone, we should keep that in mind.

**Comment by pixelzoom** [comment]
1/16/20 design meeting:

We'll go with max number of generations, followed by a dialog.  We'll figure out what max number is later.

**Comment by amanda-phet** [comment]
Initial pass at a dialog for this case when the user has reached the maximum number of generations. We discussed it saying something along the lines of "Congrats, your bunny population is stable!" but it is possible that the user can reach the maximum number of generations and it not be in a stable state at that time. 
![image](https://user-images.githubusercontent.com/7852916/73697070-eccd3200-469a-11ea-8517-62962d88512e.png)

So, I am thinking it needs to say something else about why they need to start over. Maybe we can explicitly state how many generations they've lived. 
![image](https://user-images.githubusercontent.com/7852916/73697125-0d958780-469b-11ea-826a-580ffbd4ed1d.png)

I'm not really tied to this artwork, just wanted to get some ideas in this issue.

**Comment by pixelzoom** [comment]
Does "Your bunnies have lived for N generations" communicate that we're stopping because that's the upper limit of the sim?  I'm not so sure...  And for big N, there won't be any bunny that will have lived for N generations -- the population will have have existed for N generations -- so the message is a bit misleading. 

I don't have a better suggestion at the moment, but I'll think about it.

**Comment by pixelzoom** [comment]
I've implemented all of the basic functionality. It works like this: 

* The `maxGenerations` query parameter (default 100) determines when the sim will stop -- run with `?maxGenerations=2` to test drive.  
* The dialog is currently an OopsDialog, shown in the screenshot below.   The message string and icon can easily be changed.
* After closing the dialog, the sim is in the "Start Over" state. 

Questions:

* What message and icon do you want to display?
* What value for `maxGenerations` seems reasonable?

<img width="673" alt="screenshot_415" src="https://user-images.githubusercontent.com/3046552/86041010-3cbde400-ba02-11ea-8a6a-cf4f866bc618.png">

**Comment by pixelzoom** [comment]
I also investigated whether a JavaScript program can determine how much memory it's using.  I received a couple of suggestions from @jessegreenberg on Slack:

* Performance: https://developer.mozilla.org/en-US/docs/Web/API/Performance
* RunKit.object-sizeof: https://npm.runkit.com/object-sizeof 

Performance.memory is documented as "A _non-standard_ extension added in Chrome, this property provides an object with basic memory usage information. _You **should not use** this non-standard API_." 

RunKit.object-sizeof would require the sim to compute its own total of specific memory usage, not what I had in mind, and not very practical for this sim.

So I think that our best bet is to stick with the `maxGenerations` approach, hope that we can set `maxGenerations` to a big value, like `1000`, and hope that we can develop a reliable test.

**Comment by pixelzoom** [comment]
Labeled for design meeting to get input on desired icon and message.

**Comment by pixelzoom** [comment]
7/2/2020 design meeting:

Icon: Bunny with brown fur, straight ears, long teeth.

message: leave as is

maxGenerations: set to 1000

With secondsPerGeneration=10, this should take ~2.7 hours to reach this limit.

We discussed keeping N generations of data and dropping earlier data.  But that has more issues, and consensus was that having a generation limit is cleaner/clearer.

**Comment by pixelzoom** [comment]
In the above commits, I added a bunny icon, and increased `maxGenerations: 1000`.   

Here's what it looks like in master:

<img width="1088" alt="screenshot_418" src="https://user-images.githubusercontent.com/3046552/86406099-c3c3c400-bc6f-11ea-89d9-df5e0c0f06ca.png">

@amanda-phet is this good? 

I'll leave assigned to me to verify that `maxGenerations: 1000` is reasonable, once we have the ability to get the sim in a steady state.

**Comment by amanda-phet** [comment]
I like it!

**Comment by pixelzoom** [comment]
This is assigned to me to verify that `maxGenerations: 1000` is reasonable, once we have the ability to get the sim in a steady state.

**Comment by pixelzoom** [comment]
7/7/2020 discussed with @amanda-phet via Zoom. She will describe a procedure for putting the sim in a steady state.  Then I'll put the sim is a steady state and take heap snapshots to see what the memory footprint is as we approach `maxGenerations`.

**Comment by pixelzoom** [comment]
> ... ability to get the sim in a steady state ....

Since I haven't been able to accomplish this by using the sim, I'm going to add a query parameter that prevents the bunnies from taking over the world by randomly killing part of the population.   This will be generally useful for testing memory limit, and shouldn't be relatively easy.

**Comment by amanda-phet** [comment]
See #119 for getting the sim in a steady state.

**Comment by pixelzoom** [comment]
From https://github.com/phetsims/natural-selection/issues/119#issuecomment-657915594, the stabilization procedure is:

> 1. Add a mate
> 2. At the start of generation 3, check "Limited Food"

**Comment by pixelzoom** [comment]
Since the team is happy with the `maxGenerations` approach and the look of the dialog, the only thing remains to be done is to tune `maxGenerations`.   We'll track that in #130.

Closing.
