### ISSUE TITLE
Verify that public-facing query parameters fail gracefully

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#49]
Verify that public-facing query parameters fail gracefully using the general features under development in https://github.com/phetsims/joist/issues/593.  This is on hold until that issue is addressed.

**Comment by pixelzoom** [comment]
Verified for all public facing query-parameters.

With this set of bogus query parameters:

`?allelesVisible=bogus1&introMutations=bogus2&introPopulation=bogus3&labMutations=bogus4&labPopulation=bogus4
`

The sim starts like this:

<img width="931" alt="screenshot_320" src="https://user-images.githubusercontent.com/3046552/82282016-11020580-9950-11ea-86ee-352f69d343ca.png">

... and the sim falls back to default values.

Closing.

**Comment by samreid** [comment]
There are still TODOs marked for this issue, discovered during https://github.com/phetsims/chipper/issues/946
