### ISSUE TITLE
PhET-iO design

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#5]
Version 1.0.0 will include PhET-iO support, likely with client-specific features.  For that to happen, we need to have requirements and do PhET-iO design from the beginning of development.  The PhET-iO section of the design document needs to be fleshed out asap.

**Comment by kathy-phet** [comment]
@pixelzoom - I have asked for some specifications from our partner based on the design - so we can weave that input into this. I asked yesterday when this issue was started, but unlikely to hear until early next week after they have had a chance to review the latest designs.

**Comment by ariel-phet** [comment]
@amanda-phet assigning to you for now to bring up at next design meeting that occurs after 10/17, hopefully our client will have some feedback by then.

**Comment by pixelzoom** [comment]
10/17/19 design meeting:
Completion milestone for PhET-iO design is 12/1/2019.

**Comment by pixelzoom** [comment]
10/31/19 status meeting:  

I mentioned that I'm becoming uncomfortable with proceeding without requirements. Risk increases as implementation proceeds, and we are 10% of the way along our timeline.

@amanda-phet will schedule a meeting with @kathy-phet, @ariel-phet, and @pixelzoom to discuss both general and client-specific requirements.

**Comment by pixelzoom** [comment]
Design meeting scheduled for 11/5/19, 10-11am MST. 

Agenda:
* Review client requirements doc (see email). “General Elements” section looks straightforward. “Initial conditions of the sim” section requires discussion/negotiation.
* Plan for general PhET-iO design.
* How/where to track client requirements?

**Comment by pixelzoom** [comment]
11/5/19 design meeting
* @amanda-phet @kathy-phet @ariel-phet @pixelzoom 
* We created a new (private) PhET-iO design doc in Google Doc.
* We discussed client's requirements (see notes in PhET-iO design doc).
* We briefly started discussing general requirements and features.
* Action items for @kathy-phet and @pixelzoom are in the PhET-iO design doc. Search for "ACTION ITEM".
* We should have our next meeting in 2 weeks. (@kathy-phet is busy for the next 2 weeks.)

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet please schedule the next meeting.

**Comment by amanda-phet** [comment]
@kathy-phet should be available after November 19th. However her schedule looks packed. So I think we should plan to meet during design on 11/21/19.

**Comment by pixelzoom** [comment]
From the Milestones section of the design doc:

> December 1, 2019: PhET-iO design completed

We have missed this deadline. And lack of requirements (particularly related to the collection of bunnies and graph data) is holding up model implementation.  This may result in delays for other milestones, including publication.

**Comment by pixelzoom** [comment]
In the above commits, I made a first (incomplete) pass at instrumenting the view.  I was hoping use this to have a partial Studio tree, to facilitate design discussions. 

I ran into major problems, because the PhET-iO toolchain currently does not support incremental instrumentation -- it's "all or nothing" instrumentation.  

@samreid and @zepumph worked with me for a bit, and we made a change to `grunt update` so I could at least generate API files (see https://github.com/phetsims/phet-io/issues/1589).  But Studio was still failing, and it appeared to be related to linked elements.  

I decided to commit my work, but removed 'phet-io' from `supportedBrands` in package.json.   When I return to this, I'll probably need to allocate time to do a full instrumentation.  That might mean that I wait until later in the implementation process, which also might mean having to rewrite/restructure some things to meet PhET-iO requirements or have their structure appear a certain way in the Studio tree.

**Comment by samreid** [comment]
> But Studio was still failing, and it appeared to be related to linked elements.

In https://github.com/phetsims/phet-io/issues/1589#issuecomment-562864860 I changed studio so it no longer crashes on uninstrumented linked elements.  Here is my comment from that issue:

> I added a check in studio that prevents uninstrumented LinkedElements from crashing studio. This now means studio correctly switches between screens during usage. @pixelzoom maybe this will be more useful for your upcoming meeting.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet @ariel-phet FYI, many of the client requirements have been implemented, and you can test-drive in https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.13/phet-io/.  Please refer to the design document to see which requirements have been implemented, they are marked with ✅.

**Comment by pixelzoom** [comment]
In 12/11/19 design meeting, we discussed all GitHub phet-io design issue, and came up with a (complete?) list of general PhET-iO requirements.  See the design doc for notes.

**Comment by pixelzoom** [comment]
If/when you resume review, here's a more current PhET-iO version:
https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.18/phet-io/

**Comment by pixelzoom** [comment]
12/19/19 design meeting:

In #30, we had a productive initial review of the Studio tree (structure and naming). We'll do another review when the model is more fleshed out.

I asked @kathy-phet about what aspects of data stream we should be concerned about for design. There are 2 main things:
(1) which things should be `phetioHighFrequency: true`
(2) adding custom events to the data stream

I'm going to concern myself with (1), and wait for any requirements for (2).

**Comment by pixelzoom** [comment]
The sim has been feature-complete since 7/7/2020 and I'm not anticipating that I'll need to make any more internal changes that will affect the Studio tree structure.  I'm shooting for a late-August dev test, which will include phet and phet-io brands.  

@amanda-phet and @kathy-phet please review the current PhET-iO implementation.  You can use master or https://phet-dev.colorado.edu/html/natural-selection/1.1.0-dev.2/phet-io/.  You first pass should be overall structure of the Studio tree and tandem names.  If that looks OK, that you can probably start on phetioFeatured.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet When you start on this, ask me for a fresh dev version.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet FYI, the current milestone was to start dev testing at the end of August.  Code review needs to happen before then, and PhET-iO review should be completed before code review (or maybe OK to do in parallel for this sim).  Since we're now at mid-August, raising priority of this review to high.

**Comment by amanda-phet** [comment]
@kathy-phet and I were planning to get to this Monday but she was sick this week. We will likely do this review on Tuesday 8/18/20.

**Comment by amanda-phet** [comment]
Review is complete, and questions have been discussed in the referenced issues.
