### ISSUE TITLE
UX for selecting a bunny

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#50]
The selected bunny determines what is displayed in the Pedigree graph.

In the Java version, there is initially no selection. The Pedigree graph displays "Click a Bunny":

<img width="1023" alt="screenshot_229" src="https://user-images.githubusercontent.com/3046552/77965597-93e6d800-729e-11ea-82cb-7dde5bbd1f40.png">

When you do select a bunny, a blue rectangle appears around it:

<img width="1023" alt="screenshot_231" src="https://user-images.githubusercontent.com/3046552/77965702-d27c9280-729e-11ea-9f52-a2bbda93936e.png">

You can select another bunny. But the only way to clear the selection is Reset All.  And if the selected bunny dies, then it (and its blue rectangle) disappears from the environment. But it remains in the Pedigree graph, labeled with a red 'X':

<img width="1025" alt="screenshot_230" src="https://user-images.githubusercontent.com/3046552/77965692-cb558480-729e-11ea-8561-0883831f8df9.png">

Is this the UX you'd like for the HTML5 version?

Some other possibilities, not mutually exclusive:

* Only show the selection (and allow selecting) when Pedigree radio button is selected, since that's the only time that selection is relevant.  
* Allow the user to click somewhere else in the environment (anywhere except on a bunny) to clear the selection.  
* Clear the selection (and the Pedigree graph) if the selected bunny dies.

**Comment by pixelzoom** [comment]
Proposal...  Like Java version, but with these changes:

* Use "Select a Bunny" instead of "Click a Bunny" in the Pedigree graph, since "click" is specific to mouse input. This is displayed by the Pedigree graph whenever there is no bunny selected.
* Allow the user to "pointer down" somewhere else in the environment (anywhere except on a bunny) to clear the current selection.
* When a bunny dies, clear the selection.

**Comment by pixelzoom** [comment]
Proposal...  Like Java version, but with these changes:

* Use "Select a Bunny" instead of "Click a Bunny" in the Pedigree graph, since "click" is specific to mouse input. This is displayed by the Pedigree graph whenever there is no bunny selected.
* Allow the user to "pointer down" somewhere else in the environment (anywhere except on a bunny) to clear the current selection.  This seems useful since having a selected bunny is only relevant for the Pedigree graph.
* If the selected bunny dies, clear the selection. This also clears the Pedigree graph.

**Comment by amanda-phet** [comment]
@pixelzoom I like your proposal. Bullets 1 and 2, about selecting a bunny and allowing the user to deselect a bunny. 

I'm not sure about clearing the pedigree when the bunny dies. I think someone could in theory be analyzing the pedigree and it could disappear while in the middle of viewing it. I don't see the harm in keeping the pedigree of a dead bunny.. I realize it's strange that they won't see a selected bunny in the environment view, but the pedigree will indicate that the bunny is dead. So my vote is to not clear the selection if a bunny dies.

**Comment by pixelzoom** [comment]
Thanks @amanda-phet, I agree - let's not clear the Pedigree graph when the selected bunny dies.

So this proposal is now fully implemented.  To summarize:

* Use "Select a Bunny" instead of "Click a Bunny" in the Pedigree graph, since "click" is specific to mouse input. This is displayed by the Pedigree graph whenever there is no bunny selected.
* Allow the user to press somewhere else in the environment (anywhere except on a bunny) to clear the selected bunny.

@amanda-phet @kathy-phet @ariel-phet please review in master.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet @ariel-phet ping - I don't want to get too further along before getting your input on this.

**Comment by amanda-phet** [comment]
This seems to be working as desired. 

This is nitpicky but I think the corners of the blue rectangle could be slightly less rounded. 

If I start the sim with more bunnies am I able to see a pedigree? Or is that still in the works?

**Comment by pixelzoom** [comment]
> This is nitpicky but I think the corners of the blue rectangle could be slightly less rounded.

I hate the square corners in the Java version.  So I started by matching the roundness of other rounded corners (radio buttons, panels, ... ) for a uniform look.  It's trivial to change if you'd prefer a different corner radius. 

> If I start the sim with more bunnies am I able to see a pedigree? Or is that still in the works?

The selected bunny does not yet appear in the Pedigree graph, but "Select a Bunny" text does.

**Comment by amanda-phet** [comment]
It must be an illusion then, because I thought they seemed more rounded than the panels. No need to change if they are in fact the same.

**Comment by pixelzoom** [comment]
It's a little tricky because the bunnies are scaled, so I have to compute the corner radius to make them similar to panels, etc. -- and they are indeed off a little bit.  I've changed how bunnies (and all sprites) are scaled in the above commit, so now the corner radius is spot-on identical to panels. Easy to change if you'd like something else, and thanks for the feedback.

The feedback I'm most interested in from @kathy-phet and @ariel-phet, regarding the overall design here.

**Comment by ariel-phet** [comment]
@pixelzoom @amanda-phet overall I think this design/interaction looks really good!

My one suggestion would be to move the text for "Select a Bunny" to near the top of the empty panel. It seems putting it closer to the play area would be a better cue, and it feels a little lost to me in all the white space.

**Comment by pixelzoom** [comment]
Thanks for the feedback @ariel-phet.  I've centered 'Select a Bunny' in the upper third of the panel, see screenshot below. Better?

<img width="920" alt="screenshot_249" src="https://user-images.githubusercontent.com/3046552/78929174-25083c80-7a5f-11ea-9f10-2d8ff3672288.png">

**Comment by pixelzoom** [comment]
We haven't gotten @kathy-phet's input.  But it feels like we have consensus on this, so I'm going to close this issue because I need to move forward.
