### ISSUE TITLE
NumberSpinner should use NumberDisplay

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#51]
In https://github.com/phetsims/sun/issues/575, NumberSpinner is supposed to be modified to use NumberDisplay, specifically to achieve a desired PhET-iO tandem structure. Since this sim uses NumberSpinner, we'll need to decide if completion of that issue is a prerequisite.

**Comment by pixelzoom** [comment]
@amanda-phet is this a prerequisite for 1.0 release?  If so, we should get the common-code work scheduled.

**Comment by amanda-phet** [comment]
I have no idea. @kathy-phet ?

**Comment by pixelzoom** [comment]
Labeled for 7/2/20 design meeting, to get @kathy-phet's input on whether this is a prerequisite to 1.0.

**Comment by pixelzoom** [comment]
7/2/2020 design meeting:

Let's try to get this done for 1.0, as well as ph-scale 1.4, gas-properties, etc.

Would like me to do it.

**Comment by pixelzoom** [comment]
Work completed in https://github.com/phetsims/sun/issues/575.   The Studio tree for the "Generations" spinner, `naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.generationSpinner`, now looks like this:

<img width="231" alt="screenshot_422" src="https://user-images.githubusercontent.com/3046552/86977768-9af17200-c13a-11ea-8013-0645503ac5d5.png">

@amanda-phet please verify in master or https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.66/phet-io/wrappers/studio/.

**Comment by pixelzoom** [comment]
Raising priority to "top".  If the Studio tree is for some reason incorrect, this will require common-code changes, and will impact the pH Scale RC 1.4.0-rc.1 that's in progress.   So it's important to get this issue (and phetsims/sun#575) closed quickly.

**Comment by amanda-phet** [comment]
I think NumberDisplay is looking good and working as it should. 

Is `naturalSelection.labScreen.view.graphs.populationNode.populationGraphNode.generationScrollControl` supposed to also use `numberDisplay` instead of `backButton` and `forwardButton`?

**Comment by pixelzoom** [comment]
No. `populationGraphNode.generationScrollControl` is not a spinner.  There is no numeric value associated with this control. We could change that if you want, but it will be a bit of work.  And it's not clear what the value (which will appear in Studio) should be - the minimum or maximum generation value shown by the graph's x axis?  Let me know if you want something changed.  Otherwise you can close this issue.

**Comment by amanda-phet** [comment]
I see the difference now. From my perspective, they seemed like really similar controls, but I see how they aren't.
