### ISSUE TITLE
Should time pass before generation clock begins?

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#53]
In the Java sim, a bunny ages right away, and could theoretically die if you don't add a mate in time. In the HTML5 sim, the generation clock and population chart don't start until a mate is added. Recording the decision here about how to handle this discrepancy: 

Amanda McGarry  12:44 PM
Hey Natural Selection team. CM and I were just discussing the issue of time passing when the sim starts up, but the generation clock not running. It is pretty inconsistent that a bunny could age (and die) while time is not moving. In the java sim, though, time is passing, and a bunny could die if you never add a mate. Is this an important feature to keep (having a bunny age before adding a mate)?

Another level of complication here is that the sim could start up with a population of bunnies, and a “start” button that starts the clock. If time is passing, then those bunnies would all age and die at the same moment. This seems really strange without a generation clock counting down.

It seems the most consistent with the design of the sim that we have a bunny (or bunnies) hopping around because it’s cute and it attracts your eye to the button in the play area, but time isn’t really passing. So a bunny could hop indefinitely if you never press the button.

Kathy Perkins  12:46 PM
I'm fine with not having time pass (but bunnies hopping indefinitely) until you add a bunny or press "start" if you begin with a population of bunnies.

Ariel Paul  12:50 PM
Also seems fine to me

**Comment by pixelzoom** [comment]
👍 Closing.
