### ISSUE TITLE
what happens after "Start Over" button is pressed? 

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#54]
If the sim is started with an initial population of 1 (the default), the "Add a Mate" button is visible. Pressing this button adds a mate and started the generation clock.

<img width="1022" alt="screenshot_270" src="https://user-images.githubusercontent.com/3046552/79618502-7354b580-80c7-11ea-969a-1fb5e2255377.png">

If the sim is started with an initial population > 1, the "Play" button is visible. Pressing this button starts the generation clock:

<img width="1024" alt="screenshot_271" src="https://user-images.githubusercontent.com/3046552/79618539-88314900-80c7-11ea-96d5-363d98cc1fc0.png">

When all bunnies have died, or bunnies have taken over the world, a modal dialog is displayed:

<img width="1021" alt="screenshot_272" src="https://user-images.githubusercontent.com/3046552/79618593-aeef7f80-80c7-11ea-9215-61b202048961.png">

When the dialog is closed by the user, a "Play Again" button is visible and some UI components are disabled. This gives the user the opportunity to review the results before starting another "game".   For example, here's what is currently displayed when the "All of the bunnies have died" dialog is closed:

<img width="1022" alt="screenshot_273" src="https://user-images.githubusercontent.com/3046552/79618676-f6760b80-80c7-11ea-99d5-0f59c4763df4.png">

Pressing the "Play Again" button re-enables the UI components that were disabled above, and leaves all of the user's settings (radio buttons, checkboxes) unchanged.

All of the above is my recollection of what was discussed in 10/17/2019 design meeting. Decisions in the design doc are not very detailed, and only say "Put a “play again” button in the play area." The screenshot accompanying the narrative about the "Play Again" button shows the "Add Mutation" panel, "Environmental Factors", and time controls disabled - so that's what the currently implementation (master) does.

Questions:

* What happens when the "Play Again" button is pressed when the initial state was 1 bunny? Do we restore 1 bunny and the "Add a Mate" button, with the generation clock paused? Or automatically add a mate and start the generation clock?

* What happens when the "Play Again" button is pressed when the initial state was N bunnies, where N > 1? Do we restore N bunnies and the "Play" button, with the generation clock paused? Or automatically start the generation clock?

**Comment by amanda-phet** [comment]
>What happens when the "Play Again" button is pressed when the initial state was 1 bunny? Do we restore 1 bunny and the "Add a Mate" button, with the generation clock paused? Or automatically add a mate and start the generation clock?

Yes, restore 1 bunny and the "add a mate" button. 

>What happens when the "Play Again" button is pressed when the initial state was N bunnies, where N > 1? Do we restore N bunnies and the "Play" button, with the generation clock paused? Or automatically start the generation clock?

Yes, restore N bunnies and the "play" button. 

Decisions during a discussion with @pixelzoom 4/20/20: 
* Change the "Play Again" button to "Start Over" 
* Change the behavior so that the users settings (mutations, environmental factors, and checked graphs) are actually reset. Mutations must be, and therefore it makes more sense that the checked graphs are also reset. So it seems strange to leave the environmental factors unchanged when the others changed.

**Comment by pixelzoom** [comment]
I made the changes we discussed in the above commit.  

There's still a bit of a usability problem here. When I press "Start Over", the "Add a Mate" or "Play" button appears in it's place.  The buttons are all the same color, and they appear in the same place.  So it's easy not to notice that the "Start Over" button was replaced, and you have to click another button to continue.   This is especially the case with a touch device, where your finger covers the button.  

@amanda-phet thoughts?

**Comment by amanda-phet** [comment]
I'd like to see how it feels when I can play with it next. But we could also see what happens in interviews. I'm not sure I see it as a huge concern if the buttons are in the same place.

**Comment by amanda-phet** [comment]
I meant that I would like to interview on this first to see if it is in fact a usability concern. 

I'm open to making the "Start Over" button a different color. Perhaps white, since there are no bunnies in the play area at that time? We could also put it in the center of the play area as opposed to the bottom.

**Comment by pixelzoom** [comment]
> I'm open to making the "Start Over" button a different color. Perhaps white, since there are no bunnies in the play area at that time? 

There are only no bunnies if they all died. If they took over the world, then the environment will be full of bunnies.

**Comment by pixelzoom** [comment]
"Play Again" button was renamed to "Start Over", so changing the title of this issue.

**Comment by pixelzoom** [comment]
4/30/2020 design meeting @amanda-phet @kathy-phet @arouinfar @ariel-phet @samreid 

Consensus that this is a good starting place, and we'll wait for interviews to see if anything needs to change.

**Comment by pixelzoom** [comment]
I've move the interview item mentioned in https://github.com/phetsims/natural-selection/issues/54#issuecomment-621478307 to https://github.com/phetsims/natural-selection/issues/166.

Closing this issue.
