### ISSUE TITLE
should "Add a Mate", "Play", and "Start Over" buttons unpause the sim?

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#55]
If the user had paused the sim, should the "Add a Mate", "Play", and "Start Over" buttons automatically unpause the sim?  Or should we never automatically unpause the sim, and leave it to the user to figure out why pressing "Play" doesn't do anything?  

I think the former (unpause the sim) is the least confusing, since we have 2 independent time-based things that can be "playing" - the sim and the generation clock.

**Comment by amanda-phet** [comment]
@pixelzoom and I discussed this today. It seemed reasonable to keep the sim paused if the user put it in that state, but also extremely confusing if the user clicks "play" or "add a mate" and the sim is frozen. So I think it makes the most sense to unpause the sim when the user clicks "start over" (what was formerly "play again"). @pixelzoom please correct me if I forgot something or misremembered our conversation from 4 hours ago!

**Comment by pixelzoom** [comment]
Implemented as requested in master and [1.0.0-dev.32]():

* Pressing "Add a Mate" does not change the time controls.
* Pressing "Play" does not change the state of the time controls.
* Pressing "Start Over" set the state of the time controls to playing.

@amanda-phet please review, and incorporate (or link) this info into the design doc. Then feel free to close this issue.   

To make testing easier... Use `?population=N` to initialize with N bunnies.  Use `?secondsPerGeneration=1` to speed up the generation clock.

Also note that when the number of bunnies gets large, the sim pauses a bit while bunnies are being born.  That hasn't been optimized yet, and is not relevant to this issue.

**Comment by pixelzoom** [comment]
Implemented as requested in master and [1.0.0-dev.31](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.31/phet/natural-selection_en_phet.html):

* Pressing "Add a Mate" does not change the time controls.
* Pressing "Play" does not change the state of the time controls.
* Pressing "Start Over" set the state of the time controls to playing.

@amanda-phet please review, and incorporate (or link) this info into the design doc. Then feel free to close this issue.   

To make testing easier... Use `?population=N` to initialize with N bunnies.  Use `?secondsPerGeneration=1` to speed up the generation clock.

Also note that when the number of bunnies gets large, the sim pauses a bit while bunnies are being born.  That hasn't been optimized yet, and the pause is not relevant to this issue.

**Comment by amanda-phet** [comment]
Looks good, and I added this to the controls section of the design doc.
