### ISSUE TITLE
PhET-iO requirements for Population graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#56]
As we've discovered with other parts of this sim, knowing PhET-iO retirements up front informs how the features are implemented.   And that's going to be especially true for the graphs.  In https://github.com/phetsims/natural-selection/issues/21, the decision was made to implement sim-specific graphs, and not to use griddle or a 3rd-party library.  The graphs must also be PhET-iO instrumented.  So the graphs in Natural Selection are going to be relatively expensive.

[Natural Selection: PhET-iO Design](https://docs.google.com/document/d/1vjsUiRdfbpPRWprozZykrDQHyaWtcgGjXrQrlZbj69Q/edit#) is sparse on requirements for the Population graph:

> Population graph:
> * For each allele, Property that indicates number of bunnies “now”
> * Get data points for each allele (`ObservableArray.<Vector2>`)

This needs to be fleshed out more, including:
* Is this a reasonably complete set of requirements? 
* How should these requirements present in Studio? (tree structure,...)
* What should appear in the data stream?
* Do any of these requirements require methods in an IO Type API? 
* How to deal with scalability - this is a lot of data. 

I'm anticipating that I'll be ready to start implementing the Population graph around 5/4/2020.

**Comment by amanda-phet** [comment]
I think these PhET-iO requirements are complete for the population graph. We think an instructional designer would want to get the number of bunnies at a given time, so essentially all of those graph values (total, white fur, brown, fur, etc.) in an array. 

Let's discuss tree structure and data stream at design meeting.

**Comment by pixelzoom** [comment]
4/30/2020 design meeting @amanda-phet @kathy-phet @arouinfar @ariel-phet @samreid

These model requirements were verified:
* For each allele, Property that indicates number of bunnies “now”
* Get data points for each allele

For the "data points for each allele"...  The Java version created 1 data point during each "death cycle", because the clock pauses.  In the HTML5 version, the clock does not pause, so each step during the "death cycle" may result in a data point.  A data point will be created whenever the total population count changes, and when the count of the number of bunnies with an allele changes.  We should try to limit the number of data points per generation, so that the sim can run longer without reaching memory limits, and so that we don't have a ridiculous number of data points in PhET-iO.

What what parts of the graph are instrumented?
* grid - NO
* tick marks - NO
* tick labels - NO
* x-axis control - YES, but visibleProperty is read-only
* y-axis label - YES, but visibleProperty is read-only
* zoom buttons - YES, but visibleProperty is read-only
* entire graph - YES, but visibleProperty is read-only

**Comment by pixelzoom** [comment]
In the above commit, data points are Vector2 instances.  Vector2.x is generation, Vector2.y is population. They are stored in ObservableArrays, and only created when there is a population change.

The ObservableArrays are groups under `dataPoints`, e.g. in the _Lab_ screen `naturalSelection.labScreen.model.populationModel.dataPoints`.   It looks like this in Studio:

<img width="250" alt="screenshot_386" src="https://user-images.githubusercontent.com/3046552/84193280-6bc2e480-aa58-11ea-8b05-26f170d53ba4.png">

**Comment by pixelzoom** [comment]
PhET-iO requirements for the Population graph are completed.  But I'm going to wait to have this reviewed until the view is rendering the data.

**Comment by pixelzoom** [comment]
@amanda-phet this is ready for review in master or https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.58/phet-io/.

The requirements were summarized in https://github.com/phetsims/natural-selection/issues/56#issuecomment-622123883. 

For the counts of bunnies “now”, see `naturalSelection.labScreen.model.bunnyCollection.liveBunnies.countsProperty`.

For the counts displayed by the data probe, see `naturalSelection.labScreen.model.populationModel.dataProbe.countsProperty`.

For data points for total and alleles, see `naturalSelection.labScreen.model.populationModel.dataPoints`.

**Comment by amanda-phet** [comment]
>For the counts of bunnies “now”, see naturalSelection.labScreen.model.bunnyCollection.liveBunnies.countsProperty.

This looks great. 

>For the counts displayed by the data probe, see naturalSelection.labScreen.model.populationModel.dataProbe.countsProperty.

This was a little confusing at first because it has values before the probe is visible, but I completely understand why that's the case and it's fine. 

>For data points for total and alleles, see naturalSelection.labScreen.model.populationModel.dataPoints.

I can't remember how to view the array to see this data. This is definitely something we will want in the client guide, and I'll need @pixelzoom to give me a refresher when he returns.

**Comment by pixelzoom** [comment]
@amanda-phet said:
> > For data points for total and alleles, see naturalSelection.labScreen.model.populationModel.dataPoints.
> 
> I can't remember how to view the array to see this data. This is definitely something we will want in the client guide, and I'll need @pixelzoom to give me a refresher when he returns.

The data is stored in ObservableArrays, and Studio provides no ability to inspect the contents of an ObservableArray.  So if you want to see data, you'll need to inspect the data stream in the State Wrapper.  For example, here are the data points for "short teeth" after the bunnies have mated twice.  For each point, x=generation, y=population.

```
"naturalSelection.labScreen.model.populationModel.dataPoints.shortTeethPoints": {
        "array": [
            {
                "x": 0,
                "y": 2
            },
            {
                "x": 1,
                "y": 6
            },
            {
                "x": 2,
                "y": 18
            }
        ]
    },
```

**Comment by amanda-phet** [comment]
Thanks @pixelzoom . That looks just like what we had discussed, so I don't think any changes need to be made here.
