### ISSUE TITLE
PhET-iO requirements for Proportions graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#57]
As we've discovered with other parts of this sim, knowing PhET-iO retirements up front informs how the features are implemented.   And that's going to be especially true for the graphs.  In https://github.com/phetsims/natural-selection/issues/21, the decision was made to implement sim-specific graphs, and not to use griddle or a 3rd-party library.  The graphs must also be PhET-iO instrumented.  So the graphs in Natural Selection are going to be relatively expensive.

[Natural Selection: PhET-iO Design](https://docs.google.com/document/d/1vjsUiRdfbpPRWprozZykrDQHyaWtcgGjXrQrlZbj69Q/edit#) is sparse on requirements for the Proportions graph:

> Proportions graph:
> * Grab data and generation number for what’s visible on graph
> * Grab data for all generations

This needs to be fleshed out more, including:
* Is this a reasonably complete set of requirements? 
* How should these requirements present in Studio? (tree structure,...)
* What should appear in the data stream?
* Do any of these requirements require methods in an IO Type API?
* How to deal with scalability - this is a lot of data. 

I'm anticipating that I'll be ready to start implementing the Population graph around 5/11/2020.

**Comment by pixelzoom** [comment]
5/7/2020 design meeting @amanda-phet @kathy-phet @ariel-phet @arouinfar @samreid 

We review the current implementation in Studio, and it all looks good. 

Discussion about these 2 items:
> * Grab data and generation number for what’s visible on graph

This will be done via Properties.

> * Grab data for all generations

Would like to get all of the data at once, and have it clearly labeled.  @samreid suggested JSON, we brainstormed a couple of different formats, and decided on something like this as a good starting point: 

```
{
  start: {
    total: 10,
    fur: { normal: 5, mutant: 5 },
    ears: { normal: 10, mutant: 0 },
    teeth: { normal: 10, mutant: 0 }
  },
  end: {
    total: 5,
    fur: { normal: 5, mutant: 0 },
    ears: { normal: 10, mutant: 0 },
    teeth: { normal: 10, mutant: 0 }
  },
}
```

* Each generation's data will be represented by the above data structure.
* Data for all generations will be stored in an ObservableArray, with the generation number serving as the array index.
* Values for `normal` and `start` fields may be counts or percentages, not sure which is best yet.
* "end" data is before mating has occurred

Previous generation data is static. Once a generation has completed, its data will not change.

Current generation data is dynamic. It has no "end" data, and has running totals that are continuously updated. So current generation data will be stored differently.

**Comment by amanda-phet** [comment]
Megan had a quick reply and might have more thoughts in a later email, but her response what that the data stream would probably be most useful as the raw values.

**Comment by pixelzoom** [comment]
Raw values being the counts, or the percentages in decimal form?

**Comment by amanda-phet** [comment]
Counts.

**Comment by pixelzoom** [comment]
@amanda-phet @kathy-phet @ariel-phet The Proportions graph is completed and ready for review.  

Here's an overview of the PhET-iO instrumentation. Sorry that this overview is long, but this is a complicated feature. Renaming phetioIDs here is easy.  Changing the structure would be major work.

**Proportions model**

Current generation data is dynamic, while previous generation is static, so it was not practical to put all data in a single PhET-iO element.  Data is therefore divided between separate elements for current and previous generations.  Here's how the Proportions model looks in Studio, for example `naturalSelection.labScreen.model.proportionsModel`:

<img width="275" alt="screenshot_334" src="https://user-images.githubusercontent.com/3046552/82956108-4cfb2300-9f6d-11ea-8042-ec9ea9154d5c.png">

**Proportions data for the current generation** 

The current counts for the current generation (shown as "Currently" in the graph) are identical to the counts for live bunnies. They are therefore implemented as linked element `currentCountsProperty`, linked to
`naturalSelection.labScreen.model.bunnyCollection.liveBunnies.countsProperty`.
`liveBunnies.countsProperty` is not stateful, because it's computed as bunnies are saved/restored. You can examine the value in Studio, for example:

<img width="599" alt="screenshot_338" src="https://user-images.githubusercontent.com/3046552/82957229-c1cf5c80-9f6f-11ea-8af9-c5d5757ae653.png">


`currentStartCountsProperty` records the counts at the start of the current generation. Because it is historical data, is cannot be computed from the current bunny population.  It's state therefore needs to be saved/restored, and requires a custom IO Type, `BunnyCountsIO`.  It looks like this in Studio:

<img width="601" alt="screenshot_339" src="https://user-images.githubusercontent.com/3046552/82957243-c72ca700-9f6f-11ea-904e-ed9e2bca71d5.png">

**Proportions data for previous generations**

`previousCounts` is an ObservableArray that records start and ends counts for previous generations. It looks like this in Studio:

<img width="598" alt="screenshot_337" src="https://user-images.githubusercontent.com/3046552/82956628-6cdf1680-9f6e-11ea-8019-a759506deb89.png">

Like `currentStartCountsProperty`, `previousCounts` also must be saved/restored, and requires a custom IO Type, `ProportionsCountIO`.  Studio cannot display the contents of an ObservableArray, so you'll need to inspect its value in the State Wrapper. For example, here is the data stream for previous generations 0, 1, & 2:

```
"naturalSelection.labScreen.model.proportionsModel.previousCounts": {
        "array": [
            {
                "generation": 0,
                "startCounts": {
                    "totalCount": 2,
                    "whiteFurCount": 2,
                    "brownFurCount": 0,
                    "straightEarsCount": 2,
                    "floppyEarsCount": 0,
                    "shortTeethCount": 2,
                    "longTeethCount": 0
                },
                "endCounts": {
                    "totalCount": 2,
                    "whiteFurCount": 2,
                    "brownFurCount": 0,
                    "straightEarsCount": 2,
                    "floppyEarsCount": 0,
                    "shortTeethCount": 2,
                    "longTeethCount": 0
                }
            },
            {
                "generation": 1,
                "startCounts": {
                    "totalCount": 6,
                    "whiteFurCount": 6,
                    "brownFurCount": 0,
                    "straightEarsCount": 6,
                    "floppyEarsCount": 0,
                    "shortTeethCount": 6,
                    "longTeethCount": 0
                },
                "endCounts": {
                    "totalCount": 4,
                    "whiteFurCount": 4,
                    "brownFurCount": 0,
                    "straightEarsCount": 4,
                    "floppyEarsCount": 0,
                    "shortTeethCount": 4,
                    "longTeethCount": 0
                }
            },
            {
                "generation": 2,
                "startCounts": {
                    "totalCount": 20,
                    "whiteFurCount": 20,
                    "brownFurCount": 0,
                    "straightEarsCount": 20,
                    "floppyEarsCount": 0,
                    "shortTeethCount": 20,
                    "longTeethCount": 0
                },
                "endCounts": {
                    "totalCount": 14,
                    "whiteFurCount": 14,
                    "brownFurCount": 0,
                    "straightEarsCount": 14,
                    "floppyEarsCount": 0,
                    "shortTeethCount": 14,
                    "longTeethCount": 0
                }
            }
        ]
    },
```

**Comment by pixelzoom** [comment]
Notes for reviewers:

You can review using master or 1.0.0-dev.43:
* https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.43/phet-io/
* https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.43/phet/natural-selection_en_phet.html

The basic models for environmental factors (wolves, food) have been implemented, see https://github.com/phetsims/natural-selection/issues/86.  So you should be able to see differences in Start vs End data on the Proportions graph.

**Comment by kathy-phet** [comment]
Chris, I don't have much time today, but took quick test drive. The charts look good to me, although could you make the wolves eat more white bunnies so that I can see a bigger change., and the bunnies don't take over the world. It would make it easier to evaluate the graphs. They don't seem to eat many bunnies right now. Not sure how that parameter gets set. Thanks!

**Comment by pixelzoom** [comment]
@kathy-phet You can change the parameters for the wolves and food via query parameters. See #86.

**Comment by amanda-phet** [comment]
I really like these Proportion graphs! They are so nice for seeing the changes in bunny population with the different environmental factors, and I think they are working really well right now for comparing populations. My only thought is that it's a lot of information at once (potentially) and I wonder if we should be displaying each trait with a checkbox.. maybe something similar to the Population graph, where it only shows the relevant graphs. I'm not sure, just thinking out loud. 

The PhET-iO solution you've come up with seems like it is working well. I checked out the proportionsModel and thought it was all pretty clear. There might be a bug with `valuesVisibleProperty` and I can elaborate in a separate issue if @pixelzoom isn't aware. I also appreciate that you included an example of the array- it looks like the spec we discussed, so I'm pleased with it!

**Comment by pixelzoom** [comment]
@amanda-phet said:
> ... My only thought is that it's a lot of information at once (potentially) and I wonder if we should be displaying each trait with a checkbox.. maybe something similar to the Population graph, where it only shows the relevant graphs. ...

There would need to be 1 checkbox for each trail, something like this:

<img width="225" alt="screenshot_345" src="https://user-images.githubusercontent.com/3046552/83058521-b6cf0780-a015-11ea-8244-5df7a3907f55.png">

Since this makes the panel ~20% wider, it would result in the Proportions graph getting narrower, which will still probably be OK.  And it would take somewhere in the 2-3 hours range to make this change.  If this is something you want to do, create a new GitHub issue that references this comment, and assign to me. 

> There might be a bug with valuesVisibleProperty and I can elaborate in a separate issue if @pixelzoom isn't aware.

Thanks, tracking in https://github.com/phetsims/natural-selection/issues/88

**Comment by amanda-phet** [comment]
That is exactly what I had in mind, but I'd like others to play with the sim and Proportions graph to see what they think. We could also see how interviews go before making a change like this.

**Comment by pixelzoom** [comment]
5/28/2020 design meeting @amanda-phet @kathy-phet @ariel-phet 

Try something like https://github.com/phetsims/natural-selection/issues/57#issuecomment-634859066, but with something less "heavy" than the curly bracket. @pixelzoom will make a new issue for this.

**Comment by pixelzoom** [comment]
Remaining work for this issue is for @kathy-phet to do a review.

**Comment by pixelzoom** [comment]
Raising priority to high. This has been ready for review for 14 days.

**Comment by amanda-phet** [comment]
6/11/20 design meeting: looks fine.
