### ISSUE TITLE
PhET-iO requirements for Pedigree graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#58]
As we've discovered with other parts of this sim, knowing PhET-iO retirements up front informs how the features are implemented.   And that's going to be especially true for the graphs.  In https://github.com/phetsims/natural-selection/issues/21, the decision was made to implement sim-specific graphs, and not to use griddle or a 3rd-party library.  The graphs must also be PhET-iO instrumented.  So the graphs in Natural Selection are going to be relatively expensive.

[Natural Selection: PhET-iO Design](https://docs.google.com/document/d/1vjsUiRdfbpPRWprozZykrDQHyaWtcgGjXrQrlZbj69Q/edit#) is sparse on requirements for the Pedigree graph:

> Pedigree:
> * Come up with a string representation of the Pedigree tree, set in a Property (null if no bunny is selected)

This needs to be fleshed out more, including:
* Is this a reasonably complete set of requirements? 
* How should these requirements present in Studio? (tree structure,...)
* What should appear in the data stream?
* Do any of these requirements require methods in an IO Type API?

I'm anticipating that I'll be ready to start implementing the Pedigree graph around 5/18/2020.

**Comment by pixelzoom** [comment]
I implemented a quick-and-dirty version of the Pedigree graph, so that we have something concrete to discuss in our design meeting.  All of the info that has been requested is visible on the graph.  It still needs a lot of work on layout and polish.

**Comment by pixelzoom** [comment]
@amanda-phet and I discussed this requirement a bit on Zoom:

> * Come up with a string representation of the Pedigree tree, set in a Property (null if no bunny is selected)

I'm not certain that we want to provide such a string representation. First, a string representation will need to be parsed by the client, and that's not easy.  Second, all of the information is already present elsewhere.  For example, if I know that the selected bunny is `bunny_12`, then I can inspect that element, determine its parents, and similarly inspect the parents, thus giving me all of the tree information.

If we do want to provide a string representation, then JSON is probably safest and easiest to parse.  And there are lots of ways to represent this in JSON.

Here's JSON that is nested, resembling the tree structure:

```js
{
  "pedigree": {
     "phetioID": "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_36"
     "father": {
        "phetioID": "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_17",
        "father": {
           ...
        }
        "mother": {
           ...
        }
      },
      "mother": {
        "phetioID": "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_12",
        "father": {
           ...
        }
        "mother": {
           ...
        }
      }
   }
} 
```

... where every node in the Pedigree tree has the format:

```js
{
  "phetioID":
  "father": {...},
  "mother": {...}
}
```

Here's another approach, where the tree structure is flattened:

```
{
  "selectedBunny": " "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_36",
  "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_36": {
     father:  "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_17",
     mother:  "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_12"
   },
  "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_17": {
     father: "...",
     mother: "..."
   },
  "naturalSelection.labScreen.model.bunnyCollection.bunnyGroup.bunny_12": {
     father: "...",
     mother: "..."
   },
   ...
}
```

Thoughts from the design team?

**Comment by pixelzoom** [comment]
I could also use a consultation with the PhET-iO team on the "string representation of the Pedigree tree" requirement, so that I understand what information is already available via the API.

**Comment by pixelzoom** [comment]
I could also use a consultation with the PhET-iO team on the "string representation of the Pedigree tree" requirement, so that I understand what information is already available via the API. @samreid @zepumph @chrisklus

**Comment by pixelzoom** [comment]
5/7/2020 design meeting

* Add Bunny `Property.<string> genotypeAbbreviationProperty`

* Wait until someone asks for a representation of the tree

**Comment by pixelzoom** [comment]
All of the requests in the previous comment have been completed. 

I'll leave this issue open until the Pedigree graph is completed, at which time these requirements can be verified.

**Comment by pixelzoom** [comment]
@amanda-phet The Pedigree graph is feature complete and ready for review.  

See master or 1.0.0-dev.36:

* https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.36/phet-io/
* https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.36/phet/natural-selection_en_phet.html

**Comment by pixelzoom** [comment]
Let's also make sure that these requirements get propagated to the PhET-iO Design document, so that QA will have this information during dev/RC testing.

**Comment by amanda-phet** [comment]
I confirmed that the listed features are all present in studio. I'm not sure where to put this information in the design document, since the section that mentioned wanting a string output was in a meeting note, not anywhere in the design requirements.

**Comment by pixelzoom** [comment]
Labeling for design meeting to discuss whether to discuss how PhET-iO requirements will be communicated to QA, whether to keep PhET-iO design doc up to date, and (if so) whose role that is.

**Comment by pixelzoom** [comment]
5/14/2020 design meeting:

Need to have a discussion with QA about how to integrate PhET-iO testing into the QA process. Create an issue and meet during either phet-io or design meeting.  @pixelzoom will create issue, assign to @ariel-phet.
