### ISSUE TITLE
issues with environment background artwork

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#6]
I've added the background artwork for the environment to [1.0.0-dev.6?dev](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.6/phet/natural-selection_en_phet.html?dev).  The artwork was exported from assets/natural-selection-artwork.ai.  

This issue identifies problems with the current artwork. See screenshots below.

- [x] The artwork does not fill the play area. Note the thin unfilled strip at the right edge.  Artwork is scaled to the height of the play area, then clipped to the play area. The size of the play area is computed to fill as much space as is available, after accounting for margins and other UI components.  The size is currently 768x309, but that is highly likely to change in the future. So we definitely need to make the artwork wider, and I recommend making it a bit wider than it needs to be. 

- [x] The horizon line is different in the 2 background images. The horizontal red line (shown with `?dev`) indicates the horizon line - the furthest away that bunnies, wolves, and food can be located.  That line must be the same for both environments.  And that line is current further away in the equator artwork.

- [x] Background images visually conflict with important UI components.  For equator, "Limited Food" checkbox and the Generation Clock are both in conflict with clouds.  For arctic, "Limited Food" is in conflict with a cloud, while the Generation Clock and environment radio buttons are in conflict with the mountains.  If we must have clouds, it would be better to use separate artwork, so they can be moved around to avoid conflicts.  I'm not sure what to do about the mountains - they are overbearing. 

- [x] For arctic, white bunnies will be very visible against the dark gray mountains. That seems to conflict with the goals of the background artwork, which is to make the white bunnies blend in, so that they are not selected by the wolves.   Should the mountains be white? 

- [x] Using a different (darker) color for the hills looks strange to me.  It causes each hill to have a distracting horizontal line at its base.

- [x] My eye is drawn to an illusionary rectangle that occurs in the equation artwork. It's caused by the horizontal line at the base of each hill (caused by the darker hill color), and the flat bottom of the cloud. And it's in an unfortunate location, just below the Generation Clock. I've outlined it here, see if you can spot it in the full screenshot below, or while running the sim.
![screenshot_1651](https://user-images.githubusercontent.com/3046552/67895273-c9d13600-fb1f-11e9-8701-f2e59ad6c2f2.jpg)

Equator:
<img width="1022" alt="screenshot_1650" src="https://user-images.githubusercontent.com/3046552/67893948-37c82e00-fb1d-11e9-8139-746e876e6026.png">

Arctic:
<img width="1020" alt="screenshot_1649" src="https://user-images.githubusercontent.com/3046552/67893953-3a2a8800-fb1d-11e9-8c4e-d9134a22f27f.png">

**Comment by pixelzoom** [comment]
> So we definitely need to make the artwork wider, and I recommend making it a bit wider than it needs to be.

Another option would be to scale the background image in the x dimension to fit the width of the play area.  If the scaling isn't too severe, it should look  OK.

**Comment by pixelzoom** [comment]
Until we revise the backgrounds, I've simplified them, see screenshots below.  I removed the clouds for Equator (which I think would be a good simplification), and removed the mountains and one of the clouds for Arctic.

<img width="823" alt="screenshot_1684" src="https://user-images.githubusercontent.com/3046552/68551512-e5172d80-03ca-11ea-8df5-e475f5306468.png">
<img width="819" alt="screenshot_1685" src="https://user-images.githubusercontent.com/3046552/68551515-e9434b00-03ca-11ea-979f-1d1ce8229386.png">

**Comment by pixelzoom** [comment]
Until we revise the backgrounds, I've simplified them, see screenshots below.  I removed the center trees and all clouds for Equator (which I think would be a good simplification), and removed the mountains and one of the clouds for Arctic.  These PNGs are 781x316.

In general, it would be good to avoid putting anything in the top center (clock) and top-right (radio buttons) of the backgrounds.

<img width="824" alt="screenshot_1687" src="https://user-images.githubusercontent.com/3046552/68551600-d11ffb80-03cb-11ea-878c-095c4fcea33c.png">

<img width="819" alt="screenshot_1685" src="https://user-images.githubusercontent.com/3046552/68551515-e9434b00-03ca-11ea-979f-1d1ce8229386.png">

**Comment by pixelzoom** [comment]
Other parts of the background to keep simple:

* bottom center (Add a Mate button)
* right side, below radio buttons (Mutation Coming alerts)

**Comment by pixelzoom** [comment]
On 11/12/19 Slack, @amanda-phet asked my opinion about this more simplified version of the background artwork, and whether this should be PNG files or programmatically created. 

![image](https://user-images.githubusercontent.com/3046552/69268728-eb589700-0b8c-11ea-89f6-7b0a18b58ad0.png)

I said:

> Those look nice. I definitely prefer these simpler backgrounds, especially since we have UI elements (clock, radio buttons) and dynamic food (type and quantity) in the play area.   I think we should still use PNG files, because I suspect that others may disagree.  Cloud on the right in “arctic” might conflict with radio buttons.  I definitely agree with ditching the trees — it will emphasize the food.

**Comment by amanda-phet** [comment]
@pixelzoom maybe during our design meeting (if time) we can discuss the backgrounds to see what @kathy-phet and @ariel-phet think, and if it's feasible for you to create them in code or if you'd still like them as PNGs.

**Comment by pixelzoom** [comment]
11/21/19 design meeting:

Consensus was that the simpler backgrounds (as in https://github.com/phetsims/natural-selection/issues/6#issuecomment-556250687) are nice.   @amanda-phet will provide .ai file.

**Comment by amanda-phet** [comment]
I uploaded the ai asset for new background artwork. Please let me know if I can help with exporting at the correct dimensions or where the horizon line should be, or anything else.

**Comment by pixelzoom** [comment]
Thanks @amanda-phet. I've integrated the new backgrounds, screenshots below. You can test drive in [1.0.0-dev.10](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.10/phet/natural-selection_en_phet.html).  Add `?dev` to see the horizon line.  Close the "Mutation Coming" alerts to see what it looks like without them.   

My only suggestion might be to move the rightmost cloud a bit to the left in the arctic background, so it's a little further away from the radio buttons.

<img width="825" alt="screenshot_1703" src="https://user-images.githubusercontent.com/3046552/69386141-ef64e180-0c7e-11ea-88ae-c8e1183d9c3c.png">
<img width="826" alt="screenshot_1704" src="https://user-images.githubusercontent.com/3046552/69386143-f12ea500-0c7e-11ea-86da-550a692b28c4.png">

**Comment by amanda-phet** [comment]
Is the horizon line the lowest point for a bunny's feet? If so, I think that looks good to me. 

![image](https://user-images.githubusercontent.com/7852916/69444634-fc7ce180-0d0d-11ea-8940-e60ef4195600.png)

![image](https://user-images.githubusercontent.com/7852916/69444665-0868a380-0d0e-11ea-99c7-9bf7507dbb62.png)

**Comment by amanda-phet** [comment]
I shifted the clouds, but when I exported the new arctic artwork I was off by 1px from what you have, so I will let you create the new image (sorry).

**Comment by pixelzoom** [comment]
> Is the horizon line the lowest point for a bunny's feet? If so, I think that looks good to me.

Yes.

> I shifted the clouds, but when I exported the new arctic artwork I was off by 1px from what you have, so I will let you create the new image (sorry).

No problem, I've update in the above commit.

**Comment by pixelzoom** [comment]
I'm going to go ahead and close this issue.  This is looking good, and we can make additional tweaks later, if needed.
