### ISSUE TITLE
add "None" graph radio button

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#66]
From 4/30/2020 design meeting @amanda-phet @kathy-phet @arouinfar @ariel-phet @samreid

@kathy-phet asked to add a "None" choice to the graph radio button group.  It will be the last (bottom) choice.

**Comment by pixelzoom** [comment]
I added "None" in the above commit.  Screenshot below shows how it looks.  @amanda-phet or @kathy-phet please review in master.

<img width="1120" alt="screenshot_291" src="https://user-images.githubusercontent.com/3046552/80763592-1829b680-8afc-11ea-8a8d-19d0fa3d18a9.png">

**Comment by amanda-phet** [comment]
Looks good to me.
