### ISSUE TITLE
disable UI components when "Start Over" button is visible

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#67]
From 4/30/2020 design meeting @amanda-phet @kathy-phet @arouinfar @ariel-phet @samreid

We reviewed the UI components that are disabled when the "Start Over" button is visible. Per the design doc, the sim currently disables:

* Add Mutations panel
* Environmental Factors panel
* Time controls

We would also like to disable:

* Environment (equator, arctic) radio button group

So basically the user should be able to review the graphs, but not change anything else.

**Comment by pixelzoom** [comment]
Done. @amanda-phet please review in master.  Let bunnies take over the world. Close the dialog, and verify that UI components are disabled.  Press "Start Over" and verify that UI components are enabled.

**Comment by amanda-phet** [comment]
I notice something funny with these buttons. For all other disabled components, if I try to hover or click them, the cursor remains an arrow. But for the environment radio buttons, if I try to click on them, the cursor blinks to a hand and then back to an arrow. Just an odd thing I wanted to point out, but if there's nothing to do to change that then we can close this. However if there is something special going on with those buttons I'm interesting in understanding it.

**Comment by pixelzoom** [comment]
@amanda-phet thanks for reporting.  What you're seeing actually has nothing to do with the radio buttons.  If you click anywhere in the environment (anywhere not on a bunny), it clears the bunny selection.  And by default, the scenery listener uses a hand cursor.  In the above commit, I've adjusted that cursor so that there is no change.  If it looks good to you in master, you can close this issue.

**Comment by amanda-phet** [comment]
I was wondering if it had something to do with bunny selection. Thanks for making that change. It looks good to me.
