### ISSUE TITLE
State wrapper bug with "Add Mutations" panel

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#68]
The "Add Mutations" panel is not behaving properly in the State wrapper.  After pressing one of the buttons, icons showing the dominant and recessive alleles should appear.  The do not appear in the downstream sim:

<img width="767" alt="screenshot_293" src="https://user-images.githubusercontent.com/3046552/80840953-aadd5a80-8bbb-11ea-8a01-48bbfd85c2e1.png">

Steps to reproduce:

1. Start sim in State wrapper
2. Go to _Lab_ screen
3. In the "Add Mutations" panel, press either of the buttons to the right of "Fur"
4. The buttons disappear and the icons should appear.

Since we don't know which allele will be dominant vs recessive, the icons are added when the button is pressed.  For example, here's the dominant (left) button lister in AddMutationsPanel.js:

```js
    // When the dominant button is pressed...
    dominantButton.addListener( () => {

      // make the mutation dominant and the non-mutation recessive
      gene.dominantAlleleProperty.value = gene.mutantAllele;
      this.children = [ labelNodeWrapper, mutantAlleleWrapper, standardAlleleWrapper ];

      // signal that a mutation is coming in the next generation
      gene.mutationComingProperty.value = true;
    } );
```

I'm guessing that children are part of the state, and that after the listeners call to `this.children =`, the State wrapper is restoring the original children (which did not include the icons).  If that's the case, that sure seems like a general problem that we'll be encountering. 

Can someone on the PhET-iO team help me understand this, and recommend a fix?

**Comment by pixelzoom** [comment]
In the above commit, I change the implementation of AddMutationsPanel.js so that children are not changed.   This resolve the problem.  But I'd still like to know why setting children is a problem for the State wrapper, and how to address it in the future.

**Comment by zepumph** [comment]
Indeed children are not stored in state. The best thought I can think of right now is to try to drive this operation from a Property. This would allow the button listener to change the Property, as well as the state engine to change the Property. 

We are in new territory, so I'm definitely brainstorming. 

I could see you implementing a `childrenProperty` that was an `PropertyIO( ArrayIO( ReferenceIO( NodeIO ) ) )` (ugly). I could also see potentially moving the children out of this listener to instead a listener to the gene.dominateAlleleProperty (not sure if that would work in this context). 

All this is to be weighed againt the patch you committed, though note I didn't fully understand it.

Let me know what you think!

**Comment by pixelzoom** [comment]
Thanks @zepumph.  I don't fully understand why the original implementation was a problem.  But the new implementation resolves it and (more importantly) is a superior solution.  I don't have time to investigate this further, so I'll wait to see if it occurs again in the future. 

Closing.
