### ISSUE TITLE
how to implement the Intro screen

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#70]
The Intro and Lab screens have identical model and view implementations.  The only difference is that the Intro screen does have the Ears, Teeth, and Limited Food features.

If this were a non-PhET-iO sim, it would be an easy matter to just hide the UI components related to those features, probably 1-2 hours of work.   But PhET-iO complicates things because the full model and view will be present for both screens.

Options:

(1) Use flags to specify whether features are visible, and propagate those flags to model. The model decides whether to create Ears, Teeth, and Limited Food based on flags.  View has conditional logic for whether those things exist in model.  
Pros: elements won't exist, so won't appear in PhET-iO API.  
Cons: deep propagating, some conditional logic in model, lots of conditional logic in view, client can't add Lab features to Intro screen.

(2) Use flags to specify whether features should be instrumented, and propagate those flags to model and view.  
Pros: Less conditional logic than (1), elements won't appear in PhET-iO API.
Cons: deep propagation, conditional logic for creating tandems, client can't add Lab features to Intro screen

(3) Generalize things a lot more so that model can contain any set of genes and environmental factors, and UI can be created by iterating over these sets.  
Pros: elements won't appear in PhET-iO API
Cons: code will likely be more complicated and less understandable, generalization likely doesn't exist for environmental factors, cost to build in unneeded generality, client can't add Lab features to Intro screen

(4) Create Intro and Lab screens identically.  Hide the Ears, Teeth, and Limited Food UI components in the Intro screen.  Preferably by setting their visibilityProperty, just like the iO client would do.
Pros: identical elements in both screens, easy to maintain, easy to specify initial configuration, client can treat both screens as having identical APIs
Cons: elements that are not part of the default Intro configuration will appear in the PhET-iO API

**Comment by pixelzoom** [comment]
At 4/30/20 design meeting, I convinced the design team (@amanda-phet @arouinfar @kathy-phet @ariel-phet) that (4) is the best path to pursue.

**Comment by pixelzoom** [comment]
In IntroScreenView.js, I added a TODO about which elements need to be hidden for the Intro screen:

```js
    //TODO see https://github.com/phetsims/natural-selection/issues/70
    // hide Ears, Teeth, and Limited Food features, by setting visibleProperty for associated PhET-iO elements
    // naturalSelection.labScreen.view.addMutationsPanel.earsRow
    // naturalSelection.labScreen.view.addMutationsPanel.teethRow
    // naturalSelection.labScreen.view.environmentalFactorsPanel.limitedFoodCheckbox
    // naturalSelection.labScreen.view.graphs.pedigreeNode.allelesPanel.earsRow
    // naturalSelection.labScreen.view.graphs.pedigreeNode.allelesPanel.teethRow
    // naturalSelection.labScreen.view.graphs.populationNode.populationPanel.straightEarsCheckbox
    // naturalSelection.labScreen.view.graphs.populationNode.populationPanel.floppyEarsCheckbox
    // naturalSelection.labScreen.view.graphs.populationNode.populationPanel.shortTeethCheckbox
    // naturalSelection.labScreen.view.graphs.populationNode.populationPanel.longTeethCheckbox
    // naturalSelection.labScreen.view.graphs.proportionsNode.proportionsPanel.legendNode.earsLegendNode
    // naturalSelection.labScreen.view.graphs.proportionsNode.proportionsPanel.legendNode.teethLegendNode
    // naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.earsColumn
    // naturalSelection.labScreen.view.graphs.proportionsNode.proportionsGraphNode.teethColumn
```

**Comment by pixelzoom** [comment]
In Slack phet-io channel, I asked about programmatically accessing elements using their phetioID.   The recommended way of accessing elements in brand=phet-io is:

`phet.phetio.phetioEngine.phetioObjectMap[ phetioID ]`

But this is not currently possible in brand=phet, because phetioEngine does not exist.  The iO team is going to investigate how to make this happen.

**Comment by pixelzoom** [comment]
In Slack phet-io channel, I asked about programmatically accessing elements using their phetioID.   The recommended way of accessing elements in brand=phet-io is:

`phet.phetio.phetioEngine.phetioObjectMap[ phetioID ]`

But this is not currently possible in brand=phet, because phetioEngine does not exist.  The iO team is going to investigate how to make this happen. 

FYI @samreid @zepumph @chrisklus

**Comment by samreid** [comment]
With these changes:

<details>

```diff

Index: js/common/view/NaturalSelectionScreenView.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/NaturalSelectionScreenView.js	(revision f8b8572eeb2347a3db2f7e6b30acb9697d6ee03e)
+++ js/common/view/NaturalSelectionScreenView.js	(date 1588718293662)
@@ -64,11 +64,13 @@
       fixedWidth: rightOfViewportWidth,
       tandem: options.tandem.createTandem( 'addMutationsPanel' )
     } );
+    this.addMutationsPanel = addMutationsPanel;
 
     const environmentalFactorsPanel = new EnvironmentalFactorsPanel( model.environmentModel, {
       fixedWidth: rightOfViewportWidth,
       tandem: options.tandem.createTandem( 'environmentalFactorsPanel' )
     } );
+    this.environmentalFactorsPanel = environmentalFactorsPanel;
 
     const panelsParent = new VBox( {
       children: [ addMutationsPanel, environmentalFactorsPanel ],
Index: js/common/view/EnvironmentalFactorsPanel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/EnvironmentalFactorsPanel.js	(revision f8b8572eeb2347a3db2f7e6b30acb9697d6ee03e)
+++ js/common/view/EnvironmentalFactorsPanel.js	(date 1588718330097)
@@ -42,6 +42,9 @@
       tandem: options.tandem.createTandem( 'titleNode' )
     } );
 
+    const limitedFoodCheckbox = new LimitedFoodCheckbox( environmentModel.foodSupply.isLimitedProperty, {
+      tandem: options.tandem.createTandem( 'limitedFoodCheckbox' )
+    } );
     const checkboxes = new VBox( merge( {}, NaturalSelectionConstants.VBOX_OPTIONS, {
       children: [
 
@@ -56,18 +59,19 @@
         } ),
 
         // Limited Food
-        new LimitedFoodCheckbox( environmentModel.foodSupply.isLimitedProperty, {
-          tandem: options.tandem.createTandem( 'limitedFoodCheckbox' )
-        } )
+        limitedFoodCheckbox
       ]
     } ) );
 
+
     const content = new VBox( merge( {}, NaturalSelectionConstants.VBOX_OPTIONS, {
       children: [ titleNode, checkboxes ]
     } ) );
 
     super( content, options );
 
+    this.limitedFoodCheckbox = limitedFoodCheckbox;
+
     // Set the panel's title to singular or plural, depending on how many checkboxes are visible.
     checkboxes.boundsProperty.link( () => {
       const visibleCount = _.filter( checkboxes.children, child => child.visible ).length;
Index: js/common/view/AddMutationsPanel.js
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
--- js/common/view/AddMutationsPanel.js	(revision f8b8572eeb2347a3db2f7e6b30acb9697d6ee03e)
+++ js/common/view/AddMutationsPanel.js	(date 1588718269364)
@@ -96,6 +96,7 @@
     const earsRow = new Row( genePool.earsGene, iconsAlignGroup, labelColumnAlignGroup, buttonColumnsAlignGroup, {
         tandem: options.tandem.createTandem( 'earsRow' )
       } );
+
     const teethRow = new Row( genePool.teethGene, iconsAlignGroup, labelColumnAlignGroup, buttonColumnsAlignGroup, {
         tandem: options.tandem.createTandem( 'teethRow' )
       } );
@@ -119,7 +120,7 @@
 
     super( content, options );
 
-    // @private
+    // @public (for customization)
     this.furRow = furRow;
     this.earsRow = earsRow;
     this.teethRow = teethRow;

```

</details>

These lines can be added to the end of the IntroScreenView constructor:

```js
this.addMutationsPanel.earsRow.visibleProperty.value = false;
this.addMutationsPanel.teethRow.visibleProperty.value = false;
this.environmentalFactorsPanel.limitedFoodCheckbox.visibleProperty.value = false;
```

**Comment by pixelzoom** [comment]
@samreid recommended a patch in https://github.com/phetsims/natural-selection/issues/69#issuecomment-624345512 for accessing the Nodes that need to be hidden. It doesn't involve accessing them by phetioID, it involves adding them to the public interface of Node instances.  I was hoping not to have to add them to the non-iO interfaces, but I'll test-drive that approach and report back.

**Comment by pixelzoom** [comment]
Thanks for the suggestion and patch @samreid.  This approach doesn't involve accessing them by phetioID, it involves adding them to the public non-iO interface of classes.  I was hoping not to have to add them to the non-iO interfaces, but I'll test-drive that approach and report back.

**Comment by pixelzoom** [comment]
I accomplished what I needed to do quickly with this approach, see the above commit.   The downside is that I need to have specific fields for specific alleles, like these in PopulationPanel.js:

```js
    this.straightEarsCheckbox = straightEarsCheckbox;
    this.floppyEarsCheckbox = floppyEarsCheckbox;
    this.shortTeethCheckbox = shortTeethCheckbox;
    this.longTeethCheckbox = longTeethCheckbox;
```

I'm currently creating these checkboxes using sort of a brute-force, boilerplate approach, where I know that the GenePool has genes for fur, ears, and teeth.  I had hoped to revisit this (and other) code and generate these checkboxes by iterating over the Genes in the GenePool -- in which case I wouldn't have specific fields like this.  And there are quite a few examples of this.  So if I use this approach to setting visibleProperty, then I will likely keep the brute-force approach. 

With the phetioID approach that I had originally hoped for, I could count on having a way to access these elements without having to create an field in some core type.

@samreid thoughts?

**Comment by pixelzoom** [comment]
Note that iterating over GenePool will also have a downside -- I'll need to generate tandem names by concatenating a prefix (the gene or allele name) and a suffix (e.g. "Checkbox", "LegendNode"). 
Genes and Alleles would each have a `tandemNamePrefix` field -- "fur", "ears", and "teeth" for the 3 genes, "whiteFur", "brownFur", etc. for the alleles.

Here's how the checkbox related to the fur gene's mutant allele might be created:

```
new CheckBox( ..., {
  tandem: options.tandem.createTandem( `${gene.mutantAllele.tandemNamePrefix}Checkbox` )
} );
```

I don't like the fact that this involves concatenation.  But there are many UI components related to genes and alleles, and I don't think we want a separate field for each complete tandem name in the Gene and Allele model classes.

**Comment by pixelzoom** [comment]
Note that iterating over GenePool will also have a downside -- I'll need to generate tandem names by concatenating a prefix (gene or allele) and a suffix (e.g. "Checkbox", "LegendNode"). 
Genes and Alleles would each have a `tandemNamePrefix` field -- "fur", "ears", and "teeth" for the 3 genes, "whiteFur", "brownFur", etc. for the alleles.

For example, here's how the checkboxes for all of the alleles in the gene pool would be created:

```
const checkboxes = [];
genePool.forEach( gene => {

  // checkbox for the normal allele
  const normalCheckbox = new CheckBox( ..., {
  tandem: options.tandem.createTandem( `${gene.normalAllele.tandemNamePrefix}Checkbox` )
} );
  checkboxes.push( normalCheckbox );

  // checkbox for the mutant allele
  const mutantCheckbox = new CheckBox( ..., {
  tandem: options.tandem.createTandem( `${gene.mutantAllele.tandemNamePrefix}Checkbox` )
} );
  checkboxes.push( mutantCheckbox );
}
```

I don't like the fact that this involves concatenation.  But there are many UI components related to genes and alleles, and I don't think we want a separate field for each complete tandem name in the Gene and Allele model classes.

**Comment by samreid** [comment]
How about just assigning instance variables for the sparse set that needs customization?

**Comment by pixelzoom** [comment]
That's what I'm doing now. But if I'm iterating over the GenePool as in the example in https://github.com/phetsims/natural-selection/issues/70#issuecomment-624378873,  how do I identify which checkbox to assign to (for example) `this.floppyEarsCheckbox`?

**Comment by pixelzoom** [comment]
That's what I'm doing now -- there are fields only for the UI components that need to be set to `visibleProperty.value = false` in IntroScreenView.

But if I'm iterating over the GenePool as in the example in https://github.com/phetsims/natural-selection/issues/70#issuecomment-624378873,  how do I identify which checkbox to assign to (for example) `this.floppyEarsCheckbox`?

**Comment by samreid** [comment]
You could brute force the names and avoid iterating over them.  Or if you want to keep the iteration and concatenated names, you could assign attributes like:

```js
  // checkbox for the mutant allele
  const mutantCheckboxName = `${gene.mutantAllele.tandemNamePrefix}Checkbox`;
  this[mutantCheckboxName] = new CheckBox( ..., {
    tandem: options.tandem.createTandem( mutantCheckboxName)
  } );
```

**Comment by pixelzoom** [comment]
I'm brute-forcing the names now, no iteration.   See checkboxes in PopulationPanel.js for the most extreme example. 

I hadn't thought of using `this[string]`, that a JavaScript construct that I try to avoid.  It also will end up creating a field for all UI components, not just the ones that I want to customize for the Intro screen. But I guess I'll consider that and the brute-force approach as my 2 alternatives.

**Comment by pixelzoom** [comment]
I'm brute-forcing now, no iteration.   See creating of checkboxes in PopulationPanel.js for the most extreme example. 

I hadn't thought of using `this[string]`, that's a JavaScript construct that I try to avoid.  It also will end up creating a field for all UI components instantiated via iteration, not just the ones that I want to customize for the Intro screen. But I guess I'll consider that and the brute-force approach as my 2 alternatives.

Thanks for the input.

**Comment by samreid** [comment]
Generalizing the pattern from this issue...

Are we suggesting that:

```js
// A
this.addMutationsPanel = new MutationsPanel(...);
this.addMutationsPanel.earsRow.visibleProperty.value = false;
```

Is superior to:

```js
// B
this.addMutationsPanel = new MutationsPanel({
  earsRowOptions:{
    visiblePropertyOptions:{
      value:false
      }
    }
  });
```

If so, should we embrace pattern A more generally?

**Comment by pixelzoom** [comment]
I do prefer A for this type of use case (configuring a ScreenView). I think it makes for a more concise/encapsulated implementation of what is made invisible.   And while it requires adding public fields that wouldn't otherwise be needed, I think that's an acceptable trade-off (with documentation like I've used in Natural Selection, e.g. "@public for configuring Intro screen only").

I don't know whether we need to prefer one pattern to the exclusion of the other, or how other developers are handling this in their sims.

**Comment by pixelzoom** [comment]
So the current approach ended up with this in IntroScreenView:

```js
    // hide Ears, Teeth, and Limited Food features, by setting visibleProperty for associated UI components
    this.addMutationsPanel.teethRow.visibleProperty.value = false;
    this.environmentalFactorsPanel.limitedFoodCheckbox.visibleProperty.value = false;
    this.populationNode.populationPanel.straightEarsCheckbox.visibleProperty.value = false;
    this.populationNode.populationPanel.floppyEarsCheckbox.visibleProperty.value = false;
    this.populationNode.populationPanel.shortTeethCheckbox.visibleProperty.value = false;
    this.populationNode.populationPanel.longTeethCheckbox.visibleProperty.value = false;
    this.proportionsNode.proportionsPanel.legendNode.earsLegendNode.visibleProperty.value = false;
    this.proportionsNode.proportionsPanel.legendNode.teethLegendNode.visibleProperty.value = false;
    this.proportionsNode.proportionsGraphNode.earsColumn.visibleProperty.value = false;
    this.proportionsNode.proportionsGraphNode.teethColumn.visibleProperty.value = false;
    this.pedigreeNode.allelesPanel.earsRow.visibleProperty.value = false;
    this.pedigreeNode.allelesPanel.teethRow.visibleProperty.value = false;
  }
```

This puts all customization for the _Intro_  screen in one place.  But it would be very difficult for the PhET-iO client to (for example) make all of the user-interface components for Ears visible.  They would have to set individual `visibleProperty` values for many elements. That problem is addressed in the above commit.  

In NaturalSelectionScreenView, I added an instrumented BooleanProperty for each gene, which controls whether that gene is present in the user interface.  Both screens have these elements:

```
-view
  -genes
    earsVisibleProperty
    furVisibleProperty
    teethVisibleProperty
```

Toggling one of these Properties changes the visibility of all user-interface components related to the gene.  This makes it very easy to (for example) add 'Ears' to the _Intro_ screen, or hide 'Teeth' in the _Lab_ screen.

Currently, the PhET-iO client still has access to the `visibilityProperty` of the elements controlled by these Properties.  So you can get into trouble if you mess with both these top-level Properties and the `visibilityProperty` for individual elements.  For example, if you set `earsVisibleProperty` to `true`, you can still make the ears row visible in the Alleles panel.  We can decide whether to make the individual elements `phetioReadOnly: true`, or just advise clients "don't do that".

**Comment by pixelzoom** [comment]
Labeling for design meeting, to review/demonstrate how this screen is implemented.

**Comment by pixelzoom** [comment]
5/7/2020 design meeting @amanda-phet @kathy-phet @ariel-phet @arouinfar 

I demoed the current implementation and instrumentation, and consensus was that this is good.

Re:
> We can decide whether to make the individual elements phetioReadOnly: true, or just advise clients "don't do that". There may be some legitimate use cases where a gene is visible in the user interface, and the client need to hide one of its related UI components.

We decided that it's fine as is.

Closing.
