### ISSUE TITLE
State wrapper is failing with "bunny counts are out of sync"

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#72]
The bunny PhetioGroup is getting out of sync with other sim-specific counts (specifically the ObservableArrays that hold live and dead bunnies) because of https://github.com/phetsims/phet-io/issues/1661.  Deferring State wrapper testing until that issue is resolved.

**Comment by zepumph** [comment]
Because of some other issues, I think it is valuable to be able to use the NS state wrapper, thus I put a bandaid on this issue with a TODO. Once https://github.com/phetsims/phet-io/issues/1661 is taken care of, we should remove the temp fix.

**Comment by pixelzoom** [comment]
Looks like the workaround was removed in https://github.com/phetsims/natural-selection/commit/d8b03d66a1bc32976939af72e30219b4bd767bf5 for https://github.com/phetsims/tandem/issues/170, so I believe this issue can be closed.  @zepumph if I'm incorrect here, please reopen.
