### ISSUE TITLE
lower the max number of bunnies

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#75]
We need to find a way to lower the max number of bunnies in the sim.

The current requirements are:
* If the population is < 1000, mate all bunnies.
* After mating all bunnies, if there are >= 1000 bunnies, stop the sim and display “Bunnies have taken over the world” dialog.

The worst case occurs when there are 999 bunnies.  499 pairs will mate, with 4 offspring per litter, for a total of 1996 new bunnies. Added to the existing 999 bunnies, that results in 2995 (!) bunnies. 

This large number of bunnies causes in a number of problems:

* Creating 1996 bunnies causes my (new, fast) MacBook Pro to pause for a full 2 seconds. There is no way to make this faster - I've already done a lot of optimizing, and we're limited by how long it takes for scenery to add Nodes to the scenegraph.  This performance problem will only get worse as data for the graphs is added.

* Disposing of 2995 bunnies (on Reset All or Start Over) takes a full 1 second, again on my MacBook Pro. Again, no way to improve this.

* In order to support 2995 live bunnies for the Pedigree graph, we'll need to keep a huge number of dead bunnies in memory, possibly exponentially more than if we kept dead ancestors for only 1000 live bunnies.   This will cause us to run out of memory sooner.

* The criteria for when the sim stops is fuzzy and difficult to explain.  It stops when the population is "somewhere between 1000 and 2995”. If bunnies took over the world as soon as the population reaches 1000, it would be easier to deduce that, and maybe not even need an explanation.

* The Population graph’s y scale will need to support a max of 2995 — a number that will rarely be reached in practice, but is possible.  So there will be zoom levels that are unlikely to ever be used, and which allow the user to zoom out excessively.

* 2995 bunnies makes a mess of the screen.  1000 bunnies still totally fills every bit of the screen, 2995 adds nothing. Imo, 1000 actually provides a better “explore” UX. 

So... Unless there's a pedagogical reason that all of the bunnies must mate, I propose that the requirements be changed to:

* Mate bunnies until the population reaches 1000.
* When the population reaches 1000, stop the sim and display “Bunnies have taken over the world” dialog.

@amanda-phet @kathy-phet @ariel-phet thoughts?

**Comment by pixelzoom** [comment]
Two problem that I can see with this:

* Unless all bunnies are allow to mate, the distribution of alleles in the population won't be accurate.
* If mutation(s) are applied on during this final mating, they won't be applied accurately, especially if more than 1 mutation is applied at the same time.  

Maybe we could stick with the original requirements, but reduce the max number of bunnies to 500?  The worst case would then occur when 499 bunnies mate:  499 + ( 498/2 * 4 ) = 1495.

**Comment by pixelzoom** [comment]
Two problem that I can see with my proposal:

* Unless all bunnies are allowed to mate, the distributions of alleles won't be accurate.
* If mutation(s) are applied during this final mating, they won't be applied accurately, especially if more than 1 mutation is applied at the same time.  

Maybe we could stick with the original requirements, but reduce the max number of bunnies to 500?  The worst case would then occur when 499 bunnies mate:  499 + ( 498/2 * 4 ) = 1495.

Here's what the screen looks like for different large numbers of bunnies:

500:
<img width="1054" alt="screenshot_301" src="https://user-images.githubusercontent.com/3046552/81629082-8c4b4080-93bf-11ea-8746-fc5f0ad859b8.png">

750:
<img width="1052" alt="screenshot_303" src="https://user-images.githubusercontent.com/3046552/81629116-a2590100-93bf-11ea-88f3-02d16c497090.png">

1000:
<img width="1052" alt="screenshot_302" src="https://user-images.githubusercontent.com/3046552/81629096-940ae500-93bf-11ea-8b47-b3ab0c169b75.png">

**Comment by pixelzoom** [comment]
In version 1.0.0-dev.37, start the sim, go to Lab screen, press "Add a Mate", and let it run.  This should run until it has created a total of 1434 bunnies (1428 live, 6 dead)...  But on iPad2, the sim pauses for > 10 seconds when creating the final generation of bunnies, then crashes - probably out of memory.  And if I try to start if with `?population=999`, it never does start up - I gave up after 10 minutes on the splash screen.

So we have a memory problem in addition to a performance problem.

**Comment by ariel-phet** [comment]
@pixelzoom I am fine with 500 bunnies personally, I don't think that would really be a detriment to any learning goal. Certainly 750 would be a totally acceptable compromise.

And just a quick note that we no longer support iOS 9.

**Comment by pixelzoom** [comment]
> And just a quick note that we no longer support iOS 9.

I realize that PhET no longer officially supports iOS 9.  But my understanding is that you would still like sims to run on iOS 9.  This sim does not run on iOS 9 -- with no query parameters, it crashes the first time the population gets anywhere near the number of bunnies required to "take over the world".  With a large initial population (via query parameters) it won't even start.   If that's OK, I would like everyone on the team to acknowledge that.  If you'd like to defer the call on whether it needs to run on iOS 9, then we need to be prepared to make compromises -- if it doesn't run on iOS 9 now, it's certainly not going to run on iOS 9 as more features are added, and the memory footprint increases. 

@arouinfar @kathy-phet is it OK if this sim does not run on iOS 9?

**Comment by ariel-phet** [comment]
On the comment above, I would note that we still do test to see if things open on iOS 9, and have not yet run into a case where they do not. It sounds like this simulation will be that case. My personal opinion is that we do not have the resources to support this case, and this sim might be the tipping point to drop even minimal testing on iPad2. I have asked Oliver if any complaints have been received since we dropped iOS 9 support (none to my knowledge).

**Comment by amanda-phet** [comment]
I think a max of 750 bunnies is totally reasonable, sticking with the original requirements (with a worst case scenario of 2245 bunnies shown at one time). The important thing is that the bunnies don't take over too quickly, and also that when they do, the screen is crowded with bunnies to give the appearance of taking over (so at least 750 IMO).

**Comment by pixelzoom** [comment]
5/14/2020 design meeting:

Reduce maxPopulation to 750.

**Comment by ariel-phet** [comment]
Note - spoke with @kathy-phet in regards to https://github.com/phetsims/natural-selection/issues/75#issuecomment-627509629

She signs off on this sim never properly running on iOS9
