### ISSUE TITLE
Email teacher when we publish this sim

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#8]
Regarding https://github.com/phetsims/natural-selection/issues/3, one teacher had emailed twice and I think he might appreciate a follow-up once the port is published. I don't want to include his email here, so I will leave the issue open and assigned to me until we publish.

https://phet.unfuddle.com/a#/projects/9404/tickets/by_number/3731

**Comment by pixelzoom** [comment]
1.1.0 has been published, so you can notify this teacher.

**Comment by amanda-phet** [comment]
Email sent.
