### ISSUE TITLE
initial state of the Proportions graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#80]
Until the generation clock starts running, there is no Proportions data to display.  What does the Proportions graph look like before the "Add a Mate" or "Play" button is pressed?  Please fill in the empty whitespace in the screenshots below with what you'd like to see.  High priority please, because I'm trying to wrap up implementation of this graph.

With no query parameters (default):

<img width="1078" alt="screenshot_324" src="https://user-images.githubusercontent.com/3046552/82611193-2f007d80-9b7d-11ea-9ee9-03d21c504f55.png">

With `?labMutations=FET&labPopulation=5Ffeett,5ffEEtt`:

<img width="1072" alt="screenshot_326" src="https://user-images.githubusercontent.com/3046552/82611376-9fa79a00-9b7d-11ea-9c97-79bdb3e49fb6.png">

**Comment by pixelzoom** [comment]
Slack:

Amanda McGarry:spiral_calendar_pad:  3:37 PM
... I’ll have to get back to you when I can think about this.. seems either (1) nothing, like the population graph, or (2) 100% white tall-ear short-teeth bunnies.

Chris Malley  4:02 PM
(1) You'll have to define "nothing" -- a blank rectangle? Row and column labels with no bars? How about a blank rectangle with "No Data"? 
(2) is not an option. The initial population may be much more diverse, if set through query parameters. And the "start" population is not defined until the generation clock starts - otherwise we would start with a total of 1 bunny in the default case.

**Comment by pixelzoom** [comment]
I'm going to go with "No Data" for now, because it seems like a nice straightforward solution. See screenshot below.  This is similar to 'Select a Bunny' for the Pedigree graph - same font size and position.

<img width="1112" alt="screenshot_327" src="https://user-images.githubusercontent.com/3046552/82613477-9a991980-9b82-11ea-8d79-b9247c6e7d72.png">

**Comment by pixelzoom** [comment]
Slack:

Amanda McGarry  4:51 PM
(1) A blank rectangle is what I had in mind.
(2) I was describing the default scenario, but if it’s a more diverse population the bars would reflect that population. Is it possible to know what the population is prior to the start of generation 0? Or do we only know once the clock starts?

I’m fine with “no data”. That seems perfectly reasonable. I can comment in the issue as well, but just brainstorming here while I have a moment

Chris Malley  5:05 PM
We don't know until the clock starts because of the lone bunny + "Add a Mate" case. The "start" should not be 1 in that case, it should be 2.  So we can't sample the population until the generation clock starts.

**Comment by pixelzoom** [comment]
Master and [1.0.0-dev.43](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.43/phet/natural-selection_en_phet.html) display "No Data" when there is no data to display. @amanda-phet are you satisfied with this solution, or does this issue need more discussion?

**Comment by amanda-phet** [comment]
I think it looks good.
