### ISSUE TITLE
state of the Proportions graph when bunnies take over the world

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#82]
When the population exceeds the maximum (750), the sim stops and displays the "Bunnies have taken over the world" dialog.  This occurs _immediately_ after all bunnies have mated, giving birth to a new generation. In that case, "Start of Generation" and "Currently" will be identical times, and will therefore show identical values in the Proportions graph.  

For example, see the screenshot below.  Generation 5 had a total population of 480 bunnies. They mated to produce generation 6, with a total population of 1428.  That exceeds the maximum population (750), so the sim immediately stops.   "Start of Generation" and "Currently" values are identical because "Start" and "Currently" are identical times. 

<img width="1114" alt="screenshot_328" src="https://user-images.githubusercontent.com/3046552/82613968-ed270580-9b83-11ea-8ed3-e94616521d3c.png">

This all makes sense (to me), but I wanted to make sure that you are aware of this behavior.  Unless there's a problem, feel free to close this issue after reviewing.

**Comment by amanda-phet** [comment]
This is what I would expect to happen. 

"Start of Generation" = "Currently" for the first 25% of any generation time interval, so this is going to happen in other situations anyway.
