### ISSUE TITLE
tune the environmental factors model

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#86]
I've completed a rudimentary implementation of environmental factors for the purposes of (a) providing graph data, and (b) tuning the model.  I need help from the team with tuning the model.

Per Zoom discussions with @amanda-phet, here are the requirements for how the environmental factors affect bunny mortality:

Wolves:
* When wolves are enabled, they eat both white and brown bunnies, but eat more of the bunnies whose fur color does not match their environment. For example, in an "arctic" environment, more brown bunnies will be eaten.
* The number eaten should be a percentage of the population, randomly chosen from a percentage range.

Food:
* With unlimited tender food, no bunnies die.
* With limited tender food, some percentage of all bunnies die of starvation, regardless of their teeth genes. The number that die should be a percentage of the population, randomly chosen from a percentage range.
* With unlimited tough food, short-toothed and long-toothed bunnies dies, but more short-toothed bunnies dies.  The number that dies should be a percentage of the population, randomly chosen from a percentage range.
* Limited tough food, is similar to unlimited tough food, but more bunnies of both type die.

The above requirements have been implemented.  Until we get a handle on setting the percentages, all bunnies die at the same time, instead of spreading out across the "death" portion of the generation clock.

I need help from the team here, because I don't know what specific behavior you're trying to create.  And the model and requirements differ greatly from the Java version.  So... I've added 6 query parameters for tuning the environmental factors model.   The query parameters, documented in [NaturalSelectionQueryParameters](https://github.com/phetsims/natural-selection/blob/master/js/common/NaturalSelectionQueryParameters.js), are:

```
// Wolves
wolvesPercentToKill
wolvesEnvironmentMultiplier

// Food
limitedFoodPercentToKill
toughFoodPercentToKill
shortTeethMultiplier
limitedFoodMultiplier
```

Please experiment with these query parameters in [1.0.0-dev.43](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.43/phet/natural-selection_en_phet.html).  Let me know what values produce the behavior that you're interested in creating.   If you have questions about the query parameters, or want to experiment together, let me know.

Finally, if you run the sim with `?log`, you'll see useful log messages in the console that describe how many bunnies have died and why.   The Proportions graph is also fully functional, and will show differences in start/end populations.  The Population graph is not implemented.

**Comment by amanda-phet** [comment]
Is it possible for you to share percentages from the java sim? We are trying to match what happens in that sim, and I assumed it used percentages.

**Comment by pixelzoom** [comment]
I'll try to locate Java values, but it's not at all obvious or straightforward.  And the food model is totally different in Java vs HTML5, so I'm not sure why trying to match the Java sim is even relevant for food.

**Comment by pixelzoom** [comment]
I'll try to locate Java values, but it's not at all obvious or straightforward.  There are certainly no "percentage" constants like we have here.  And the food model is totally different in Java vs HTML5, so I'm not sure why trying to match the Java sim is even relevant for food.

**Comment by amanda-phet** [comment]
The food model for tough food is similar to Java in that I want to recreate the same behavior, but if there aren't obvious percentages then we will have to just come up with some. I can play with the values and try to get them close to what I see happening in the Java sim.

**Comment by pixelzoom** [comment]
"Like the Java version" has not been a useful requirement for 3 reasons: 
1. The Java implementation is complicated and mostly undocumented, so it's difficult to isolate specific behavior.
2. The HTML5 design has provided no concrete examples or scenarios for what you want to reproduce.
3. The HTML5 requirements differ significantly from the Java version, especially wrt how environmental factors are applied.

The Java implementations of wolves and food are [Frenzy.java](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Fnatural-selection%2Fsrc%2Fedu%2Fcolorado%2Fphet%2Fnaturalselection%2Fmodel%2FFrenzy.java&commit=75159) and [Famine.java](https://phet.unfuddle.com/a#/projects/9404/repositories/23262/file?path=%2Ftrunk%2Fsimulations-java%2Fsimulations%2Fnatural-selection%2Fsrc%2Fedu%2Fcolorado%2Fphet%2Fnaturalselection%2Fmodel%2FFamine.java&commit=75159) respectively.  Feel free to have a look to see if you can make any sense of them. I have been unable to extract anything useful.

I did meet with JO to discuss the Java implementation on 1/22/2020. He has little recollection of the sim, and recommended that I ignore the Java version and implement something better.

Because I wasn't getting anywhere with the Java version, I discussed the wolves and food models with @amanda-phet on 5/19/2020.  That's summarized in https://github.com/phetsims/natural-selection/issues/86#issue-625261096, and that's what I've implemented.  

So... I'm sorry that there are no Java values to use as a starting point, and that the team must spend significant time experimenting with query parameters.  If anyone has alternative suggestions for how to proceed, I'm all ears.  And if there is a specific Java scenario that you want to reproduce, please provide details (step-by-step) and I'll do my best to try to reproduce it in HTML5.

**Comment by amanda-phet** [comment]
I'm currently playing with the following values: 

https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.43/phet/natural-selection_en_phet.html?secondsPerGeneration=2&wolvesPercentToKill=.35,.4&wolvesEnvironmentMultiplier=2.4&limitedFoodPercentToKill=.55,.7&toughFoodPercentToKill=.4,.7&shortTeethMultiplier=1.8

They might be too high if the user stacks environmental factors, but maybe that's a good thing, I'm not sure.

**Comment by pixelzoom** [comment]
toughFoodPercentKill (0.7) * shortTeethMultiplier (1.8) = 1.26  --- That's will fail if you have assertions enabled, because you can't kill more that 100% (1.0) of the population.

wolvesPercentToKill (0.4) * wolvesEnvironmentMultiplier (2.4) = 0.96  --- Killing 96% of the bunnies that don't match their environment seems a little extreme.

**Comment by amanda-phet** [comment]
Ah, right I made these values before I spoke with you and I clearly wasn't using the multiplier correctly!

**Comment by pixelzoom** [comment]
5/28/2020 design meeting @amanda-phet @kathy-phet @ariel-phet 

Kathy suggested collecting data from the Java version to try to deduce the functions that it's applying for environmental factors.  @amanda-phet will take a stab at that.

@amanda-phet via Slack:
> I’m tracking bunny percentages killed here, btw (https://docs.google.com/spreadsheets/d/1f-gmNNxx0NKgaV0SvFSDv-9qh2dk4a-sGBaBAi-hvXM/edit#gid=0) and just white bunnies seem to consistently be eaten at around the same rates, but it’s complicated when we have both brown and white.  it seems like the wolves might eat a higher percentage of brown bunnies as the population increases

**Comment by amanda-phet** [comment]
The values I'm currently using are:

wolvesPercentToKill=.35,.4
wolvesEnvironmentMultiplier=2.3
toughFoodPercentToKill=.4,.7
shortTeethMultiplier=1.4
limitedFoodPercentToKill=.55,.7
limitedFoodMultiplier=1.2

Assigning to @pixelzoom to change the defaults to these, and when convenient publish a dev version with these values for team members to use.

**Comment by pixelzoom** [comment]
It looks like these are the values that @amanda-phet was using in https://github.com/phetsims/natural-selection/issues/98#issuecomment-639694444. When I run the sim with those values with `?ea`, I get this assertion failure:

> Assertion failed: limitedFoodMultiplier * shortTeethMultiplier * toughFoodPercentToKill.max must be <= 1

Only public query parameters result in the "Invalid Query Parameter" dialog.  So when using internal query parameters (like these), it's important that you run with `?ea`.  That's the only way that you're going to find out about problems with the values for internal query parameters. 

Back to @amanda-phet to choose new values.  Another option would be to clamp (limit) the result of `limitedFoodMultiplier * shortTeethMultiplier * toughFoodPercentToKill.max`, but I have a feeling that may be undesirable.

**Comment by pixelzoom** [comment]
If using a dev version, you'll need to run natural-selection_all_phet_debug.html, since other html files have assertions stripped out.

**Comment by pixelzoom** [comment]
@amanda-phet You'll probably want to hold off on further work on this issue until #97 and #98 are completed, since they will change the model behavior.

**Comment by pixelzoom** [comment]
Update: #97 is done, but #98 still has some work to do.

**Comment by pixelzoom** [comment]
7/7/2020 discussed with @amanda-phet.  #98 is done, so OK to proceed with this.  She'll provide new query parameter values.

**Comment by amanda-phet** [comment]
I'm fairly confident I want the values to be as follows:

wolvesPercentToKill=.35,.4
wolvesEnvironmentMultiplier=2.3
limitedFoodPercentToKill=.6,.7
toughFoodPercentToKill=.4,.7
shortTeethMultiplier=1.4
limitedFoodMultiplier=1.02
minBunniesForFood=4
minBunniesForWolves=5

But I'm getting assertions at 10:00 when I run with `?ea` and Wolves are checked, so I might still be doing something wrong.

**Comment by pixelzoom** [comment]
> But I'm getting assertions at 10:00 when I run with ?ea and Wolves are checked, so I might still be doing something wrong.

What are the assertion messages? (in the browser console)

**Comment by pixelzoom** [comment]
> But I'm getting assertions at 10:00 when I run with ?ea and Wolves are checked, so I might still be doing something wrong.

What are the assertion messages? (in the browser console)

With master, or some dev version?

**Comment by amanda-phet** [comment]
From slack:

Trying to run with these parameters: http://phettest.colorado.edu/natural-selection/natural-selection_en.html?ea&brand=phet&wolvesPercentToKill=.35,.4&wolvesEnvironmentMultiplier=2.3&limitedFoodPercentToKill=.6,.7&toughFoodPercentToKill=.4,.7&shortTeethMultiplier=1.4&limitedFoodMultiplier=1.02&minBunniesForFood=4

Assertion failed: reentry detected, value=53.41800000000021, oldValue=53.402000000000214
assert.js:22 Uncaught Error: Assertion failed: reentry detected, value=53.41800000000021, oldValue=53.402000000000214
    at window.assertions.assertFunction (assert.js:22)
    at NumberProperty._notifyListeners (Property.js:270)
    at NumberProperty.set (Property.js:171)
    at NumberProperty.set value [as value] (Property.js:343)
    at GenerationClock.stepTime (GenerationClock.js:129)
    at GenerationClock.step (GenerationClock.js:109)
    at LabModel.stepOnce (NaturalSelectionModel.js:272)
    at LabModel.step (NaturalSelectionModel.js:258)
    at Sim.js:292
    at Action.execute (Action.js:225)

I'm not sure if this is helpful or not.

**Comment by pixelzoom** [comment]
I change to the query-parameter values specified in https://github.com/phetsims/natural-selection/issues/86#issuecomment-656436464, and I don't see any problem with those values with `?ea`.   

I also can't reproduce the problem reported in https://github.com/phetsims/natural-selection/issues/86#issuecomment-656466934, and it's not happening in CT.

**Comment by pixelzoom** [comment]
In the above commit, I changed to the query-parameter values specified in https://github.com/phetsims/natural-selection/issues/86#issuecomment-656436464, and I don't see any problem with those values with `?ea`.     You can verify that query-parameter values by running with `?log` - the first thing the sim will do is print the values of all sim-specific query parameters to the browser console.

I also can't reproduce the problem reported in https://github.com/phetsims/natural-selection/issues/86#issuecomment-656466934, and it's not happening in CT.

**Comment by pixelzoom** [comment]
I can't reproduce the problem reported in https://github.com/phetsims/natural-selection/issues/86#issuecomment-656466934, and it's not happening in CT.  @amanda-phet do you have any more details about what "Trying to run" means? Where you interacting with any other controls, like the fast-forward button?  Exact steps to reproduce are always helpful.

**Comment by pixelzoom** [comment]
"reentry detected" seems unrelated to this issue (it's related to the GenerationClock), and has been moved to #127.

@amanda-phet please review the query parameter changes. If you're happy with the behavior, you can close this issue. Otherwise describe change requests and assign back to me.

**Comment by amanda-phet** [comment]
Sounds like what I was experiencing wasn't related to the parameters. I'm not having any issues now, and all seems to be working great!
