### ISSUE TITLE
Proportions "Values" checkbox is buggy

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#88]
It's not behaving as it should, very obvious when you use it.  Instead of just hiding the percentage values, it hides the entire bars.

**Comment by amanda-phet** [comment]
Also, when I was using it in studio (either using the checkbox or the property), I would check it again and it wouldn't show anything. I had to go to another generation and then back to see the content.

**Comment by pixelzoom** [comment]
Yes @amanda-phet, that's the behavior that I'm seeing.

**Comment by pixelzoom** [comment]
Fixed in master via the above commit.  Closing.
