### ISSUE TITLE
 Assertion failed: value failed isValidValue: 8

### ISSUE THREAD

**Issue by zepumph** [phetsims/natural-selection#90]
The problem is about `naturalSelection.labScreen.model.proportionsModel.generationProperty`. It looks like some how the value is being incremented beyond the range of the generation. In the pasted example. The downstream sim was being set to generation 6, but then somehow, by the time the generationProperty notified, therefore validating itself, its value was now 8.

```
VM7914:1 Uncaught Error: Assertion failed: value failed isValidValue: 8
    at eval (eval at window.assertions.assertFunction (assert.js:22), <anonymous>:1:7)
    at window.assertions.assertFunction (assert.js:22)
    at Object.isValueValid (ValidatorDef.js:298)
    at validate (validate.js:27)
    at NumberProperty.validateNumberProperty (NumberProperty.js:94)
    at NumberProperty.js:125
    at TinyEmitter.emit (TinyEmitter.js:69)
    at NumberProperty._notifyListeners (Property.js:273)
    at PhaseCallback.listener (Property.js:323)
    at PropertyStateHandler.attemptToApplyPhases (PropertyStateHandler.js:262)
```

I'm going to discuss with @pixelzoom to see if there are any listeners incrementing the generationProperty that perhaps shouldn't fire when setting PhET-iO state, or need to be reworked in another way.

**Comment by pixelzoom** [comment]
@zepumph and I paired on this via Zoom.  The problem is in NumberProperty, where it's not creating the tandem for the `rangeProperty` that it owns.  So the rangeProperty is therefore not being saved and restored.  

@zepumph has a fix that he's going to commit after some testing.

**Comment by zepumph** [comment]
Thanks @pixelzoom, a few more notes:

This was hard to reproduce because of a listener order where it is likely that this multilink was firing before the generationProperty validation:

```

    // When the sim starts playing or the current generation changes, show the current generation immediately.
    Property.multilink(
      [ isPlayingProperty, currentGenerationProperty ],
      ( isPlaying, currentGeneration ) => {
        if ( isPlaying ) {
          this.generationProperty.setValueAndRange( currentGeneration, new Range( 0, currentGeneration ) );
        }
      } );
```

So the lack of instrumentation for generationProperty.rangeProperty was hidden.

Wrapping that listener such that it didn't happen when setting state demonstrated this problem consistently.

To fix this, we updated NumberProperty to automatically instrument rangeProperty when the NumberProperty is instrumented. This feels more robust to me. I'll leave open and check back after a few CT runs.

**Comment by pixelzoom** [comment]
@zepumph did you mean to assign this back to me? If so, feel free to close. Otherwise let me know what else needs to be done here.

**Comment by zepumph** [comment]
I don't see this on CT. That said we never saw this on CT. We can reopen if it re-appears. Closing
