### ISSUE TITLE
When you click "start over", reset environmental factors selections

### ISSUE THREAD

**Issue by amanda-phet** [phetsims/natural-selection#91]
When I click "start over" to do a new experiment, I want the environmental factors to be reset so that my bunnies don't all die immediately. I found this while working with query parameters and iterating.

**Comment by pixelzoom** [comment]
I've made this change, and it's working nicely in standalone.  But when Launched from Studio, the state of the Environmental Factors checkboxes is reset correct with "Reset All" button, but not with "Start Over" buttons.  I'm not sure why that is, because it's the same code path.  But I'll investigate.

**Comment by pixelzoom** [comment]
Ugh. I see why Rest All is behaving as desired, but not Start Over. `ResetAllButton` has this listener:

```js
  // Wrap the listener for all cases, since PhET-iO won't be able to call this.isPhetioInstrumented() until the super call is complete.
  options.listener = () => {
    passedInListener();

    // every ResetAllButton has the option to reset to the last PhET-iO state if desired.
    if ( options.phetioRestoreScreenStateOnReset &&
         this.isPhetioInstrumented() && // even though this is Tandem.REQUIRED, still be graceful if not yet instrumented
         _.hasIn( window, 'phet.phetio.phetioEngine' ) ) {
      phet.phetio.phetioEngine.phetioStateEngine.restoreStateForScreen( options.tandem );
    }
  };
```

So questions for PhET-iO team...

1. Why is this handled in `ResetAllButton` and not in Property? This seems like a very odd place to do handle this, and will result in exactly the type of problem that I'm seeing in NS.

2. If it can't be changed, how can I make the NS `StartOverButton` behave similarly to `ResetAllButton`?

**Comment by pixelzoom** [comment]
Here's some more info to clarify the problem in NS.  In NaturalSelectionModel.js:

```js
  /**
   * Resets the entire model when the 'Reset All' button is pressed.
   * @public
   */
  reset() {

    this.startOver();

    // environmental factors
    this.environmentProperty.reset();
  }

  /**
   * Resets the part of the model that is reset when the 'Start Over' button is pressed.
   * @public
   */
  startOver() {

    this.simulationModeProperty.reset();
    this.isPlayingProperty.reset(); // see https://github.com/phetsims/natural-selection/issues/55
    this.generationClock.reset();

    this.genePool.reset();

    this.bunnyCollection.reset();
    this.initializeGenerationZero();

    this.wolfCollection.reset();
    this.food.reset();

    this.populationModel.reset();
    this.proportionsModel.reset();
    this.pedigreeModel.reset();
  }
```

Pressing `ResetAllButton` calls `reset`.

Pressing `StartOverButton` calls `startOver`. It's supposed to behave like a subset of `reset`, but does not because of the `restoreStateForScreen` code in `ResetAllButton`.

**Comment by pixelzoom** [comment]
This issue is on hold until phetsims/phet-io#1678 is addressed.

**Comment by pixelzoom** [comment]
Moving the "Start Over" problem to a new issue, https://github.com/phetsims/natural-selection/issues/95.

Closing.
