### ISSUE TITLE
divide generation clock into 'food' and 'wolves' slices

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#92]
@amanda-phet and I identified a potential issue with having both wolves and food being applied simultaneously.  It makes it impossible to determine what part of the population decline was due to wolves vs food.  

We started discussing ways to remedy this.  One idea was to divide the "death" portion of the clock (3:00-9:00) into 2 pieces.  From 3:00-6:00, bunnies would eat/starve.  From 6:00-9:00, wolves would eat.  This would allow you to look at the Population graph to see what the population change was during those intervals.

Other ideas?

**Comment by amanda-phet** [comment]
5/28/20 meeting: 

We want to proceed with this approach of dividing the clock up. 

Can you use #93c83d for 3:00-6:00?

**Comment by pixelzoom** [comment]
To make the association between the environmental factors and the generation clock, I experimented with something like this:

<img width="261" alt="screenshot_365" src="https://user-images.githubusercontent.com/3046552/83566329-0feadf80-a4dd-11ea-931b-889325df23eb.png">

I like this direction. But for hiding checkboxes via PhET-iO, it creates major headaches for layout problems.  The above took me ~15 minutes to implement, but will probably take another ~3 hours to work out the PhET-iO issues.

@amanda-phet thoughts?

**Comment by pixelzoom** [comment]
After discussing with @amanda-phet on Slack, here's the next iteration. We like this one better, and it has no PhET-iO issues.

<img width="256" alt="screenshot_366" src="https://user-images.githubusercontent.com/3046552/83569781-42e3a200-a4e2-11ea-8da5-9e94016dad57.png">

**Comment by kathy-phet** [comment]
Seems nice.

**Comment by pixelzoom** [comment]
> Can you use #93c83d for 3:00-6:00?

That shade of green looks washed out, even after making the "reveal" more transparent (40% opacity):

<img width="75" alt="screenshot_368" src="https://user-images.githubusercontent.com/3046552/83570511-68bd7680-a4e3-11ea-8519-dc040b30c787.png"> <img width="73" alt="screenshot_369" src="https://user-images.githubusercontent.com/3046552/83570519-6bb86700-a4e3-11ea-89f7-80da0ab5d993.png">

`rgb( 0, 210, 0 )` looks a little better to me, but still a little washed out. 

<img width="83" alt="screenshot_371" src="https://user-images.githubusercontent.com/3046552/83570680-b76b1080-a4e3-11ea-9269-457ca7262021.png">
<img width="71" alt="screenshot_372" src="https://user-images.githubusercontent.com/3046552/83570685-ba660100-a4e3-11ea-9d7d-103cae544a2c.png">

Anyway... I've made it easy to adjust this color, so we can tweak as much as we want.

**Comment by pixelzoom** [comment]
@amanda-phet This is ready for your review in master or [1.0.0-dev.46](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.46/phet/natural-selection_en_phet.html).

A couple of remaining questions:
* Might using shades of green for both food and fur lead to color-coding misconceptions?
* Should the food color-coding be reviewed for color-blindness compatibility?

**Comment by amanda-phet** [comment]
>Might using shades of green for both food and fur lead to color-coding misconceptions?

This is something I've wondered about, but it is difficult to find colors to associate with traits in a helpful way, so we picked three colors that are recommended for color-blindness. I suppose we could find a different color for food, or use the same color for both food and wolves (since they are in different regions now). 

>Should the food color-coding be reviewed for color-blindness compatibility? 

I did a color-blind test and the green and pink regions in the generation clock aren't great for red-blind folks. Let me try playing with the colors a bit.

**Comment by pixelzoom** [comment]
When @amanda-phet and I were reviewing this issue on Zoom, we discussed the possibility of dividing the clock into 3rds, so that the amount of time that wolves are animating is longer. Something like one of the 2 examples below.  @amanda-phet let me know if this is something that you want to try.

Options (1):
```js
  // Generation Clock
  CLOCK_FOOD_RANGE: new Range( 1/6, 3/6 ), // percentage of clock cycle when bunnies are starved by food factors
  CLOCK_WOLVES_RANGE: new Range( 3/6, 5/6 ), // percentage of clock cycle when bunnies are eaten by wolves
```

<img width="67" alt="screenshot_381" src="https://user-images.githubusercontent.com/3046552/84084294-6609c800-a9a0-11ea-8f12-3d851a4732dd.png">

Option (2):
```js
  // Generation Clock
  CLOCK_FOOD_RANGE: new Range( 1/3, 2/3 ), // percentage of clock cycle when bunnies are starved by food factors
  CLOCK_WOLVES_RANGE: new Range( 2/3, 1 ), // percentage of clock cycle when bunnies are eaten by wolves
```

<img width="64" alt="screenshot_382" src="https://user-images.githubusercontent.com/3046552/84084298-6904b880-a9a0-11ea-9984-45c72cbf56cd.png">

**Comment by amanda-phet** [comment]
I was imagining option 1. Can you go ahead and implement it?

**Comment by pixelzoom** [comment]
Option (1) is implemented in master and [1.0.0-dev.51](https://phet-dev.colorado.edu/html/natural-selection/1.0.0-dev.51/phet/natural-selection_en_phet.html).

**Comment by pixelzoom** [comment]
The new division of the clock seems to be working nicely, and was further refined in #110.

In https://github.com/phetsims/natural-selection/issues/92#issuecomment-638265250, @amanda-phet said:
> I did a color-blind test and the green and pink regions in the generation clock aren't great for red-blind folks. Let me try playing with the colors a bit.

I think this is the last bit to address for this issue.  Or maybe more it to a new issue and close this one?

**Comment by pixelzoom** [comment]
Actually, I guess both of these color-related questions are still open:

> * Might using shades of green for both food and fur lead to color-coding misconceptions?
> * Should the food color-coding be reviewed for color-blindness compatibility?

**Comment by pixelzoom** [comment]
In 7/2/2020 design meeting, everyone reported being pleased with the new division of the generation clock.  

The remaining color issues are now being tracked in https://github.com/phetsims/natural-selection/issues/114.

Closing.
