### ISSUE TITLE
checkboxes for traits in Proportions graph

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#94]
In https://github.com/phetsims/natural-selection/issues/57#issuecomment-634840142, @amanda-phet suggested adding checkboxes to show/hide traits in the Proportions graph.

We discussed 2 designs in 5/28/2020 design meeting:

(1) Checkboxes in Proportions panel.  Something like this, but with something less heavy than curly brackets:

<img width="225" alt="screenshot_345" src="https://user-images.githubusercontent.com/3046552/83058521-b6cf0780-a015-11ea-8244-5df7a3907f55.png">

(2) Checkboxes next to the "Fur", "Ears", "Teeth" column headings, suggested by @ariel-phet.

We decide to try (1) first.

**Comment by pixelzoom** [comment]
I tried 2 designs for the panel:

<img width="187" alt="screenshot_347" src="https://user-images.githubusercontent.com/3046552/83193308-03891000-a0f4-11ea-8f0b-7c670487b7bf.png">

<img width="192" alt="screenshot_349" src="https://user-images.githubusercontent.com/3046552/83193318-06840080-a0f4-11ea-82bc-11306d90d06e.png">

@amanda-phet said in Slack:
> It’s a lot of lines in the second one.. leaning toward the first (also make that horizontal separator wider)

... so I went with the first one.  It worked nice in cases like this:

<img width="900" alt="screenshot_351" src="https://user-images.githubusercontent.com/3046552/83193414-38956280-a0f4-11ea-98b1-b3ee1abf0fcd.png">

But then I discovered this case, which @amanda-phet agreed is bad:

<img width="904" alt="screenshot_350" src="https://user-images.githubusercontent.com/3046552/83193438-464ae800-a0f4-11ea-95bf-f8a65cb67551.png">

Besides the above problem, the panel is starting to look busy/cluttered -- exactly the problem that we were trying to solve with this feature.   So @amanda-phet and I agree to bail on this approach.   I committed my changes in https://github.com/phetsims/natural-selection/commit/a555b80587a318a1b03d7cc5869d7c59830e2870 in case I want to come back to it, but will immediately revert them.

**Comment by pixelzoom** [comment]
Next I tried the design suggested by @ariel-phet.  This works better.  I don't love it, but it does the job.   And there are no PhET-iO issues.   

@amanda-phet you can test drive in [1.0.0-dev.45] and let me know whether to keep, revert, or try something else.

<img width="904" alt="screenshot_353" src="https://user-images.githubusercontent.com/3046552/83195278-3d0f4a80-a0f7-11ea-8bfc-5d085d8bfaeb.png">

<img width="900" alt="screenshot_354" src="https://user-images.githubusercontent.com/3046552/83195290-41d3fe80-a0f7-11ea-9e90-dc5844205b82.png">

<img width="905" alt="screenshot_356" src="https://user-images.githubusercontent.com/3046552/83195303-45678580-a0f7-11ea-8e88-ce931d96a37a.png">

**Comment by amanda-phet** [comment]
I think this works.

**Comment by amanda-phet** [comment]
I closed this, but realized @pixelzoom might still need it open before finalizing the change. Please close if it's complete.

**Comment by pixelzoom** [comment]
Thanks @amanda-phet. Everything is done here, closing.
