### ISSUE TITLE
"Start Over" does not reset state

### ISSUE THREAD

**Issue by pixelzoom** [phetsims/natural-selection#95]
In https://github.com/phetsims/natural-selection/issues/91, I discovered that unlike pressing the "Reset All" button, pressing the "Start Over" button does not properly reset state.  That's because ResetAllButton is responsible for resetting state, an approach that violates MVC and makes it impossible to reset state in other ways.  

See https://github.com/phetsims/phet-io/issues/1678, the pre-requisite to resolving this issue.

**Comment by pixelzoom** [comment]
Over in https://github.com/phetsims/phet-io/issues/1678#issuecomment-635927838, I noted:
> I think I'd better discuss with the NS design team before doing any more work here. Thinking about this more, it's not clear to me what "Start Over" means in the context of saved state that (for example) is somewhere in the middle of generation 2.

**Comment by pixelzoom** [comment]
I discussed this issue with @amanda-phet via Zoom.   It is indeed odd that Reset All will restore to some PhET-iO state, while Start Over will always go back to the time before the generation clock was started.  But that seems to be the correct semantics for "Start Over".  If that's a problem for the PhET-iO client, then they should probably be using the query parameters to set up an initial population, not running the simulation and saving the state of some partially-completed experiment.   We also don't know how this will be used.   So the resolution to this issue is "do nothing". 

Closing.

**Comment by zepumph** [comment]
A few notes on how we would set this up to support Start Over going back to the previously set PhET-iO State.

One option: update initialValue of Properties on state set such that startOver goes back to that value. This could be done manually, or perhaps with a PropertyIO subtype/mixin that makes sure that initialValue is also set during phet-io state set. This would not handle non-Properties. It looks like there are some dynamic elements that would need to be dealt with as well.

Another option: we could expand on our algorithm for setting state when the resetAllButton is pressed, and expose a method or value of `PhetioStateEngine.mostRecentSavedState` to be utilized by sim-specific logic in StartOverButton or perhaps `NaturalSelectionModel.startOver()`.

After writing these out, I am happy that we don't need to do further investigation right now!

**Comment by samreid** [comment]
In https://github.com/phetsims/gravity-and-orbits/issues/343 we are developing a way to restore individual scenes.  @amanda-phet if there was built-in support for restoring the initial state (separately from the existing supported behavior of resetting the whole screen), would we want to leverage it in Natural Selection for "Start Over"?

**Comment by amanda-phet** [comment]
Possibly. I feel comfortable with the decision we made to make "Start Over" actually start over, and leave it to the client to hide that button if they don't want to use it. But I'm open to discussing it again if this becomes a possibility.

**Comment by pixelzoom** [comment]
No, I don't see a need to leverage phetsims/gravity-and-orbits#343  in Natural Selection.

We decided that "Start Over" means to go back to the point where we have the initial population, and that "Start Over" should not restore to a state that was saved after the generation clock started running.   When a state like that has been saved, it will be odd that "Start Over" and "Reset All" take you to different states, and clients should consider hiding the "Start Over" button. But there's not a lot of value in saving a state after the generation clock has been started, and it's preferable to set up an experiment using the query parameters that configure the initial population.  So we should document this in the PhET-iO Client Guide (@amanda-phet should we start an issue for things to include in the Client Guide?)

@amanda-phet if you still agree, feel free to close this issue.  Otherwise label for design meeting.
